In [49]:
import pandas as pd
import os
import numpy as np
import re
import requests
import json
from bs4 import BeautifulSoup as bs
from time import sleep
from random import randrange

In [50]:
os.chdir("TermProject")
files = os.listdir()
file_list = []
years = []
df_list = []
files

FileNotFoundError: [Errno 2] No such file or directory: 'TermProject'

In [51]:
# I got a number of sales records spreadsheets from the assessor
for f in files:
    if f.__contains__('Resi'):
        file_list.append(f)
        pattern = "(\d{4})-(\d{4})"
        pattern = re.compile(pattern)
        [f_years] = pattern.findall(f)
        print(f_years)
        years.append(f_years)

file_list

('2020', '2022')
('2019', '2021')
('2017', '2019')
('2014', '2016')
('2015', '2017')
('2016', '2018')
('2018', '2020')

['Resi Sales 2020-2022.xlsx',
 'Resi Sales 2019-2021.xlsx',
 'Resi Sales 2017-2019.xlsx',
 'Resi Sales 2014-2016.xlsx',
 'Resi Sales 2015-2017.xlsx',
 'Resi Sales 2016-2018.xlsx',
 'Resi Sales 2018-2020.xlsx',
 'Resi Sales 2020-2022.xlsx',
 'Resi Sales 2019-2021.xlsx',
 'Resi Sales 2017-2019.xlsx',
 'Resi Sales 2014-2016.xlsx',
 'Resi Sales 2015-2017.xlsx',
 'Resi Sales 2016-2018.xlsx',
 'Resi Sales 2018-2020.xlsx']

In [52]:
df_list = []
df_14_16 = pd.read_excel(file_list[0], header=2, dtype={"Parcel ID": str})
df_list.append(df_14_16)
df_17_19 = pd.read_excel(file_list[1], header=2, dtype={"Parcel ID": str})
df_list.append(df_17_19)
df_15_17 = pd.read_excel(file_list[2], header=2, dtype={"Parcel ID": str})
df_list.append(df_15_17)
df_18_20 = pd.read_excel(file_list[3], header=2, dtype={"Parcel ID": str})
df_list.append(df_18_20)
df_19_21 = pd.read_excel(file_list[4], header=2, dtype={"Parcel ID": str})
df_list.append(df_19_21)
df_16_18 = pd.read_excel(file_list[5], header=2, dtype={"Parcel ID": str})
df_list.append(df_16_18)
df_20_22 = pd.read_excel(file_list[6], header=2, dtype={"Parcel ID": str})
df_list.append(df_20_22)

/opt/homebrew/Caskroom/miniforge/base/lib/python3.10/site-packages/openpyxl/worksheet/header_footer.py:48: UserWarning: Cannot parse header or footer so it will be ignored
  warn("""Cannot parse header or footer so it will be ignored""")
/opt/homebrew/Caskroom/miniforge/base/lib/python3.10/site-packages/openpyxl/worksheet/header_footer.py:48: UserWarning: Cannot parse header or footer so it will be ignored
  warn("""Cannot parse header or footer so it will be ignored""")
/opt/homebrew/Caskroom/miniforge/base/lib/python3.10/site-packages/openpyxl/worksheet/header_footer.py:48: UserWarning: Cannot parse header or footer so it will be ignored
  warn("""Cannot parse header or footer so it will be ignored""")
/opt/homebrew/Caskroom/miniforge/base/lib/python3.10/site-packages/openpyxl/worksheet/header_footer.py:48: UserWarning: Cannot parse header or footer so it will be ignored
  warn("""Cannot parse header or footer so it will be ignored""")

In [53]:
for df in df_list:
    display(df)

,Sale Date,Parcel ID,Seller,Buyer,LEGAL DESCRIPTION,Sale Price,Assessed Value,Assessor Location
0,NaT,NaN,NaN,NaN,KIMBALL,NaN,at time of sale,NaN
1,2020-10-01,530033429,Ka'Lani O'Shea,Sharon June Pickering,DOWD'S SECOND ADD. BLOCK - LOT 14 (CARD #14),100000.0,113040,Kimball
2,2020-10-01,530036932,Chico R Fernandez,Crystal Kisicki,LEAMINGS ADD. BLOCK 9 S. 39' OF THE W. 80' OF ...,38000.0,27545,Kimball
3,2020-10-06,530033488,Justin W & Jacqueline N Prather,Anthony & Linda Madrid,DOWD'S SECOND ADD. BLOCK - LOT 19,145000.0,156090,Kimball
4,2020-10-06,530039036,James & Donna Cederburg,Caleb Reuter,SOUTH PARK ADD. BLOCK 16 W. 110' OF LOT 8 & W....,47900.0,36120,Kimball
...,...,...,...,...,...,...,...,...
138,2021-09-28,530016818,Barbara K Michael,Carmen M Jackman,TRACT 200 FEET BY 300 FEET IN THE N 1/2 OF THE...,225000.0,156655,Rural Resi
139,2022-04-11,530015951,Sammie M & Lovina Gingerich,Sammie & Talia L Gingerich,23.540 ACRES IN SE 1/4 S. OF UPRR 29-15-54,167000.0,190030,Rural Resi
140,2022-04-28,530020041,Michael A & Clara Sue Salazar,Matthew & Crystal Brown,TAX LOT 14 MORGAN'S SUBDIVISION IN E 1/2 OF SW...,305000.0,150090,Rural Resi
141,2022-05-11,530151785,Jean A Mueller-Yanaga,Daniel Glasgow,TRACT IN SE 1/4 AND E 1/2 NE 1/4 SW 1/4 33-15-55,190000.0,96960,Rural Resi
142,2022-07-07,530023288,Central Properties,"Adair Holdings, LLC",9.883 ACRE TRACT IN N 1/2 N 1/2 6-16-53,126185.0,126185,Rural Resi

,Sale Date,Parcel ID,Seller,Buyer,LEGAL DESCRIPTION,Sale Price,Assessed Value,Assessor Location
0,NaT,NaN,NaN,NaN,KIMBALL,NaN,at time of sale,NaN
1,2019-10-03,530042460,Kathleen P & Ricky L Chapman,Paul Richard & Rebecca Ellen Burris,SUNNYVIEW HEIGHTS ADDITION BLOCK 11 LOT 4,92500.0,71505,Kimball
2,2019-10-17,530033399,Tammy Adair,Doris F Burton,DOWD'S SECOND ADDITION BLOCK - LOT 10 AND SW 2...,147000.0,125245,Kimball
3,2019-11-06,530036754,Howard R & Shirley J Hoberg,David W & Debra A Gibson,LEAMINGS ADD BLOCK 7 LOT 6 AND THE N 1/2 OF LOT 7,89500.0,76555,Kimball
4,2019-11-07,530035448,Dan J & Cindy L Dean,Ryan M & Tiffany K Johnson,HUFF'S SECOND ADDITION BLOCK 1 S 5' OF LOT 1 A...,170000.0,175775,Kimball
...,...,...,...,...,...,...,...,...
170,2021-03-05,530010445,Daniel B Arnold,Timothy Wayne & Dixie Lee Smith,6-14-55 PART OF S1/2S1/2 6-14-55,330000.0,215195,Rural Resi
171,2021-03-25,530024640,Kathleen Atkins Trustee,Ryan Lukassen & Elyse Schlake,25-16-54 A TRACT IN THE N/2NE/4 25-16-54,265000.0,161020,Rural Resi
172,2021-05-03,530005069,Garland & Megan Hamilton,Sara Silvanage,6.502 ACRE TRACT IN NE1/4NE1/4 26-13-55,122000.0,103510,Rural Resi
173,2021-08-05,530010518,Michael T & Renee A Geha,Adam Geha,1.907 A. IN SE CORNER OF SW 1/4 7-14-55,80000.0,74345,Rural Resi
174,2021-09-28,530016818,Barbara K Michael,Carmen M Jackman,TRACT 200 FEET BY 300 FEET IN THE N 1/2 OF THE...,225000.0,156655,Rural Resi

,Sale Date,Parcel ID,Seller,Buyer,LEGAL DESCRIPTION,Sale Price,Assessor Location
0,NaT,NaN,NaN,NaN,KIMBALL,NaN,NaN
1,2017-10-12,530038722,Carson R Sisk,Shelby L Widener,SOUTH PARK ADDITION BLOCK 13 LOT 9,88000.0,Kimball
2,2017-10-20,530034484,Donna L Luther,David J & Barbara A Nickel,HILLCREST FIRST ADDITION BLOCK 1 LOT 6,73500.0,Kimball
3,2017-10-26,530042738,Rhonda Green & Roger Seeman,Joshua & Bobbie J Ybarra,SUNNYVIEW HEIGHTS ADDITION BLOCK 13 S.6' OF LO...,75000.0,Kimball
4,2017-10-27,530035642,Chauncey & Stephanie Pedersen,Monica Cajero & Efrain Soto,KIMBALL HEIGHTS ADDITION - LOT 13,138000.0,Kimball
...,...,...,...,...,...,...,...
128,2018-12-07,530061201,Sam & Lovina Gingerich,Tracy & Sabine Kasten,1.82 ACRES IN N 1/2 NW 1/4 35-15-54,45000.0,Rural Resi
129,2018-12-19,530009099,Maury D & Diane B Horst,Larry & Denise Loose,20.07 ACRE TRACT IN NE 1/4 5-14-54,105000.0,Rural Resi
130,2019-03-22,530157749,David & Joanna Hottell,Liam Dunn,TRACT IN SE 1/4 OF SE 1/4 OF SW 1/W 22-13-53,125000.0,Rural Resi
131,2019-05-13,530029073,Robert Mueller,Richard R & Kelli L Patterson,LOT 1 PRAIRIE RIDGE ESTATE 17-15-55,249000.0,Rural Resi
132,2019-08-30,530017377,Darren L & Kelleigh Huff,Teresa Teppert,11.449 ACRES IN THE SE 1/4 OF THE SW 1/4 SOUTH...,157000.0,Rural Resi

,Sale Date,Parcel ID,Seller,Buyer,LEGAL DESCRIPTION,Sale Price,Assessor Location
0,2014-10-17,530041421,Robert & Denise Waite,Preston Walls,SOUTH PARK ADD. BLOCK 3 N 1/2 OF LOT 13 AND AL...,54500.0,Kimball
1,2014-10-29,530035642,Elizabeth Shandera,Chauncey & Stephanie Pedersen,KIMBALL HEIGHTS ADD. LOT 13,140000.0,Kimball
2,2014-11-14,530032732,Wilma Vencill,Michael Mowry,CLARKSON ADD. BLOCK 10 LOT 6 AND N. 25' OF LOT 7,57000.0,Kimball
3,2014-11-14,530042800,Krissy Petersen,Roy Hammond,SUNNYVIEW HEIGHTS ADD. BLOCK 13 LOT 14,49600.0,Kimball
4,2014-11-24,530047381,Dennis & Robin McIntosh,Marc & Elizabeth Taylor,ANTELOPEVILLE ADD. BLOCK 8 W 1/2 OF LOTS8 AND 9,102000.0,Kimball
5,2014-12-01,530036134,Debra Schadegg,Penny Blackman-Hobbs,LEAMINGS ADD. BLOCK 2 LOT 12,20000.0,Kimball
6,2014-12-19,530044404,Ryan & Theresa Wilson,Elvin & Lynette Helms,YANNAYON ADD. BLOCK 8 A STRIP 43' IN WEST E...,20000.0,Kimball
7,2014-12-19,530036029,Dorothy Christiansen,James Wessels,LEAMINGS ADD. BLOCK 1 LOT 8,34000.0,Kimball
8,2014-12-29,530033798,Charles E & M Joyce Shields,Marcelino Calderon,FAIRVIEW ADD. BLOCK 4 LOTS 21-22-23 AND 24,20000.0,Kimball
9,2015-01-06,530042673,Kathy Brules,Marcelino & Dulce Calderon,SUNNYVIEW HEIGHTS ADD. BLOCK 13 LOT 3,41900.0,Kimball
10,2015-01-08,530037157,Randee Hottell,Michael Webb,LEAMINGS ADD. BLOCK 12 LOT 6,38500.0,Kimball
11,2015-01-09,530042851,Robert Baker,Joseph & Sharlet Morgan,SUNNYVIEW HEIGHTS ADD. BLOCK 14 LOT 5,38000.0,Kimball
12,2015-01-09,530044005,Robert Baker,Joseph & Sharlet Morgan,FREDERICK ADD. BLOCK 3 LOT 2,42000.0,Kimball
13,2015-02-02,530032341,Carmen Freeman,Gerald & Lana Anderson,CLARKSON ADD. BLOCK 7 LOT 2,45000.0,Kimball
14,2015-02-11,530036916,Robert & Gina Lopez,Max & Caitlin Williams,LEAMINGS ADD. BLOCK 9 LOT 4,67000.0,Kimball
15,2015-02-26,530032961,Jim & Charlotta Young,Andrew Brown,DOWD'S FIRST ADD. BLOCK 1 LOT 2,74500.0,Kimball
16,2015-03-15,530032465,Norma Stolz,Albert & Cynthia Johnson,CLARKSON ADD. BLOCK 7 E 1/2 OF LOTS 14-15 ...,63000.0,Kimball
17,2015-03-27,530041162,Scott & Kim Milewski,EDZ Property Investments LLC,SOUTH PARK ADD. BLOCK 1 LOT 9,67000.0,Kimball
18,2015-03-30,530067730,Troy & Bob Unzicker,Marshall & Kim Lewis,KINGSWOOD 2ND ADDITION BLOCK 1 LOTS 7 & 8,129000.0,Kimball
19,2015-04-10,530041197,Scott & Kim Milewski,Cody Markham,SOUTH PARK ADD. BLOCK 1 LOT 11,65000.0,Kimball
20,2015-04-22,530042053,Points West Community Bank,James & Donna Cederburg,SOUTH PARK ADD. BLOCK 10 LOT 3,20111.0,Kimball
21,2015-05-01,530032767,Shawn Becker,Marvin & Sandra Tabor,CLARKSON ADD. BLOCK 11 LOT 2,30000.0,Kimball
22,2015-05-07,530033593,Josephine Vernon,Dustin Erikson,EAST MANOR FIRST ADD. BLOCK 1 LOT 7,30000.0,Kimball
23,2015-05-21,530067722,David & Lisa Schohl,Mary Price,KINGSWOOD 2ND ADDITION BLOCK 1 LOT 6,162000.0,Kimball
24,2015-06-08,530036088,June Nielsen,John Robert & Rut Noemi Miller,LEAMINGS ADD. BLOCK 2 LOT 6,39000.0,Kimball
25,2015-06-12,530034581,Gerald & Lana Anderson,Zachary & Merissa Donnan,HILLCREST THIRD ADD. BLOCK 1 LOT 3,105000.0,Kimball
26,2015-07-17,530040115,Kara Dike,Dennis & Grayce Keller,SUNNYVIEW HEIGHTS ADD. BLOCK 9 LOT 1,82000.0,Kimball
27,2015-07-27,530035871,William Thomas,Matthew Bright,KINGSWOOD FIRST ADD. LOT 4,132000.0,Kimball
28,2015-07-30,530033488,Robert & Carol Pinkerton,Justin & Jacqueline Prather,DOWD'S SECOND ADD. BLOCK - LOT 19,150000.0,Kimball
29,2015-07-31,530034611,Lydia Hamilton,Luke & Lindsey Maas,HILLCREST THIRD ADD. BLOCK 1 LOT 5,95000.0,Kimball
30,2015-08-28,530040468,Gerald & Lana Anderson,Patrick Connelly,ORIGINAL KIMBALL ADD. BLOCK 18 LOTS 1 AND 2,32000.0,Kimball
31,2015-09-15,530031981,Kyle & Laura Johnson,Gerald & Lana Anderson,CLARKSON ADD. BLOCK 2 LOT 12,66000.0,Kimball
32,2015-09-25,530036703,Margaret Case,Patrick Connelly,LEAMINGS ADD. BLOCK 7 LOT 1,18000.0,Kimball
33,2015-10-19,530035847,Donald Thompson,Carolyn & Jennette Wood,KINGSWOOD FIRST ADD. LOT 1,62000.0,Kimball
34,2015-10-26,530045036,William Loring,Aleta Lewis,BURG'S ADD. BLOCK 2 ALL OF SUBLOT 1 OF LOTS 1...,30000.0,Kimball
35,2015-10-27,530033003,William & Winifred Petersen,Matthew & Rachel Merryfield,DOWD'S FIRST ADD. BLOCK 2 LOT 1,87500.0,Kimball
36,2015-11-12,530017318,James & Charlotta Young,Jose & Fatima Lozoya,PART OF THE SW 1/4 SOUTH OF THE UPRR 28-15-55,95000.0,Kimball
37,2015-11-27,530033798,Marcelino Calderon,Daniel & Sherry Acheson,FAIRVIEW ADD. BLOCK 4 LOTS 21-22-23 AND 24,30000.0,Kimball
38,2015-11-30,530033348,Max Williams,Casey & Katie Madden,DOWD'S SECOND ADD. BLOCK - LOT 5,108500.0,Kimball
39,2015-12-07,530044390,Jarrod & Tara Schnell,Sheldon & Terry Padelio,YANNAYON ADD. BLOCK 8 LOTS 15 AND 16 EXC. A...,92000.0,Kimball
40,2015-12-18,530033364,Sandra Lemaster,Tyler Olson,DOWD'S SECOND ADD. BLOCK - LOT 7,110000.0,Kimball
41,2015-12-31,530044293,Jeremy & Kerri Kerr,Marilyn Baker & Amy Sapp,YANNAYON ADD. BLOCK 8 LOT 4,101000.0,Kimball
42,2016-01-08,530035928,Dennis Baack Successor Trustee,Cory Shaw,KINGSWOOD FIRST ADD. LOT 7,92500.0,Kimball
43,2016-01-29,530045257,Marshall & Paula Hopkins,Ty Gibson,BURG'S ADD. BLOCK 4 LOT 5,55000.0,Kimball
44,2016-02-03,530032139,Elmer Bogert,Allen & Lindsey Chavez,CLARKSON ADD. BLOCK 5 S 1/2 OF LOT 2 ANDALL LOT 3,50000.0,Kimball
45,2016-02-11,530040220,Steven Cleveland,Lincoln & Kelsey Brown,ORIGINAL KIMBALL ADD. BLOCK 10 LOTS 8 AND 9 ...,24000.0,Kimball
46,2016-03-04,530035480,Helen Henson,Chad Wise,HUFF'S SECOND ADD. BLOCK 2 S. 43.2' OF LOT 1 ...,130000.0,Kimball
47,2016-03-17,530043106,Donald & Joyce Maxted,Richard & Brenda Baliman,TRITT ADD. BLOCK 1 LOT 8,128900.0,Kimball
48,2016-03-18,530018993,Richard & Brenda Baliman,Michael & Jennifer Coleman,A TRACT 100' X 140' SOUTH OF BLK 17 SOUTH ...,125000.0,Kimball
49,2016-04-08,530018500,Travis Terrell,Dawn Maier,A TRACT 199.36 FEET BY 210.5 FEET LOT 1 HULL'S...,95000.0,Kimball
50,2016-04-08,530042134,Kristine Carr,Elizabeth Taylor-Herzberger,SOUTH PARK ADD. BLOCK 10 N 1/3 OF LOT 13AND AL...,35000.0,Kimball
51,2016-04-15,530038145,Carl & Elizabeth Bateman,Robert & Gina Lopez,LOCKWOOD'S ADD. BLOCK 2 LOTS 13 AND 14,51000.0,Kimball
52,2016-05-03,530036657,Ryan Haas,David & Tracie Gamblin,LEAMINGS ADD. BLOCK 6 LOTS 9 AND 10,127000.0,Kimball
53,2016-05-26,530042991,Michael & Andrea Bemis,Amanda Lusche,SUNNYVIEW HEIGHTS ADD. BLOCK 15 LOT 4,83000.0,Kimball
54,2016-06-17,530033593,Dustin Erickson,Raymond Forehand,EAST MANOR FIRST ADD. BLOCK 1 LOT 7,35000.0,Kimball
55,2016-06-20,530040174,Emmanuel Gutierrez,Raymond Forehand,ORIGINAL KIMBALL ADD. BLOCK 10 LOTS 1 AND 2 ...,50000.0,Kimball
56,2016-06-23,530042657,Harold Kolene Edwards,James Wurnig,SUNNYVIEW HEIGHTS ADD. BLOCK 13 LOT 1,65000.0,Kimball
57,2016-06-29,530041847,Wilson Bowling,Joe & Christine Lewis,SOUTH PARK ADD. BLOCK 7 LOT 7,49000.0,Kimball
58,2016-06-29,530040093,Jean & Charles Kasson,Charlotte Weigel,SUNNYVIEW HEIGHTS ADD. BLOCK 8 LOT 11,58500.0,Kimball
59,2016-08-12,530039818,Mildred King,Tyler & Anne White,SUNNYVIEW HEIGHTS ADD. BLOCK 6 LOT 4,64500.0,Kimball
60,2016-08-15,530033372,JMK Revocable Trust,John Freed,DOWD'S SECOND ADD. BLOCK - LOT 8,160000.0,Kimball
61,2016-08-25,530036940,Deborah Moehr,Daniel & Patricia Deines,LEAMINGS ADD. BLOCK 10 E.62.89' OF LOTS 1 AND 2,20000.0,Kimball
62,2016-08-26,530042185,Leonard Michal,Richard Brookman,SOUTH PARK ADD. BLOCK 11 S 1/2 OF LOT 6 AND AL...,22500.0,Kimball
63,2016-08-31,530035316,Marrian Hennings,Z & S Construction Co,HILLCREST SIXTH ADD. BLOCK 2 LOT 3,80000.0,Kimball
64,2016-09-02,530039400,Daniel & Shirley Kinnison,Nate & Heather Entingh & Paula Weiss,SOUTH PARK ADD. BLOCK 21 E. 70' OF THAT PART O...,85000.0,Kimball
65,2016-09-06,530043467,Mary Moehr,Robert & Jacqueline Hill,YANNAYON ADD. BLOCK 3 LOTS 3 AND 4,36000.0,Kimball
66,2016-09-21,530035863,John & Maureen Trout,Elizabeth Shandera,KINGSWOOD FIRST ADD. LOT 3,125000.0,Kimball
67,2016-09-27,530036614,Gloria Barkley,Val Deane & Kathleen Snyder,LEAMINGS ADD. BLOCK 6 S. 40' OF LOT 3 AND TH...,38000.0,Kimball
68,2016-09-29,530033313,Anne Anderson,Matthew & Stephanie Shoup,DOWD'S SECOND ADD. BLOCK - LOT 3,85000.0,Kimball
69,2016-09-30,530031698,Wade Kiefer,Carl Stander,ALDENS ADD. BLOCK 1 N. 94' OF LOT 2,110000.0,Kimball
70,NaT,NaN,NaN,NaN,NaN,NaN,NaN
71,2015-04-15,530050765,Nathan Juhl,"John, Jaclyn, Chad & Julia Miller",HORRUM'S FIRST ADD. BLOCK 17 LOT 7 AND THE S ...,38000.0,Dix
72,2015-07-22,530050897,Marie Cashion,Harold & Gail Dunkle,HORRUM'S FIRST ADD. BLOCK 19 LOTS 13 AND14,55000.0,Dix
73,NaT,NaN,NaN,NaN,NaN,NaN,NaN
74,2014-11-26,530049260,Robert & Marie Adams,Deann Sweeter,WOOLDRIDGE ADD. BLOCK 1 LOTS 7 AND 8,76000.0,Bushnell
75,2015-03-03,530047446,Patricia Clason,Jay Latta,BUSHNELL VILLAGE ADD BLOCK 1 S. 25 FEET OF LOT...,29000.0,Bushnell
76,2015-06-01,530047721,Susan Rose,Joseph & Sharlet Morgan,BUSHNELL VILLAGE ADD. BLOCK 4 LOTS 18-19AND 20,25000.0,Bushnell
77,2016-09-29,530049228,Peter & Annelies Cunis,John & Venita Zimmerman,THOMAS ADD. BLOCK 6 LOTS 7 AND 8,72500.0,Bushnell
78,NaT,NaN,NaN,NaN,NaN,NaN,NaN
79,2014-11-06,530157938,William Spires,Andrew Knicely,3.99 A.TRACT IN SE1/4 28-15-56,80000.0,Rural Resi
80,2015-02-24,530031094,Nationstar Mortgage LLC,James & Karla Jenkins,TRACT S. OF UPRR IN SE 1/4 26-15-56,118000.0,Rural Resi
81,2015-02-27,530028050,Laurie & Mark Bennett,Whiting Oil & Gas Corp,63.398 A. TRACT IN SE CORNER 10-16-58,100000.0,Rural Resi
82,2015-07-02,530019191,Marjorie Shirk,David & Michelle Henker,LOT 2R DEBOODT SUBDIVISION (N1/2NW1/4) 33-15-55,63000.0,Rural Resi
83,2015-09-04,530007347,Dolores Harms Trustee,Carl Butler,TRACT IN E1/2 NE 1/4 14-13-58,40000.0,Rural Resi
84,2015-09-30,530160227,Kyle & Laura Johnson,Jay & Ashley Thurin,PART OF NE1/4SE1/4 2-15-55,220000.0,Rural Resi
85,2015-10-07,530153150,Cheema Investments,Ryan Burback & Stacy Garrett,1.498 A. TRACT IN NW 1/4 17-15-55,70000.0,Rural Resi
86,2015-11-05,530016818,Stanley & Beverly Pearson,Barbara Michael,TRACT 200 FEET BY 300 FEET IN THE N 1/2 OF THE...,175750.0,Rural Resi
87,2015-11-20,530151659,Lawrence & Nicole Snyder,Robert & Fawney Vincent,4.954A. TRACT IN SW1/4 30-15-56,123000.0,Rural Resi
88,2016-01-25,530028050,Whiting Oil & Gas Corp,Austin Garner,63.398 A. TRACT IN SE CORNER 10-16-58,95000.0,Rural Resi
89,2016-03-06,530029146,Daniel & Misty Curtis,Natalie & Owen Elder,LOTS 6 & 7 LESS TRACT PRAIRIE RIDGE ESTATE...,185000.0,Rural Resi
90,2016-07-25,530028522,David & Martha Cannon,Paul & Linda Piatz,19.854 ACRE TRACT IN 12-16-59,173000.0,Rural Resi

,Sale Date,Parcel ID,Seller,Buyer,LEGAL DESCRIPTION,Sale Price,Assessor Location
0,2015-10-19,530035847,Donald Thompson,Carolyn & Jennette Wood,KINGSWOOD FIRST ADD. LOT 1,62000.0,Kimball
1,2015-10-26,530045036,William Loring,Aleta Lewis,BURG'S ADD. BLOCK 2 ALL OF SUBLOT 1 OF LOTS 1...,30000.0,Kimball
2,2015-10-27,530033003,William & Winifred Petersen,Matthew & Rachel Merryfield,DOWD'S FIRST ADD. BLOCK 2 LOT 1,87500.0,Kimball
3,2015-11-12,530017318,James & Charlotta Young,Jose & Fatima Lozoya,PART OF THE SW 1/4 SOUTH OF THE UPRR 28-15-55,95000.0,Kimball
4,2015-11-27,530033798,Marcelino Calderon,Daniel & Sherry Acheson,FAIRVIEW ADD. BLOCK 4 LOTS 21-22-23 AND 24,30000.0,Kimball
...,...,...,...,...,...,...,...
116,2017-08-25,530010445,Lyle & Shonna Yung,Daniel & Mercedes Arnold,PART OF S 1/2 S 1/2 6-14-55 30.012 ACRES,235000.0,Rural Resi
117,2017-09-14,530151659,Robert & Fawney Vincent,Christine & Eddie Sharkey,4.954 ACRE TRACT IN SW 1/4 30-15-56,135000.0,Rural Resi
118,NaT,NaN,NaN,NaN,NaN,NaN,NaN
119,NaT,NaN,NaN,NaN,NaN,NaN,NaN
120,NaT,NaN,,NaN,NaN,NaN,NaN

,Sale Date,Parcel ID,Seller,Buyer,LEGAL DESCRIPTION,Sale Price,Assessor Location
0,2016-10-13,530045583,James Buckley,Scott Christensen,BURGS ADD. BLOCK 6 LOT 8,37000.0,Kimball
1,2016-10-17,530041286,Charles & Carolyn Carlson,Richard & Gloria Brookman,SOUTH PARK ADD. BLOCK 2 ALL LOT 8 AND S1/8 OF ...,150000.0,Kimball
2,2016-10-20,530035448,James Prince & Nancy Garrett,Patricia Biesecker & Deanna Bleyle,HUFFS SECOND ADD. BLOCK 1 S. 5' OF LOT 1 AND A...,120000.0,Kimball
3,2016-10-24,530032546,Claire Tritt,Ricky & Julia Gehrig,CLARKSON ADD. BLOCK 8 S. 20' OF LOT 7 AND ALL ...,83000.0,Kimball
4,2016-11-05,530045273,Jennifer Dillinger,Rachel Rowe,BURG'S ADD. BLOCK 4 ALL LOT 7 AND N 15' OF LOT 8,30000.0,Kimball
...,...,...,...,...,...,...,...
137,2018-06-15,530020696,Michael H & Karen M Isley,James N Columbia,A TRACT IN SE 1/4 28-15-56,165000.0,Rural Resi
138,2018-07-06,530031094,Karla J Jenkins,Marvin & Sandra Tabor,TRACT S OF UPRR IN SE 1/4 26-15-56,130000.0,Rural Resi
139,2018-07-18,530151470,Jared C & Melissa L Reich,Karla Jenkins,29.823 A TRACT IN NE 1/4 18-16-55,217500.0,Rural Resi
140,2018-08-01,530025779,Jeanne Anderson,Cheryl Delaplane,TRACT IN WEST PART OF NW 1/4 32-16-55,67000.0,Rural Resi
141,2018-09-14,530026937,Mary Ann Felkins,John M & Alicia I Buchart,7.015 ACRES IN THE NE 1/4 OF THE NE 1/4 OF TH ...,180000.0,Rural Resi

,Sale Date,Parcel ID,Seller,Buyer,LEGAL DESCRIPTION,Sale Price,Assessed Value,Assessor Location
0,NaT,NaN,NaN,NaN,KIMBALL,NaN,at time of sale,NaN
1,2018-10-16,530040824,Larry L & JoAnne M Fleagle,Christopher J Woods,ORIGINAL KIMBALL ADDITION BLOCK 21 LOTS 7 THRU 12,62000.0,40020,Kimball
2,2018-10-18,530033429,Melvin D & Sarah E Bouse,Ka'Lani O'Shea,DOWD'S SECOND ADDITION BLOCK - LOT 14,80000.0,102980,Kimball
3,2018-10-23,530036703,Patrick H Connelly,Mary Ann Felkins,LEAMINGS ADDITION BLOCK 7 LOT 1,40000.0,18875,Kimball
4,2018-10-26,530043416,Lisa A Rockhold,"Virginia K, Troy L & Julie E Davis",YANNAYON ADDITION BLOCK 2 LOT 20,75500.0,67475,Kimball
...,...,...,...,...,...,...,...,...
133,2020-02-15,530010518,Trevor L Chrystal,Michael T & Renee A Geha,1.907 ACRES IN SE CORNER OF SW 1/4 7-14-55,80000.0,74345,Rural Resi
134,2020-03-13,530021609,Scott E & Susan L Lockwood,Dalton & Ainsley Lockwood,23.147 ACRES IN 36-15-57,490000.0,300120,Rural Resi
135,2020-03-14,530029103,Douglas J & Marvel L Linthicum,Trevor L & Nicole M Anderson,LOT 3 PRAIRIE RIDGE ESTATE 17-15-55,255000.0,206040,Rural Resi
136,2020-04-01,530018365,Walter L Wann,Robert D Dunkin III,TRACT IN NE 1/4 NW 1/4 31-15-55,70000.0,87090,Rural Resi
137,2020-07-24,530050439,Dwayne A & Jonita M Groves,Bradley Ray & Nicole Lynn Hottell,12.415 ACRE TRACT IN NE 1/4 29-15-55,135000.0,197340,Rural Resi

In [54]:
cleaned_dfs = []
for df in df_list:
    nas = df.loc[df.isna().any(axis=1), :]
    #display(nas)
    cleaned_dfs.append(df.loc[~df.isna().any(axis=1),:])
    display(df.loc[~df.isna().any(axis=1),:])

,Sale Date,Parcel ID,Seller,Buyer,LEGAL DESCRIPTION,Sale Price,Assessed Value,Assessor Location
1,2020-10-01,530033429,Ka'Lani O'Shea,Sharon June Pickering,DOWD'S SECOND ADD. BLOCK - LOT 14 (CARD #14),100000.0,113040,Kimball
2,2020-10-01,530036932,Chico R Fernandez,Crystal Kisicki,LEAMINGS ADD. BLOCK 9 S. 39' OF THE W. 80' OF ...,38000.0,27545,Kimball
3,2020-10-06,530033488,Justin W & Jacqueline N Prather,Anthony & Linda Madrid,DOWD'S SECOND ADD. BLOCK - LOT 19,145000.0,156090,Kimball
4,2020-10-06,530039036,James & Donna Cederburg,Caleb Reuter,SOUTH PARK ADD. BLOCK 16 W. 110' OF LOT 8 & W....,47900.0,36120,Kimball
5,2020-10-20,530042959,Carol L Meyer,Danny E Yung,SUNNYVIEW HEIGHTS ADD. BLOCK 14 N. 5' OF LOT 1...,71100.0,82945,Kimball
...,...,...,...,...,...,...,...,...
138,2021-09-28,530016818,Barbara K Michael,Carmen M Jackman,TRACT 200 FEET BY 300 FEET IN THE N 1/2 OF THE...,225000.0,156655,Rural Resi
139,2022-04-11,530015951,Sammie M & Lovina Gingerich,Sammie & Talia L Gingerich,23.540 ACRES IN SE 1/4 S. OF UPRR 29-15-54,167000.0,190030,Rural Resi
140,2022-04-28,530020041,Michael A & Clara Sue Salazar,Matthew & Crystal Brown,TAX LOT 14 MORGAN'S SUBDIVISION IN E 1/2 OF SW...,305000.0,150090,Rural Resi
141,2022-05-11,530151785,Jean A Mueller-Yanaga,Daniel Glasgow,TRACT IN SE 1/4 AND E 1/2 NE 1/4 SW 1/4 33-15-55,190000.0,96960,Rural Resi
142,2022-07-07,530023288,Central Properties,"Adair Holdings, LLC",9.883 ACRE TRACT IN N 1/2 N 1/2 6-16-53,126185.0,126185,Rural Resi

,Sale Date,Parcel ID,Seller,Buyer,LEGAL DESCRIPTION,Sale Price,Assessed Value,Assessor Location
1,2019-10-03,530042460,Kathleen P & Ricky L Chapman,Paul Richard & Rebecca Ellen Burris,SUNNYVIEW HEIGHTS ADDITION BLOCK 11 LOT 4,92500.0,71505,Kimball
2,2019-10-17,530033399,Tammy Adair,Doris F Burton,DOWD'S SECOND ADDITION BLOCK - LOT 10 AND SW 2...,147000.0,125245,Kimball
3,2019-11-06,530036754,Howard R & Shirley J Hoberg,David W & Debra A Gibson,LEAMINGS ADD BLOCK 7 LOT 6 AND THE N 1/2 OF LOT 7,89500.0,76555,Kimball
4,2019-11-07,530035448,Dan J & Cindy L Dean,Ryan M & Tiffany K Johnson,HUFF'S SECOND ADDITION BLOCK 1 S 5' OF LOT 1 A...,170000.0,175775,Kimball
5,2019-11-11,530038803,Diana K Fiehtner,Frank & Norma Stauffer,SOUTH PARK ADDITION BLOCK 14 W 80' OF LOTS 1-3...,60000.0,53015,Kimball
...,...,...,...,...,...,...,...,...
170,2021-03-05,530010445,Daniel B Arnold,Timothy Wayne & Dixie Lee Smith,6-14-55 PART OF S1/2S1/2 6-14-55,330000.0,215195,Rural Resi
171,2021-03-25,530024640,Kathleen Atkins Trustee,Ryan Lukassen & Elyse Schlake,25-16-54 A TRACT IN THE N/2NE/4 25-16-54,265000.0,161020,Rural Resi
172,2021-05-03,530005069,Garland & Megan Hamilton,Sara Silvanage,6.502 ACRE TRACT IN NE1/4NE1/4 26-13-55,122000.0,103510,Rural Resi
173,2021-08-05,530010518,Michael T & Renee A Geha,Adam Geha,1.907 A. IN SE CORNER OF SW 1/4 7-14-55,80000.0,74345,Rural Resi
174,2021-09-28,530016818,Barbara K Michael,Carmen M Jackman,TRACT 200 FEET BY 300 FEET IN THE N 1/2 OF THE...,225000.0,156655,Rural Resi

,Sale Date,Parcel ID,Seller,Buyer,LEGAL DESCRIPTION,Sale Price,Assessor Location
1,2017-10-12,530038722,Carson R Sisk,Shelby L Widener,SOUTH PARK ADDITION BLOCK 13 LOT 9,88000.0,Kimball
2,2017-10-20,530034484,Donna L Luther,David J & Barbara A Nickel,HILLCREST FIRST ADDITION BLOCK 1 LOT 6,73500.0,Kimball
3,2017-10-26,530042738,Rhonda Green & Roger Seeman,Joshua & Bobbie J Ybarra,SUNNYVIEW HEIGHTS ADDITION BLOCK 13 S.6' OF LO...,75000.0,Kimball
4,2017-10-27,530035642,Chauncey & Stephanie Pedersen,Monica Cajero & Efrain Soto,KIMBALL HEIGHTS ADDITION - LOT 13,138000.0,Kimball
5,2017-10-27,530034735,Irene J Wallin,Bernardo & Mercedes Quinones,HILLCREST SECOND ADDITION BLOCK 2 LOT 4,55000.0,Kimball
...,...,...,...,...,...,...,...
128,2018-12-07,530061201,Sam & Lovina Gingerich,Tracy & Sabine Kasten,1.82 ACRES IN N 1/2 NW 1/4 35-15-54,45000.0,Rural Resi
129,2018-12-19,530009099,Maury D & Diane B Horst,Larry & Denise Loose,20.07 ACRE TRACT IN NE 1/4 5-14-54,105000.0,Rural Resi
130,2019-03-22,530157749,David & Joanna Hottell,Liam Dunn,TRACT IN SE 1/4 OF SE 1/4 OF SW 1/W 22-13-53,125000.0,Rural Resi
131,2019-05-13,530029073,Robert Mueller,Richard R & Kelli L Patterson,LOT 1 PRAIRIE RIDGE ESTATE 17-15-55,249000.0,Rural Resi
132,2019-08-30,530017377,Darren L & Kelleigh Huff,Teresa Teppert,11.449 ACRES IN THE SE 1/4 OF THE SW 1/4 SOUTH...,157000.0,Rural Resi

,Sale Date,Parcel ID,Seller,Buyer,LEGAL DESCRIPTION,Sale Price,Assessor Location
0,2014-10-17,530041421,Robert & Denise Waite,Preston Walls,SOUTH PARK ADD. BLOCK 3 N 1/2 OF LOT 13 AND AL...,54500.0,Kimball
1,2014-10-29,530035642,Elizabeth Shandera,Chauncey & Stephanie Pedersen,KIMBALL HEIGHTS ADD. LOT 13,140000.0,Kimball
2,2014-11-14,530032732,Wilma Vencill,Michael Mowry,CLARKSON ADD. BLOCK 10 LOT 6 AND N. 25' OF LOT 7,57000.0,Kimball
3,2014-11-14,530042800,Krissy Petersen,Roy Hammond,SUNNYVIEW HEIGHTS ADD. BLOCK 13 LOT 14,49600.0,Kimball
4,2014-11-24,530047381,Dennis & Robin McIntosh,Marc & Elizabeth Taylor,ANTELOPEVILLE ADD. BLOCK 8 W 1/2 OF LOTS8 AND 9,102000.0,Kimball
5,2014-12-01,530036134,Debra Schadegg,Penny Blackman-Hobbs,LEAMINGS ADD. BLOCK 2 LOT 12,20000.0,Kimball
6,2014-12-19,530044404,Ryan & Theresa Wilson,Elvin & Lynette Helms,YANNAYON ADD. BLOCK 8 A STRIP 43' IN WEST E...,20000.0,Kimball
7,2014-12-19,530036029,Dorothy Christiansen,James Wessels,LEAMINGS ADD. BLOCK 1 LOT 8,34000.0,Kimball
8,2014-12-29,530033798,Charles E & M Joyce Shields,Marcelino Calderon,FAIRVIEW ADD. BLOCK 4 LOTS 21-22-23 AND 24,20000.0,Kimball
9,2015-01-06,530042673,Kathy Brules,Marcelino & Dulce Calderon,SUNNYVIEW HEIGHTS ADD. BLOCK 13 LOT 3,41900.0,Kimball
10,2015-01-08,530037157,Randee Hottell,Michael Webb,LEAMINGS ADD. BLOCK 12 LOT 6,38500.0,Kimball
11,2015-01-09,530042851,Robert Baker,Joseph & Sharlet Morgan,SUNNYVIEW HEIGHTS ADD. BLOCK 14 LOT 5,38000.0,Kimball
12,2015-01-09,530044005,Robert Baker,Joseph & Sharlet Morgan,FREDERICK ADD. BLOCK 3 LOT 2,42000.0,Kimball
13,2015-02-02,530032341,Carmen Freeman,Gerald & Lana Anderson,CLARKSON ADD. BLOCK 7 LOT 2,45000.0,Kimball
14,2015-02-11,530036916,Robert & Gina Lopez,Max & Caitlin Williams,LEAMINGS ADD. BLOCK 9 LOT 4,67000.0,Kimball
15,2015-02-26,530032961,Jim & Charlotta Young,Andrew Brown,DOWD'S FIRST ADD. BLOCK 1 LOT 2,74500.0,Kimball
16,2015-03-15,530032465,Norma Stolz,Albert & Cynthia Johnson,CLARKSON ADD. BLOCK 7 E 1/2 OF LOTS 14-15 ...,63000.0,Kimball
17,2015-03-27,530041162,Scott & Kim Milewski,EDZ Property Investments LLC,SOUTH PARK ADD. BLOCK 1 LOT 9,67000.0,Kimball
18,2015-03-30,530067730,Troy & Bob Unzicker,Marshall & Kim Lewis,KINGSWOOD 2ND ADDITION BLOCK 1 LOTS 7 & 8,129000.0,Kimball
19,2015-04-10,530041197,Scott & Kim Milewski,Cody Markham,SOUTH PARK ADD. BLOCK 1 LOT 11,65000.0,Kimball
20,2015-04-22,530042053,Points West Community Bank,James & Donna Cederburg,SOUTH PARK ADD. BLOCK 10 LOT 3,20111.0,Kimball
21,2015-05-01,530032767,Shawn Becker,Marvin & Sandra Tabor,CLARKSON ADD. BLOCK 11 LOT 2,30000.0,Kimball
22,2015-05-07,530033593,Josephine Vernon,Dustin Erikson,EAST MANOR FIRST ADD. BLOCK 1 LOT 7,30000.0,Kimball
23,2015-05-21,530067722,David & Lisa Schohl,Mary Price,KINGSWOOD 2ND ADDITION BLOCK 1 LOT 6,162000.0,Kimball
24,2015-06-08,530036088,June Nielsen,John Robert & Rut Noemi Miller,LEAMINGS ADD. BLOCK 2 LOT 6,39000.0,Kimball
25,2015-06-12,530034581,Gerald & Lana Anderson,Zachary & Merissa Donnan,HILLCREST THIRD ADD. BLOCK 1 LOT 3,105000.0,Kimball
26,2015-07-17,530040115,Kara Dike,Dennis & Grayce Keller,SUNNYVIEW HEIGHTS ADD. BLOCK 9 LOT 1,82000.0,Kimball
27,2015-07-27,530035871,William Thomas,Matthew Bright,KINGSWOOD FIRST ADD. LOT 4,132000.0,Kimball
28,2015-07-30,530033488,Robert & Carol Pinkerton,Justin & Jacqueline Prather,DOWD'S SECOND ADD. BLOCK - LOT 19,150000.0,Kimball
29,2015-07-31,530034611,Lydia Hamilton,Luke & Lindsey Maas,HILLCREST THIRD ADD. BLOCK 1 LOT 5,95000.0,Kimball
30,2015-08-28,530040468,Gerald & Lana Anderson,Patrick Connelly,ORIGINAL KIMBALL ADD. BLOCK 18 LOTS 1 AND 2,32000.0,Kimball
31,2015-09-15,530031981,Kyle & Laura Johnson,Gerald & Lana Anderson,CLARKSON ADD. BLOCK 2 LOT 12,66000.0,Kimball
32,2015-09-25,530036703,Margaret Case,Patrick Connelly,LEAMINGS ADD. BLOCK 7 LOT 1,18000.0,Kimball
33,2015-10-19,530035847,Donald Thompson,Carolyn & Jennette Wood,KINGSWOOD FIRST ADD. LOT 1,62000.0,Kimball
34,2015-10-26,530045036,William Loring,Aleta Lewis,BURG'S ADD. BLOCK 2 ALL OF SUBLOT 1 OF LOTS 1...,30000.0,Kimball
35,2015-10-27,530033003,William & Winifred Petersen,Matthew & Rachel Merryfield,DOWD'S FIRST ADD. BLOCK 2 LOT 1,87500.0,Kimball
36,2015-11-12,530017318,James & Charlotta Young,Jose & Fatima Lozoya,PART OF THE SW 1/4 SOUTH OF THE UPRR 28-15-55,95000.0,Kimball
37,2015-11-27,530033798,Marcelino Calderon,Daniel & Sherry Acheson,FAIRVIEW ADD. BLOCK 4 LOTS 21-22-23 AND 24,30000.0,Kimball
38,2015-11-30,530033348,Max Williams,Casey & Katie Madden,DOWD'S SECOND ADD. BLOCK - LOT 5,108500.0,Kimball
39,2015-12-07,530044390,Jarrod & Tara Schnell,Sheldon & Terry Padelio,YANNAYON ADD. BLOCK 8 LOTS 15 AND 16 EXC. A...,92000.0,Kimball
40,2015-12-18,530033364,Sandra Lemaster,Tyler Olson,DOWD'S SECOND ADD. BLOCK - LOT 7,110000.0,Kimball
41,2015-12-31,530044293,Jeremy & Kerri Kerr,Marilyn Baker & Amy Sapp,YANNAYON ADD. BLOCK 8 LOT 4,101000.0,Kimball
42,2016-01-08,530035928,Dennis Baack Successor Trustee,Cory Shaw,KINGSWOOD FIRST ADD. LOT 7,92500.0,Kimball
43,2016-01-29,530045257,Marshall & Paula Hopkins,Ty Gibson,BURG'S ADD. BLOCK 4 LOT 5,55000.0,Kimball
44,2016-02-03,530032139,Elmer Bogert,Allen & Lindsey Chavez,CLARKSON ADD. BLOCK 5 S 1/2 OF LOT 2 ANDALL LOT 3,50000.0,Kimball
45,2016-02-11,530040220,Steven Cleveland,Lincoln & Kelsey Brown,ORIGINAL KIMBALL ADD. BLOCK 10 LOTS 8 AND 9 ...,24000.0,Kimball
46,2016-03-04,530035480,Helen Henson,Chad Wise,HUFF'S SECOND ADD. BLOCK 2 S. 43.2' OF LOT 1 ...,130000.0,Kimball
47,2016-03-17,530043106,Donald & Joyce Maxted,Richard & Brenda Baliman,TRITT ADD. BLOCK 1 LOT 8,128900.0,Kimball
48,2016-03-18,530018993,Richard & Brenda Baliman,Michael & Jennifer Coleman,A TRACT 100' X 140' SOUTH OF BLK 17 SOUTH ...,125000.0,Kimball
49,2016-04-08,530018500,Travis Terrell,Dawn Maier,A TRACT 199.36 FEET BY 210.5 FEET LOT 1 HULL'S...,95000.0,Kimball
50,2016-04-08,530042134,Kristine Carr,Elizabeth Taylor-Herzberger,SOUTH PARK ADD. BLOCK 10 N 1/3 OF LOT 13AND AL...,35000.0,Kimball
51,2016-04-15,530038145,Carl & Elizabeth Bateman,Robert & Gina Lopez,LOCKWOOD'S ADD. BLOCK 2 LOTS 13 AND 14,51000.0,Kimball
52,2016-05-03,530036657,Ryan Haas,David & Tracie Gamblin,LEAMINGS ADD. BLOCK 6 LOTS 9 AND 10,127000.0,Kimball
53,2016-05-26,530042991,Michael & Andrea Bemis,Amanda Lusche,SUNNYVIEW HEIGHTS ADD. BLOCK 15 LOT 4,83000.0,Kimball
54,2016-06-17,530033593,Dustin Erickson,Raymond Forehand,EAST MANOR FIRST ADD. BLOCK 1 LOT 7,35000.0,Kimball
55,2016-06-20,530040174,Emmanuel Gutierrez,Raymond Forehand,ORIGINAL KIMBALL ADD. BLOCK 10 LOTS 1 AND 2 ...,50000.0,Kimball
56,2016-06-23,530042657,Harold Kolene Edwards,James Wurnig,SUNNYVIEW HEIGHTS ADD. BLOCK 13 LOT 1,65000.0,Kimball
57,2016-06-29,530041847,Wilson Bowling,Joe & Christine Lewis,SOUTH PARK ADD. BLOCK 7 LOT 7,49000.0,Kimball
58,2016-06-29,530040093,Jean & Charles Kasson,Charlotte Weigel,SUNNYVIEW HEIGHTS ADD. BLOCK 8 LOT 11,58500.0,Kimball
59,2016-08-12,530039818,Mildred King,Tyler & Anne White,SUNNYVIEW HEIGHTS ADD. BLOCK 6 LOT 4,64500.0,Kimball
60,2016-08-15,530033372,JMK Revocable Trust,John Freed,DOWD'S SECOND ADD. BLOCK - LOT 8,160000.0,Kimball
61,2016-08-25,530036940,Deborah Moehr,Daniel & Patricia Deines,LEAMINGS ADD. BLOCK 10 E.62.89' OF LOTS 1 AND 2,20000.0,Kimball
62,2016-08-26,530042185,Leonard Michal,Richard Brookman,SOUTH PARK ADD. BLOCK 11 S 1/2 OF LOT 6 AND AL...,22500.0,Kimball
63,2016-08-31,530035316,Marrian Hennings,Z & S Construction Co,HILLCREST SIXTH ADD. BLOCK 2 LOT 3,80000.0,Kimball
64,2016-09-02,530039400,Daniel & Shirley Kinnison,Nate & Heather Entingh & Paula Weiss,SOUTH PARK ADD. BLOCK 21 E. 70' OF THAT PART O...,85000.0,Kimball
65,2016-09-06,530043467,Mary Moehr,Robert & Jacqueline Hill,YANNAYON ADD. BLOCK 3 LOTS 3 AND 4,36000.0,Kimball
66,2016-09-21,530035863,John & Maureen Trout,Elizabeth Shandera,KINGSWOOD FIRST ADD. LOT 3,125000.0,Kimball
67,2016-09-27,530036614,Gloria Barkley,Val Deane & Kathleen Snyder,LEAMINGS ADD. BLOCK 6 S. 40' OF LOT 3 AND TH...,38000.0,Kimball
68,2016-09-29,530033313,Anne Anderson,Matthew & Stephanie Shoup,DOWD'S SECOND ADD. BLOCK - LOT 3,85000.0,Kimball
69,2016-09-30,530031698,Wade Kiefer,Carl Stander,ALDENS ADD. BLOCK 1 N. 94' OF LOT 2,110000.0,Kimball
71,2015-04-15,530050765,Nathan Juhl,"John, Jaclyn, Chad & Julia Miller",HORRUM'S FIRST ADD. BLOCK 17 LOT 7 AND THE S ...,38000.0,Dix
72,2015-07-22,530050897,Marie Cashion,Harold & Gail Dunkle,HORRUM'S FIRST ADD. BLOCK 19 LOTS 13 AND14,55000.0,Dix
74,2014-11-26,530049260,Robert & Marie Adams,Deann Sweeter,WOOLDRIDGE ADD. BLOCK 1 LOTS 7 AND 8,76000.0,Bushnell
75,2015-03-03,530047446,Patricia Clason,Jay Latta,BUSHNELL VILLAGE ADD BLOCK 1 S. 25 FEET OF LOT...,29000.0,Bushnell
76,2015-06-01,530047721,Susan Rose,Joseph & Sharlet Morgan,BUSHNELL VILLAGE ADD. BLOCK 4 LOTS 18-19AND 20,25000.0,Bushnell
77,2016-09-29,530049228,Peter & Annelies Cunis,John & Venita Zimmerman,THOMAS ADD. BLOCK 6 LOTS 7 AND 8,72500.0,Bushnell
79,2014-11-06,530157938,William Spires,Andrew Knicely,3.99 A.TRACT IN SE1/4 28-15-56,80000.0,Rural Resi
80,2015-02-24,530031094,Nationstar Mortgage LLC,James & Karla Jenkins,TRACT S. OF UPRR IN SE 1/4 26-15-56,118000.0,Rural Resi
81,2015-02-27,530028050,Laurie & Mark Bennett,Whiting Oil & Gas Corp,63.398 A. TRACT IN SE CORNER 10-16-58,100000.0,Rural Resi
82,2015-07-02,530019191,Marjorie Shirk,David & Michelle Henker,LOT 2R DEBOODT SUBDIVISION (N1/2NW1/4) 33-15-55,63000.0,Rural Resi
83,2015-09-04,530007347,Dolores Harms Trustee,Carl Butler,TRACT IN E1/2 NE 1/4 14-13-58,40000.0,Rural Resi
84,2015-09-30,530160227,Kyle & Laura Johnson,Jay & Ashley Thurin,PART OF NE1/4SE1/4 2-15-55,220000.0,Rural Resi
85,2015-10-07,530153150,Cheema Investments,Ryan Burback & Stacy Garrett,1.498 A. TRACT IN NW 1/4 17-15-55,70000.0,Rural Resi
86,2015-11-05,530016818,Stanley & Beverly Pearson,Barbara Michael,TRACT 200 FEET BY 300 FEET IN THE N 1/2 OF THE...,175750.0,Rural Resi
87,2015-11-20,530151659,Lawrence & Nicole Snyder,Robert & Fawney Vincent,4.954A. TRACT IN SW1/4 30-15-56,123000.0,Rural Resi
88,2016-01-25,530028050,Whiting Oil & Gas Corp,Austin Garner,63.398 A. TRACT IN SE CORNER 10-16-58,95000.0,Rural Resi
89,2016-03-06,530029146,Daniel & Misty Curtis,Natalie & Owen Elder,LOTS 6 & 7 LESS TRACT PRAIRIE RIDGE ESTATE...,185000.0,Rural Resi
90,2016-07-25,530028522,David & Martha Cannon,Paul & Linda Piatz,19.854 ACRE TRACT IN 12-16-59,173000.0,Rural Resi

,Sale Date,Parcel ID,Seller,Buyer,LEGAL DESCRIPTION,Sale Price,Assessor Location
0,2015-10-19,530035847,Donald Thompson,Carolyn & Jennette Wood,KINGSWOOD FIRST ADD. LOT 1,62000.0,Kimball
1,2015-10-26,530045036,William Loring,Aleta Lewis,BURG'S ADD. BLOCK 2 ALL OF SUBLOT 1 OF LOTS 1...,30000.0,Kimball
2,2015-10-27,530033003,William & Winifred Petersen,Matthew & Rachel Merryfield,DOWD'S FIRST ADD. BLOCK 2 LOT 1,87500.0,Kimball
3,2015-11-12,530017318,James & Charlotta Young,Jose & Fatima Lozoya,PART OF THE SW 1/4 SOUTH OF THE UPRR 28-15-55,95000.0,Kimball
4,2015-11-27,530033798,Marcelino Calderon,Daniel & Sherry Acheson,FAIRVIEW ADD. BLOCK 4 LOTS 21-22-23 AND 24,30000.0,Kimball
...,...,...,...,...,...,...,...
113,2017-04-24,530009285,Monica & Magdaleno Cajero,Donald Weeks,TRACT IN E 1/2 NE 1/4 OF 10-14-54 (26.849 ACRES),135000.0,Rural Resi
114,2017-06-16,530020173,Kristi & Ronald Cortney,Toni & Edward Barnes,TAX LOT 8 PART OF SE 1/4 OF THE NW 1/4 & NE 1/...,150499.0,Rural Resi
115,2017-07-12,530020041,Jason Hottell,Robin Whitehead,TAX LOT 14 MORGANS SUBDIVISION IN E 1/2 OF SW ...,187000.0,Rural Resi
116,2017-08-25,530010445,Lyle & Shonna Yung,Daniel & Mercedes Arnold,PART OF S 1/2 S 1/2 6-14-55 30.012 ACRES,235000.0,Rural Resi
117,2017-09-14,530151659,Robert & Fawney Vincent,Christine & Eddie Sharkey,4.954 ACRE TRACT IN SW 1/4 30-15-56,135000.0,Rural Resi

,Sale Date,Parcel ID,Seller,Buyer,LEGAL DESCRIPTION,Sale Price,Assessor Location
0,2016-10-13,530045583,James Buckley,Scott Christensen,BURGS ADD. BLOCK 6 LOT 8,37000.0,Kimball
1,2016-10-17,530041286,Charles & Carolyn Carlson,Richard & Gloria Brookman,SOUTH PARK ADD. BLOCK 2 ALL LOT 8 AND S1/8 OF ...,150000.0,Kimball
2,2016-10-20,530035448,James Prince & Nancy Garrett,Patricia Biesecker & Deanna Bleyle,HUFFS SECOND ADD. BLOCK 1 S. 5' OF LOT 1 AND A...,120000.0,Kimball
3,2016-10-24,530032546,Claire Tritt,Ricky & Julia Gehrig,CLARKSON ADD. BLOCK 8 S. 20' OF LOT 7 AND ALL ...,83000.0,Kimball
4,2016-11-05,530045273,Jennifer Dillinger,Rachel Rowe,BURG'S ADD. BLOCK 4 ALL LOT 7 AND N 15' OF LOT 8,30000.0,Kimball
...,...,...,...,...,...,...,...
137,2018-06-15,530020696,Michael H & Karen M Isley,James N Columbia,A TRACT IN SE 1/4 28-15-56,165000.0,Rural Resi
138,2018-07-06,530031094,Karla J Jenkins,Marvin & Sandra Tabor,TRACT S OF UPRR IN SE 1/4 26-15-56,130000.0,Rural Resi
139,2018-07-18,530151470,Jared C & Melissa L Reich,Karla Jenkins,29.823 A TRACT IN NE 1/4 18-16-55,217500.0,Rural Resi
140,2018-08-01,530025779,Jeanne Anderson,Cheryl Delaplane,TRACT IN WEST PART OF NW 1/4 32-16-55,67000.0,Rural Resi
141,2018-09-14,530026937,Mary Ann Felkins,John M & Alicia I Buchart,7.015 ACRES IN THE NE 1/4 OF THE NE 1/4 OF TH ...,180000.0,Rural Resi

,Sale Date,Parcel ID,Seller,Buyer,LEGAL DESCRIPTION,Sale Price,Assessed Value,Assessor Location
1,2018-10-16,530040824,Larry L & JoAnne M Fleagle,Christopher J Woods,ORIGINAL KIMBALL ADDITION BLOCK 21 LOTS 7 THRU 12,62000.0,40020,Kimball
2,2018-10-18,530033429,Melvin D & Sarah E Bouse,Ka'Lani O'Shea,DOWD'S SECOND ADDITION BLOCK - LOT 14,80000.0,102980,Kimball
3,2018-10-23,530036703,Patrick H Connelly,Mary Ann Felkins,LEAMINGS ADDITION BLOCK 7 LOT 1,40000.0,18875,Kimball
4,2018-10-26,530043416,Lisa A Rockhold,"Virginia K, Troy L & Julie E Davis",YANNAYON ADDITION BLOCK 2 LOT 20,75500.0,67475,Kimball
5,2018-12-14,530035626,Kenneth H & Cynthia Stone Hunter,Ty M & Jessica S Gibson,KIMBALL HEIGHTS ADDITION N. 23' OF LOT 9 AND A...,189000.0,171090,Kimball
...,...,...,...,...,...,...,...,...
133,2020-02-15,530010518,Trevor L Chrystal,Michael T & Renee A Geha,1.907 ACRES IN SE CORNER OF SW 1/4 7-14-55,80000.0,74345,Rural Resi
134,2020-03-13,530021609,Scott E & Susan L Lockwood,Dalton & Ainsley Lockwood,23.147 ACRES IN 36-15-57,490000.0,300120,Rural Resi
135,2020-03-14,530029103,Douglas J & Marvel L Linthicum,Trevor L & Nicole M Anderson,LOT 3 PRAIRIE RIDGE ESTATE 17-15-55,255000.0,206040,Rural Resi
136,2020-04-01,530018365,Walter L Wann,Robert D Dunkin III,TRACT IN NE 1/4 NW 1/4 31-15-55,70000.0,87090,Rural Resi
137,2020-07-24,530050439,Dwayne A & Jonita M Groves,Bradley Ray & Nicole Lynn Hottell,12.415 ACRE TRACT IN NE 1/4 29-15-55,135000.0,197340,Rural Resi

In [55]:
for df in cleaned_dfs:
    display(df)

,Sale Date,Parcel ID,Seller,Buyer,LEGAL DESCRIPTION,Sale Price,Assessed Value,Assessor Location
1,2020-10-01,530033429,Ka'Lani O'Shea,Sharon June Pickering,DOWD'S SECOND ADD. BLOCK - LOT 14 (CARD #14),100000.0,113040,Kimball
2,2020-10-01,530036932,Chico R Fernandez,Crystal Kisicki,LEAMINGS ADD. BLOCK 9 S. 39' OF THE W. 80' OF ...,38000.0,27545,Kimball
3,2020-10-06,530033488,Justin W & Jacqueline N Prather,Anthony & Linda Madrid,DOWD'S SECOND ADD. BLOCK - LOT 19,145000.0,156090,Kimball
4,2020-10-06,530039036,James & Donna Cederburg,Caleb Reuter,SOUTH PARK ADD. BLOCK 16 W. 110' OF LOT 8 & W....,47900.0,36120,Kimball
5,2020-10-20,530042959,Carol L Meyer,Danny E Yung,SUNNYVIEW HEIGHTS ADD. BLOCK 14 N. 5' OF LOT 1...,71100.0,82945,Kimball
...,...,...,...,...,...,...,...,...
138,2021-09-28,530016818,Barbara K Michael,Carmen M Jackman,TRACT 200 FEET BY 300 FEET IN THE N 1/2 OF THE...,225000.0,156655,Rural Resi
139,2022-04-11,530015951,Sammie M & Lovina Gingerich,Sammie & Talia L Gingerich,23.540 ACRES IN SE 1/4 S. OF UPRR 29-15-54,167000.0,190030,Rural Resi
140,2022-04-28,530020041,Michael A & Clara Sue Salazar,Matthew & Crystal Brown,TAX LOT 14 MORGAN'S SUBDIVISION IN E 1/2 OF SW...,305000.0,150090,Rural Resi
141,2022-05-11,530151785,Jean A Mueller-Yanaga,Daniel Glasgow,TRACT IN SE 1/4 AND E 1/2 NE 1/4 SW 1/4 33-15-55,190000.0,96960,Rural Resi
142,2022-07-07,530023288,Central Properties,"Adair Holdings, LLC",9.883 ACRE TRACT IN N 1/2 N 1/2 6-16-53,126185.0,126185,Rural Resi

,Sale Date,Parcel ID,Seller,Buyer,LEGAL DESCRIPTION,Sale Price,Assessed Value,Assessor Location
1,2019-10-03,530042460,Kathleen P & Ricky L Chapman,Paul Richard & Rebecca Ellen Burris,SUNNYVIEW HEIGHTS ADDITION BLOCK 11 LOT 4,92500.0,71505,Kimball
2,2019-10-17,530033399,Tammy Adair,Doris F Burton,DOWD'S SECOND ADDITION BLOCK - LOT 10 AND SW 2...,147000.0,125245,Kimball
3,2019-11-06,530036754,Howard R & Shirley J Hoberg,David W & Debra A Gibson,LEAMINGS ADD BLOCK 7 LOT 6 AND THE N 1/2 OF LOT 7,89500.0,76555,Kimball
4,2019-11-07,530035448,Dan J & Cindy L Dean,Ryan M & Tiffany K Johnson,HUFF'S SECOND ADDITION BLOCK 1 S 5' OF LOT 1 A...,170000.0,175775,Kimball
5,2019-11-11,530038803,Diana K Fiehtner,Frank & Norma Stauffer,SOUTH PARK ADDITION BLOCK 14 W 80' OF LOTS 1-3...,60000.0,53015,Kimball
...,...,...,...,...,...,...,...,...
170,2021-03-05,530010445,Daniel B Arnold,Timothy Wayne & Dixie Lee Smith,6-14-55 PART OF S1/2S1/2 6-14-55,330000.0,215195,Rural Resi
171,2021-03-25,530024640,Kathleen Atkins Trustee,Ryan Lukassen & Elyse Schlake,25-16-54 A TRACT IN THE N/2NE/4 25-16-54,265000.0,161020,Rural Resi
172,2021-05-03,530005069,Garland & Megan Hamilton,Sara Silvanage,6.502 ACRE TRACT IN NE1/4NE1/4 26-13-55,122000.0,103510,Rural Resi
173,2021-08-05,530010518,Michael T & Renee A Geha,Adam Geha,1.907 A. IN SE CORNER OF SW 1/4 7-14-55,80000.0,74345,Rural Resi
174,2021-09-28,530016818,Barbara K Michael,Carmen M Jackman,TRACT 200 FEET BY 300 FEET IN THE N 1/2 OF THE...,225000.0,156655,Rural Resi

,Sale Date,Parcel ID,Seller,Buyer,LEGAL DESCRIPTION,Sale Price,Assessor Location
1,2017-10-12,530038722,Carson R Sisk,Shelby L Widener,SOUTH PARK ADDITION BLOCK 13 LOT 9,88000.0,Kimball
2,2017-10-20,530034484,Donna L Luther,David J & Barbara A Nickel,HILLCREST FIRST ADDITION BLOCK 1 LOT 6,73500.0,Kimball
3,2017-10-26,530042738,Rhonda Green & Roger Seeman,Joshua & Bobbie J Ybarra,SUNNYVIEW HEIGHTS ADDITION BLOCK 13 S.6' OF LO...,75000.0,Kimball
4,2017-10-27,530035642,Chauncey & Stephanie Pedersen,Monica Cajero & Efrain Soto,KIMBALL HEIGHTS ADDITION - LOT 13,138000.0,Kimball
5,2017-10-27,530034735,Irene J Wallin,Bernardo & Mercedes Quinones,HILLCREST SECOND ADDITION BLOCK 2 LOT 4,55000.0,Kimball
...,...,...,...,...,...,...,...
128,2018-12-07,530061201,Sam & Lovina Gingerich,Tracy & Sabine Kasten,1.82 ACRES IN N 1/2 NW 1/4 35-15-54,45000.0,Rural Resi
129,2018-12-19,530009099,Maury D & Diane B Horst,Larry & Denise Loose,20.07 ACRE TRACT IN NE 1/4 5-14-54,105000.0,Rural Resi
130,2019-03-22,530157749,David & Joanna Hottell,Liam Dunn,TRACT IN SE 1/4 OF SE 1/4 OF SW 1/W 22-13-53,125000.0,Rural Resi
131,2019-05-13,530029073,Robert Mueller,Richard R & Kelli L Patterson,LOT 1 PRAIRIE RIDGE ESTATE 17-15-55,249000.0,Rural Resi
132,2019-08-30,530017377,Darren L & Kelleigh Huff,Teresa Teppert,11.449 ACRES IN THE SE 1/4 OF THE SW 1/4 SOUTH...,157000.0,Rural Resi

,Sale Date,Parcel ID,Seller,Buyer,LEGAL DESCRIPTION,Sale Price,Assessor Location
0,2014-10-17,530041421,Robert & Denise Waite,Preston Walls,SOUTH PARK ADD. BLOCK 3 N 1/2 OF LOT 13 AND AL...,54500.0,Kimball
1,2014-10-29,530035642,Elizabeth Shandera,Chauncey & Stephanie Pedersen,KIMBALL HEIGHTS ADD. LOT 13,140000.0,Kimball
2,2014-11-14,530032732,Wilma Vencill,Michael Mowry,CLARKSON ADD. BLOCK 10 LOT 6 AND N. 25' OF LOT 7,57000.0,Kimball
3,2014-11-14,530042800,Krissy Petersen,Roy Hammond,SUNNYVIEW HEIGHTS ADD. BLOCK 13 LOT 14,49600.0,Kimball
4,2014-11-24,530047381,Dennis & Robin McIntosh,Marc & Elizabeth Taylor,ANTELOPEVILLE ADD. BLOCK 8 W 1/2 OF LOTS8 AND 9,102000.0,Kimball
5,2014-12-01,530036134,Debra Schadegg,Penny Blackman-Hobbs,LEAMINGS ADD. BLOCK 2 LOT 12,20000.0,Kimball
6,2014-12-19,530044404,Ryan & Theresa Wilson,Elvin & Lynette Helms,YANNAYON ADD. BLOCK 8 A STRIP 43' IN WEST E...,20000.0,Kimball
7,2014-12-19,530036029,Dorothy Christiansen,James Wessels,LEAMINGS ADD. BLOCK 1 LOT 8,34000.0,Kimball
8,2014-12-29,530033798,Charles E & M Joyce Shields,Marcelino Calderon,FAIRVIEW ADD. BLOCK 4 LOTS 21-22-23 AND 24,20000.0,Kimball
9,2015-01-06,530042673,Kathy Brules,Marcelino & Dulce Calderon,SUNNYVIEW HEIGHTS ADD. BLOCK 13 LOT 3,41900.0,Kimball
10,2015-01-08,530037157,Randee Hottell,Michael Webb,LEAMINGS ADD. BLOCK 12 LOT 6,38500.0,Kimball
11,2015-01-09,530042851,Robert Baker,Joseph & Sharlet Morgan,SUNNYVIEW HEIGHTS ADD. BLOCK 14 LOT 5,38000.0,Kimball
12,2015-01-09,530044005,Robert Baker,Joseph & Sharlet Morgan,FREDERICK ADD. BLOCK 3 LOT 2,42000.0,Kimball
13,2015-02-02,530032341,Carmen Freeman,Gerald & Lana Anderson,CLARKSON ADD. BLOCK 7 LOT 2,45000.0,Kimball
14,2015-02-11,530036916,Robert & Gina Lopez,Max & Caitlin Williams,LEAMINGS ADD. BLOCK 9 LOT 4,67000.0,Kimball
15,2015-02-26,530032961,Jim & Charlotta Young,Andrew Brown,DOWD'S FIRST ADD. BLOCK 1 LOT 2,74500.0,Kimball
16,2015-03-15,530032465,Norma Stolz,Albert & Cynthia Johnson,CLARKSON ADD. BLOCK 7 E 1/2 OF LOTS 14-15 ...,63000.0,Kimball
17,2015-03-27,530041162,Scott & Kim Milewski,EDZ Property Investments LLC,SOUTH PARK ADD. BLOCK 1 LOT 9,67000.0,Kimball
18,2015-03-30,530067730,Troy & Bob Unzicker,Marshall & Kim Lewis,KINGSWOOD 2ND ADDITION BLOCK 1 LOTS 7 & 8,129000.0,Kimball
19,2015-04-10,530041197,Scott & Kim Milewski,Cody Markham,SOUTH PARK ADD. BLOCK 1 LOT 11,65000.0,Kimball
20,2015-04-22,530042053,Points West Community Bank,James & Donna Cederburg,SOUTH PARK ADD. BLOCK 10 LOT 3,20111.0,Kimball
21,2015-05-01,530032767,Shawn Becker,Marvin & Sandra Tabor,CLARKSON ADD. BLOCK 11 LOT 2,30000.0,Kimball
22,2015-05-07,530033593,Josephine Vernon,Dustin Erikson,EAST MANOR FIRST ADD. BLOCK 1 LOT 7,30000.0,Kimball
23,2015-05-21,530067722,David & Lisa Schohl,Mary Price,KINGSWOOD 2ND ADDITION BLOCK 1 LOT 6,162000.0,Kimball
24,2015-06-08,530036088,June Nielsen,John Robert & Rut Noemi Miller,LEAMINGS ADD. BLOCK 2 LOT 6,39000.0,Kimball
25,2015-06-12,530034581,Gerald & Lana Anderson,Zachary & Merissa Donnan,HILLCREST THIRD ADD. BLOCK 1 LOT 3,105000.0,Kimball
26,2015-07-17,530040115,Kara Dike,Dennis & Grayce Keller,SUNNYVIEW HEIGHTS ADD. BLOCK 9 LOT 1,82000.0,Kimball
27,2015-07-27,530035871,William Thomas,Matthew Bright,KINGSWOOD FIRST ADD. LOT 4,132000.0,Kimball
28,2015-07-30,530033488,Robert & Carol Pinkerton,Justin & Jacqueline Prather,DOWD'S SECOND ADD. BLOCK - LOT 19,150000.0,Kimball
29,2015-07-31,530034611,Lydia Hamilton,Luke & Lindsey Maas,HILLCREST THIRD ADD. BLOCK 1 LOT 5,95000.0,Kimball
30,2015-08-28,530040468,Gerald & Lana Anderson,Patrick Connelly,ORIGINAL KIMBALL ADD. BLOCK 18 LOTS 1 AND 2,32000.0,Kimball
31,2015-09-15,530031981,Kyle & Laura Johnson,Gerald & Lana Anderson,CLARKSON ADD. BLOCK 2 LOT 12,66000.0,Kimball
32,2015-09-25,530036703,Margaret Case,Patrick Connelly,LEAMINGS ADD. BLOCK 7 LOT 1,18000.0,Kimball
33,2015-10-19,530035847,Donald Thompson,Carolyn & Jennette Wood,KINGSWOOD FIRST ADD. LOT 1,62000.0,Kimball
34,2015-10-26,530045036,William Loring,Aleta Lewis,BURG'S ADD. BLOCK 2 ALL OF SUBLOT 1 OF LOTS 1...,30000.0,Kimball
35,2015-10-27,530033003,William & Winifred Petersen,Matthew & Rachel Merryfield,DOWD'S FIRST ADD. BLOCK 2 LOT 1,87500.0,Kimball
36,2015-11-12,530017318,James & Charlotta Young,Jose & Fatima Lozoya,PART OF THE SW 1/4 SOUTH OF THE UPRR 28-15-55,95000.0,Kimball
37,2015-11-27,530033798,Marcelino Calderon,Daniel & Sherry Acheson,FAIRVIEW ADD. BLOCK 4 LOTS 21-22-23 AND 24,30000.0,Kimball
38,2015-11-30,530033348,Max Williams,Casey & Katie Madden,DOWD'S SECOND ADD. BLOCK - LOT 5,108500.0,Kimball
39,2015-12-07,530044390,Jarrod & Tara Schnell,Sheldon & Terry Padelio,YANNAYON ADD. BLOCK 8 LOTS 15 AND 16 EXC. A...,92000.0,Kimball
40,2015-12-18,530033364,Sandra Lemaster,Tyler Olson,DOWD'S SECOND ADD. BLOCK - LOT 7,110000.0,Kimball
41,2015-12-31,530044293,Jeremy & Kerri Kerr,Marilyn Baker & Amy Sapp,YANNAYON ADD. BLOCK 8 LOT 4,101000.0,Kimball
42,2016-01-08,530035928,Dennis Baack Successor Trustee,Cory Shaw,KINGSWOOD FIRST ADD. LOT 7,92500.0,Kimball
43,2016-01-29,530045257,Marshall & Paula Hopkins,Ty Gibson,BURG'S ADD. BLOCK 4 LOT 5,55000.0,Kimball
44,2016-02-03,530032139,Elmer Bogert,Allen & Lindsey Chavez,CLARKSON ADD. BLOCK 5 S 1/2 OF LOT 2 ANDALL LOT 3,50000.0,Kimball
45,2016-02-11,530040220,Steven Cleveland,Lincoln & Kelsey Brown,ORIGINAL KIMBALL ADD. BLOCK 10 LOTS 8 AND 9 ...,24000.0,Kimball
46,2016-03-04,530035480,Helen Henson,Chad Wise,HUFF'S SECOND ADD. BLOCK 2 S. 43.2' OF LOT 1 ...,130000.0,Kimball
47,2016-03-17,530043106,Donald & Joyce Maxted,Richard & Brenda Baliman,TRITT ADD. BLOCK 1 LOT 8,128900.0,Kimball
48,2016-03-18,530018993,Richard & Brenda Baliman,Michael & Jennifer Coleman,A TRACT 100' X 140' SOUTH OF BLK 17 SOUTH ...,125000.0,Kimball
49,2016-04-08,530018500,Travis Terrell,Dawn Maier,A TRACT 199.36 FEET BY 210.5 FEET LOT 1 HULL'S...,95000.0,Kimball
50,2016-04-08,530042134,Kristine Carr,Elizabeth Taylor-Herzberger,SOUTH PARK ADD. BLOCK 10 N 1/3 OF LOT 13AND AL...,35000.0,Kimball
51,2016-04-15,530038145,Carl & Elizabeth Bateman,Robert & Gina Lopez,LOCKWOOD'S ADD. BLOCK 2 LOTS 13 AND 14,51000.0,Kimball
52,2016-05-03,530036657,Ryan Haas,David & Tracie Gamblin,LEAMINGS ADD. BLOCK 6 LOTS 9 AND 10,127000.0,Kimball
53,2016-05-26,530042991,Michael & Andrea Bemis,Amanda Lusche,SUNNYVIEW HEIGHTS ADD. BLOCK 15 LOT 4,83000.0,Kimball
54,2016-06-17,530033593,Dustin Erickson,Raymond Forehand,EAST MANOR FIRST ADD. BLOCK 1 LOT 7,35000.0,Kimball
55,2016-06-20,530040174,Emmanuel Gutierrez,Raymond Forehand,ORIGINAL KIMBALL ADD. BLOCK 10 LOTS 1 AND 2 ...,50000.0,Kimball
56,2016-06-23,530042657,Harold Kolene Edwards,James Wurnig,SUNNYVIEW HEIGHTS ADD. BLOCK 13 LOT 1,65000.0,Kimball
57,2016-06-29,530041847,Wilson Bowling,Joe & Christine Lewis,SOUTH PARK ADD. BLOCK 7 LOT 7,49000.0,Kimball
58,2016-06-29,530040093,Jean & Charles Kasson,Charlotte Weigel,SUNNYVIEW HEIGHTS ADD. BLOCK 8 LOT 11,58500.0,Kimball
59,2016-08-12,530039818,Mildred King,Tyler & Anne White,SUNNYVIEW HEIGHTS ADD. BLOCK 6 LOT 4,64500.0,Kimball
60,2016-08-15,530033372,JMK Revocable Trust,John Freed,DOWD'S SECOND ADD. BLOCK - LOT 8,160000.0,Kimball
61,2016-08-25,530036940,Deborah Moehr,Daniel & Patricia Deines,LEAMINGS ADD. BLOCK 10 E.62.89' OF LOTS 1 AND 2,20000.0,Kimball
62,2016-08-26,530042185,Leonard Michal,Richard Brookman,SOUTH PARK ADD. BLOCK 11 S 1/2 OF LOT 6 AND AL...,22500.0,Kimball
63,2016-08-31,530035316,Marrian Hennings,Z & S Construction Co,HILLCREST SIXTH ADD. BLOCK 2 LOT 3,80000.0,Kimball
64,2016-09-02,530039400,Daniel & Shirley Kinnison,Nate & Heather Entingh & Paula Weiss,SOUTH PARK ADD. BLOCK 21 E. 70' OF THAT PART O...,85000.0,Kimball
65,2016-09-06,530043467,Mary Moehr,Robert & Jacqueline Hill,YANNAYON ADD. BLOCK 3 LOTS 3 AND 4,36000.0,Kimball
66,2016-09-21,530035863,John & Maureen Trout,Elizabeth Shandera,KINGSWOOD FIRST ADD. LOT 3,125000.0,Kimball
67,2016-09-27,530036614,Gloria Barkley,Val Deane & Kathleen Snyder,LEAMINGS ADD. BLOCK 6 S. 40' OF LOT 3 AND TH...,38000.0,Kimball
68,2016-09-29,530033313,Anne Anderson,Matthew & Stephanie Shoup,DOWD'S SECOND ADD. BLOCK - LOT 3,85000.0,Kimball
69,2016-09-30,530031698,Wade Kiefer,Carl Stander,ALDENS ADD. BLOCK 1 N. 94' OF LOT 2,110000.0,Kimball
71,2015-04-15,530050765,Nathan Juhl,"John, Jaclyn, Chad & Julia Miller",HORRUM'S FIRST ADD. BLOCK 17 LOT 7 AND THE S ...,38000.0,Dix
72,2015-07-22,530050897,Marie Cashion,Harold & Gail Dunkle,HORRUM'S FIRST ADD. BLOCK 19 LOTS 13 AND14,55000.0,Dix
74,2014-11-26,530049260,Robert & Marie Adams,Deann Sweeter,WOOLDRIDGE ADD. BLOCK 1 LOTS 7 AND 8,76000.0,Bushnell
75,2015-03-03,530047446,Patricia Clason,Jay Latta,BUSHNELL VILLAGE ADD BLOCK 1 S. 25 FEET OF LOT...,29000.0,Bushnell
76,2015-06-01,530047721,Susan Rose,Joseph & Sharlet Morgan,BUSHNELL VILLAGE ADD. BLOCK 4 LOTS 18-19AND 20,25000.0,Bushnell
77,2016-09-29,530049228,Peter & Annelies Cunis,John & Venita Zimmerman,THOMAS ADD. BLOCK 6 LOTS 7 AND 8,72500.0,Bushnell
79,2014-11-06,530157938,William Spires,Andrew Knicely,3.99 A.TRACT IN SE1/4 28-15-56,80000.0,Rural Resi
80,2015-02-24,530031094,Nationstar Mortgage LLC,James & Karla Jenkins,TRACT S. OF UPRR IN SE 1/4 26-15-56,118000.0,Rural Resi
81,2015-02-27,530028050,Laurie & Mark Bennett,Whiting Oil & Gas Corp,63.398 A. TRACT IN SE CORNER 10-16-58,100000.0,Rural Resi
82,2015-07-02,530019191,Marjorie Shirk,David & Michelle Henker,LOT 2R DEBOODT SUBDIVISION (N1/2NW1/4) 33-15-55,63000.0,Rural Resi
83,2015-09-04,530007347,Dolores Harms Trustee,Carl Butler,TRACT IN E1/2 NE 1/4 14-13-58,40000.0,Rural Resi
84,2015-09-30,530160227,Kyle & Laura Johnson,Jay & Ashley Thurin,PART OF NE1/4SE1/4 2-15-55,220000.0,Rural Resi
85,2015-10-07,530153150,Cheema Investments,Ryan Burback & Stacy Garrett,1.498 A. TRACT IN NW 1/4 17-15-55,70000.0,Rural Resi
86,2015-11-05,530016818,Stanley & Beverly Pearson,Barbara Michael,TRACT 200 FEET BY 300 FEET IN THE N 1/2 OF THE...,175750.0,Rural Resi
87,2015-11-20,530151659,Lawrence & Nicole Snyder,Robert & Fawney Vincent,4.954A. TRACT IN SW1/4 30-15-56,123000.0,Rural Resi
88,2016-01-25,530028050,Whiting Oil & Gas Corp,Austin Garner,63.398 A. TRACT IN SE CORNER 10-16-58,95000.0,Rural Resi
89,2016-03-06,530029146,Daniel & Misty Curtis,Natalie & Owen Elder,LOTS 6 & 7 LESS TRACT PRAIRIE RIDGE ESTATE...,185000.0,Rural Resi
90,2016-07-25,530028522,David & Martha Cannon,Paul & Linda Piatz,19.854 ACRE TRACT IN 12-16-59,173000.0,Rural Resi

,Sale Date,Parcel ID,Seller,Buyer,LEGAL DESCRIPTION,Sale Price,Assessor Location
0,2015-10-19,530035847,Donald Thompson,Carolyn & Jennette Wood,KINGSWOOD FIRST ADD. LOT 1,62000.0,Kimball
1,2015-10-26,530045036,William Loring,Aleta Lewis,BURG'S ADD. BLOCK 2 ALL OF SUBLOT 1 OF LOTS 1...,30000.0,Kimball
2,2015-10-27,530033003,William & Winifred Petersen,Matthew & Rachel Merryfield,DOWD'S FIRST ADD. BLOCK 2 LOT 1,87500.0,Kimball
3,2015-11-12,530017318,James & Charlotta Young,Jose & Fatima Lozoya,PART OF THE SW 1/4 SOUTH OF THE UPRR 28-15-55,95000.0,Kimball
4,2015-11-27,530033798,Marcelino Calderon,Daniel & Sherry Acheson,FAIRVIEW ADD. BLOCK 4 LOTS 21-22-23 AND 24,30000.0,Kimball
...,...,...,...,...,...,...,...
113,2017-04-24,530009285,Monica & Magdaleno Cajero,Donald Weeks,TRACT IN E 1/2 NE 1/4 OF 10-14-54 (26.849 ACRES),135000.0,Rural Resi
114,2017-06-16,530020173,Kristi & Ronald Cortney,Toni & Edward Barnes,TAX LOT 8 PART OF SE 1/4 OF THE NW 1/4 & NE 1/...,150499.0,Rural Resi
115,2017-07-12,530020041,Jason Hottell,Robin Whitehead,TAX LOT 14 MORGANS SUBDIVISION IN E 1/2 OF SW ...,187000.0,Rural Resi
116,2017-08-25,530010445,Lyle & Shonna Yung,Daniel & Mercedes Arnold,PART OF S 1/2 S 1/2 6-14-55 30.012 ACRES,235000.0,Rural Resi
117,2017-09-14,530151659,Robert & Fawney Vincent,Christine & Eddie Sharkey,4.954 ACRE TRACT IN SW 1/4 30-15-56,135000.0,Rural Resi

,Sale Date,Parcel ID,Seller,Buyer,LEGAL DESCRIPTION,Sale Price,Assessor Location
0,2016-10-13,530045583,James Buckley,Scott Christensen,BURGS ADD. BLOCK 6 LOT 8,37000.0,Kimball
1,2016-10-17,530041286,Charles & Carolyn Carlson,Richard & Gloria Brookman,SOUTH PARK ADD. BLOCK 2 ALL LOT 8 AND S1/8 OF ...,150000.0,Kimball
2,2016-10-20,530035448,James Prince & Nancy Garrett,Patricia Biesecker & Deanna Bleyle,HUFFS SECOND ADD. BLOCK 1 S. 5' OF LOT 1 AND A...,120000.0,Kimball
3,2016-10-24,530032546,Claire Tritt,Ricky & Julia Gehrig,CLARKSON ADD. BLOCK 8 S. 20' OF LOT 7 AND ALL ...,83000.0,Kimball
4,2016-11-05,530045273,Jennifer Dillinger,Rachel Rowe,BURG'S ADD. BLOCK 4 ALL LOT 7 AND N 15' OF LOT 8,30000.0,Kimball
...,...,...,...,...,...,...,...
137,2018-06-15,530020696,Michael H & Karen M Isley,James N Columbia,A TRACT IN SE 1/4 28-15-56,165000.0,Rural Resi
138,2018-07-06,530031094,Karla J Jenkins,Marvin & Sandra Tabor,TRACT S OF UPRR IN SE 1/4 26-15-56,130000.0,Rural Resi
139,2018-07-18,530151470,Jared C & Melissa L Reich,Karla Jenkins,29.823 A TRACT IN NE 1/4 18-16-55,217500.0,Rural Resi
140,2018-08-01,530025779,Jeanne Anderson,Cheryl Delaplane,TRACT IN WEST PART OF NW 1/4 32-16-55,67000.0,Rural Resi
141,2018-09-14,530026937,Mary Ann Felkins,John M & Alicia I Buchart,7.015 ACRES IN THE NE 1/4 OF THE NE 1/4 OF TH ...,180000.0,Rural Resi

,Sale Date,Parcel ID,Seller,Buyer,LEGAL DESCRIPTION,Sale Price,Assessed Value,Assessor Location
1,2018-10-16,530040824,Larry L & JoAnne M Fleagle,Christopher J Woods,ORIGINAL KIMBALL ADDITION BLOCK 21 LOTS 7 THRU 12,62000.0,40020,Kimball
2,2018-10-18,530033429,Melvin D & Sarah E Bouse,Ka'Lani O'Shea,DOWD'S SECOND ADDITION BLOCK - LOT 14,80000.0,102980,Kimball
3,2018-10-23,530036703,Patrick H Connelly,Mary Ann Felkins,LEAMINGS ADDITION BLOCK 7 LOT 1,40000.0,18875,Kimball
4,2018-10-26,530043416,Lisa A Rockhold,"Virginia K, Troy L & Julie E Davis",YANNAYON ADDITION BLOCK 2 LOT 20,75500.0,67475,Kimball
5,2018-12-14,530035626,Kenneth H & Cynthia Stone Hunter,Ty M & Jessica S Gibson,KIMBALL HEIGHTS ADDITION N. 23' OF LOT 9 AND A...,189000.0,171090,Kimball
...,...,...,...,...,...,...,...,...
133,2020-02-15,530010518,Trevor L Chrystal,Michael T & Renee A Geha,1.907 ACRES IN SE CORNER OF SW 1/4 7-14-55,80000.0,74345,Rural Resi
134,2020-03-13,530021609,Scott E & Susan L Lockwood,Dalton & Ainsley Lockwood,23.147 ACRES IN 36-15-57,490000.0,300120,Rural Resi
135,2020-03-14,530029103,Douglas J & Marvel L Linthicum,Trevor L & Nicole M Anderson,LOT 3 PRAIRIE RIDGE ESTATE 17-15-55,255000.0,206040,Rural Resi
136,2020-04-01,530018365,Walter L Wann,Robert D Dunkin III,TRACT IN NE 1/4 NW 1/4 31-15-55,70000.0,87090,Rural Resi
137,2020-07-24,530050439,Dwayne A & Jonita M Groves,Bradley Ray & Nicole Lynn Hottell,12.415 ACRE TRACT IN NE 1/4 29-15-55,135000.0,197340,Rural Resi

In [56]:
merged_df = pd.DataFrame()

for df in cleaned_dfs:
    merged_df = pd.concat([merged_df, df], ignore_index=True)
    display(merged_df)

,Sale Date,Parcel ID,Seller,Buyer,LEGAL DESCRIPTION,Sale Price,Assessed Value,Assessor Location
0,2020-10-01,530033429,Ka'Lani O'Shea,Sharon June Pickering,DOWD'S SECOND ADD. BLOCK - LOT 14 (CARD #14),100000.0,113040,Kimball
1,2020-10-01,530036932,Chico R Fernandez,Crystal Kisicki,LEAMINGS ADD. BLOCK 9 S. 39' OF THE W. 80' OF ...,38000.0,27545,Kimball
2,2020-10-06,530033488,Justin W & Jacqueline N Prather,Anthony & Linda Madrid,DOWD'S SECOND ADD. BLOCK - LOT 19,145000.0,156090,Kimball
3,2020-10-06,530039036,James & Donna Cederburg,Caleb Reuter,SOUTH PARK ADD. BLOCK 16 W. 110' OF LOT 8 & W....,47900.0,36120,Kimball
4,2020-10-20,530042959,Carol L Meyer,Danny E Yung,SUNNYVIEW HEIGHTS ADD. BLOCK 14 N. 5' OF LOT 1...,71100.0,82945,Kimball
...,...,...,...,...,...,...,...,...
132,2021-09-28,530016818,Barbara K Michael,Carmen M Jackman,TRACT 200 FEET BY 300 FEET IN THE N 1/2 OF THE...,225000.0,156655,Rural Resi
133,2022-04-11,530015951,Sammie M & Lovina Gingerich,Sammie & Talia L Gingerich,23.540 ACRES IN SE 1/4 S. OF UPRR 29-15-54,167000.0,190030,Rural Resi
134,2022-04-28,530020041,Michael A & Clara Sue Salazar,Matthew & Crystal Brown,TAX LOT 14 MORGAN'S SUBDIVISION IN E 1/2 OF SW...,305000.0,150090,Rural Resi
135,2022-05-11,530151785,Jean A Mueller-Yanaga,Daniel Glasgow,TRACT IN SE 1/4 AND E 1/2 NE 1/4 SW 1/4 33-15-55,190000.0,96960,Rural Resi
136,2022-07-07,530023288,Central Properties,"Adair Holdings, LLC",9.883 ACRE TRACT IN N 1/2 N 1/2 6-16-53,126185.0,126185,Rural Resi

,Sale Date,Parcel ID,Seller,Buyer,LEGAL DESCRIPTION,Sale Price,Assessed Value,Assessor Location
0,2020-10-01,530033429,Ka'Lani O'Shea,Sharon June Pickering,DOWD'S SECOND ADD. BLOCK - LOT 14 (CARD #14),100000.0,113040,Kimball
1,2020-10-01,530036932,Chico R Fernandez,Crystal Kisicki,LEAMINGS ADD. BLOCK 9 S. 39' OF THE W. 80' OF ...,38000.0,27545,Kimball
2,2020-10-06,530033488,Justin W & Jacqueline N Prather,Anthony & Linda Madrid,DOWD'S SECOND ADD. BLOCK - LOT 19,145000.0,156090,Kimball
3,2020-10-06,530039036,James & Donna Cederburg,Caleb Reuter,SOUTH PARK ADD. BLOCK 16 W. 110' OF LOT 8 & W....,47900.0,36120,Kimball
4,2020-10-20,530042959,Carol L Meyer,Danny E Yung,SUNNYVIEW HEIGHTS ADD. BLOCK 14 N. 5' OF LOT 1...,71100.0,82945,Kimball
...,...,...,...,...,...,...,...,...
299,2021-03-05,530010445,Daniel B Arnold,Timothy Wayne & Dixie Lee Smith,6-14-55 PART OF S1/2S1/2 6-14-55,330000.0,215195,Rural Resi
300,2021-03-25,530024640,Kathleen Atkins Trustee,Ryan Lukassen & Elyse Schlake,25-16-54 A TRACT IN THE N/2NE/4 25-16-54,265000.0,161020,Rural Resi
301,2021-05-03,530005069,Garland & Megan Hamilton,Sara Silvanage,6.502 ACRE TRACT IN NE1/4NE1/4 26-13-55,122000.0,103510,Rural Resi
302,2021-08-05,530010518,Michael T & Renee A Geha,Adam Geha,1.907 A. IN SE CORNER OF SW 1/4 7-14-55,80000.0,74345,Rural Resi
303,2021-09-28,530016818,Barbara K Michael,Carmen M Jackman,TRACT 200 FEET BY 300 FEET IN THE N 1/2 OF THE...,225000.0,156655,Rural Resi

,Sale Date,Parcel ID,Seller,Buyer,LEGAL DESCRIPTION,Sale Price,Assessed Value,Assessor Location
0,2020-10-01,530033429,Ka'Lani O'Shea,Sharon June Pickering,DOWD'S SECOND ADD. BLOCK - LOT 14 (CARD #14),100000.0,113040,Kimball
1,2020-10-01,530036932,Chico R Fernandez,Crystal Kisicki,LEAMINGS ADD. BLOCK 9 S. 39' OF THE W. 80' OF ...,38000.0,27545,Kimball
2,2020-10-06,530033488,Justin W & Jacqueline N Prather,Anthony & Linda Madrid,DOWD'S SECOND ADD. BLOCK - LOT 19,145000.0,156090,Kimball
3,2020-10-06,530039036,James & Donna Cederburg,Caleb Reuter,SOUTH PARK ADD. BLOCK 16 W. 110' OF LOT 8 & W....,47900.0,36120,Kimball
4,2020-10-20,530042959,Carol L Meyer,Danny E Yung,SUNNYVIEW HEIGHTS ADD. BLOCK 14 N. 5' OF LOT 1...,71100.0,82945,Kimball
...,...,...,...,...,...,...,...,...
424,2018-12-07,530061201,Sam & Lovina Gingerich,Tracy & Sabine Kasten,1.82 ACRES IN N 1/2 NW 1/4 35-15-54,45000.0,NaN,Rural Resi
425,2018-12-19,530009099,Maury D & Diane B Horst,Larry & Denise Loose,20.07 ACRE TRACT IN NE 1/4 5-14-54,105000.0,NaN,Rural Resi
426,2019-03-22,530157749,David & Joanna Hottell,Liam Dunn,TRACT IN SE 1/4 OF SE 1/4 OF SW 1/W 22-13-53,125000.0,NaN,Rural Resi
427,2019-05-13,530029073,Robert Mueller,Richard R & Kelli L Patterson,LOT 1 PRAIRIE RIDGE ESTATE 17-15-55,249000.0,NaN,Rural Resi
428,2019-08-30,530017377,Darren L & Kelleigh Huff,Teresa Teppert,11.449 ACRES IN THE SE 1/4 OF THE SW 1/4 SOUTH...,157000.0,NaN,Rural Resi

,Sale Date,Parcel ID,Seller,Buyer,LEGAL DESCRIPTION,Sale Price,Assessed Value,Assessor Location
0,2020-10-01,530033429,Ka'Lani O'Shea,Sharon June Pickering,DOWD'S SECOND ADD. BLOCK - LOT 14 (CARD #14),100000.0,113040,Kimball
1,2020-10-01,530036932,Chico R Fernandez,Crystal Kisicki,LEAMINGS ADD. BLOCK 9 S. 39' OF THE W. 80' OF ...,38000.0,27545,Kimball
2,2020-10-06,530033488,Justin W & Jacqueline N Prather,Anthony & Linda Madrid,DOWD'S SECOND ADD. BLOCK - LOT 19,145000.0,156090,Kimball
3,2020-10-06,530039036,James & Donna Cederburg,Caleb Reuter,SOUTH PARK ADD. BLOCK 16 W. 110' OF LOT 8 & W....,47900.0,36120,Kimball
4,2020-10-20,530042959,Carol L Meyer,Danny E Yung,SUNNYVIEW HEIGHTS ADD. BLOCK 14 N. 5' OF LOT 1...,71100.0,82945,Kimball
...,...,...,...,...,...,...,...,...
512,2015-11-05,530016818,Stanley & Beverly Pearson,Barbara Michael,TRACT 200 FEET BY 300 FEET IN THE N 1/2 OF THE...,175750.0,NaN,Rural Resi
513,2015-11-20,530151659,Lawrence & Nicole Snyder,Robert & Fawney Vincent,4.954A. TRACT IN SW1/4 30-15-56,123000.0,NaN,Rural Resi
514,2016-01-25,530028050,Whiting Oil & Gas Corp,Austin Garner,63.398 A. TRACT IN SE CORNER 10-16-58,95000.0,NaN,Rural Resi
515,2016-03-06,530029146,Daniel & Misty Curtis,Natalie & Owen Elder,LOTS 6 & 7 LESS TRACT PRAIRIE RIDGE ESTATE...,185000.0,NaN,Rural Resi
516,2016-07-25,530028522,David & Martha Cannon,Paul & Linda Piatz,19.854 ACRE TRACT IN 12-16-59,173000.0,NaN,Rural Resi

,Sale Date,Parcel ID,Seller,Buyer,LEGAL DESCRIPTION,Sale Price,Assessed Value,Assessor Location
0,2020-10-01,530033429,Ka'Lani O'Shea,Sharon June Pickering,DOWD'S SECOND ADD. BLOCK - LOT 14 (CARD #14),100000.0,113040,Kimball
1,2020-10-01,530036932,Chico R Fernandez,Crystal Kisicki,LEAMINGS ADD. BLOCK 9 S. 39' OF THE W. 80' OF ...,38000.0,27545,Kimball
2,2020-10-06,530033488,Justin W & Jacqueline N Prather,Anthony & Linda Madrid,DOWD'S SECOND ADD. BLOCK - LOT 19,145000.0,156090,Kimball
3,2020-10-06,530039036,James & Donna Cederburg,Caleb Reuter,SOUTH PARK ADD. BLOCK 16 W. 110' OF LOT 8 & W....,47900.0,36120,Kimball
4,2020-10-20,530042959,Carol L Meyer,Danny E Yung,SUNNYVIEW HEIGHTS ADD. BLOCK 14 N. 5' OF LOT 1...,71100.0,82945,Kimball
...,...,...,...,...,...,...,...,...
624,2017-04-24,530009285,Monica & Magdaleno Cajero,Donald Weeks,TRACT IN E 1/2 NE 1/4 OF 10-14-54 (26.849 ACRES),135000.0,NaN,Rural Resi
625,2017-06-16,530020173,Kristi & Ronald Cortney,Toni & Edward Barnes,TAX LOT 8 PART OF SE 1/4 OF THE NW 1/4 & NE 1/...,150499.0,NaN,Rural Resi
626,2017-07-12,530020041,Jason Hottell,Robin Whitehead,TAX LOT 14 MORGANS SUBDIVISION IN E 1/2 OF SW ...,187000.0,NaN,Rural Resi
627,2017-08-25,530010445,Lyle & Shonna Yung,Daniel & Mercedes Arnold,PART OF S 1/2 S 1/2 6-14-55 30.012 ACRES,235000.0,NaN,Rural Resi
628,2017-09-14,530151659,Robert & Fawney Vincent,Christine & Eddie Sharkey,4.954 ACRE TRACT IN SW 1/4 30-15-56,135000.0,NaN,Rural Resi

,Sale Date,Parcel ID,Seller,Buyer,LEGAL DESCRIPTION,Sale Price,Assessed Value,Assessor Location
0,2020-10-01,530033429,Ka'Lani O'Shea,Sharon June Pickering,DOWD'S SECOND ADD. BLOCK - LOT 14 (CARD #14),100000.0,113040,Kimball
1,2020-10-01,530036932,Chico R Fernandez,Crystal Kisicki,LEAMINGS ADD. BLOCK 9 S. 39' OF THE W. 80' OF ...,38000.0,27545,Kimball
2,2020-10-06,530033488,Justin W & Jacqueline N Prather,Anthony & Linda Madrid,DOWD'S SECOND ADD. BLOCK - LOT 19,145000.0,156090,Kimball
3,2020-10-06,530039036,James & Donna Cederburg,Caleb Reuter,SOUTH PARK ADD. BLOCK 16 W. 110' OF LOT 8 & W....,47900.0,36120,Kimball
4,2020-10-20,530042959,Carol L Meyer,Danny E Yung,SUNNYVIEW HEIGHTS ADD. BLOCK 14 N. 5' OF LOT 1...,71100.0,82945,Kimball
...,...,...,...,...,...,...,...,...
760,2018-06-15,530020696,Michael H & Karen M Isley,James N Columbia,A TRACT IN SE 1/4 28-15-56,165000.0,NaN,Rural Resi
761,2018-07-06,530031094,Karla J Jenkins,Marvin & Sandra Tabor,TRACT S OF UPRR IN SE 1/4 26-15-56,130000.0,NaN,Rural Resi
762,2018-07-18,530151470,Jared C & Melissa L Reich,Karla Jenkins,29.823 A TRACT IN NE 1/4 18-16-55,217500.0,NaN,Rural Resi
763,2018-08-01,530025779,Jeanne Anderson,Cheryl Delaplane,TRACT IN WEST PART OF NW 1/4 32-16-55,67000.0,NaN,Rural Resi
764,2018-09-14,530026937,Mary Ann Felkins,John M & Alicia I Buchart,7.015 ACRES IN THE NE 1/4 OF THE NE 1/4 OF TH ...,180000.0,NaN,Rural Resi

,Sale Date,Parcel ID,Seller,Buyer,LEGAL DESCRIPTION,Sale Price,Assessed Value,Assessor Location
0,2020-10-01,530033429,Ka'Lani O'Shea,Sharon June Pickering,DOWD'S SECOND ADD. BLOCK - LOT 14 (CARD #14),100000.0,113040,Kimball
1,2020-10-01,530036932,Chico R Fernandez,Crystal Kisicki,LEAMINGS ADD. BLOCK 9 S. 39' OF THE W. 80' OF ...,38000.0,27545,Kimball
2,2020-10-06,530033488,Justin W & Jacqueline N Prather,Anthony & Linda Madrid,DOWD'S SECOND ADD. BLOCK - LOT 19,145000.0,156090,Kimball
3,2020-10-06,530039036,James & Donna Cederburg,Caleb Reuter,SOUTH PARK ADD. BLOCK 16 W. 110' OF LOT 8 & W....,47900.0,36120,Kimball
4,2020-10-20,530042959,Carol L Meyer,Danny E Yung,SUNNYVIEW HEIGHTS ADD. BLOCK 14 N. 5' OF LOT 1...,71100.0,82945,Kimball
...,...,...,...,...,...,...,...,...
889,2020-02-15,530010518,Trevor L Chrystal,Michael T & Renee A Geha,1.907 ACRES IN SE CORNER OF SW 1/4 7-14-55,80000.0,74345,Rural Resi
890,2020-03-13,530021609,Scott E & Susan L Lockwood,Dalton & Ainsley Lockwood,23.147 ACRES IN 36-15-57,490000.0,300120,Rural Resi
891,2020-03-14,530029103,Douglas J & Marvel L Linthicum,Trevor L & Nicole M Anderson,LOT 3 PRAIRIE RIDGE ESTATE 17-15-55,255000.0,206040,Rural Resi
892,2020-04-01,530018365,Walter L Wann,Robert D Dunkin III,TRACT IN NE 1/4 NW 1/4 31-15-55,70000.0,87090,Rural Resi
893,2020-07-24,530050439,Dwayne A & Jonita M Groves,Bradley Ray & Nicole Lynn Hottell,12.415 ACRE TRACT IN NE 1/4 29-15-55,135000.0,197340,Rural Resi

In [57]:
print(len(merged_df))
merged_df.sort_values(by='Sale Date')

894

,Sale Date,Parcel ID,Seller,Buyer,LEGAL DESCRIPTION,Sale Price,Assessed Value,Assessor Location
429,2014-10-17,530041421,Robert & Denise Waite,Preston Walls,SOUTH PARK ADD. BLOCK 3 N 1/2 OF LOT 13 AND AL...,54500.0,NaN,Kimball
430,2014-10-29,530035642,Elizabeth Shandera,Chauncey & Stephanie Pedersen,KIMBALL HEIGHTS ADD. LOT 13,140000.0,NaN,Kimball
505,2014-11-06,530157938,William Spires,Andrew Knicely,3.99 A.TRACT IN SE1/4 28-15-56,80000.0,NaN,Rural Resi
432,2014-11-14,530042800,Krissy Petersen,Roy Hammond,SUNNYVIEW HEIGHTS ADD. BLOCK 13 LOT 14,49600.0,NaN,Kimball
431,2014-11-14,530032732,Wilma Vencill,Michael Mowry,CLARKSON ADD. BLOCK 10 LOT 6 AND N. 25' OF LOT 7,57000.0,NaN,Kimball
...,...,...,...,...,...,...,...,...
105,2022-08-12,530034344,Abraham Parra,"Lynn Tornberg, James Cleveland & Shawna Cleveland",FORSLINGS ADD. BLOCK 3 LOT 12,185000.0,37575,Kimball
106,2022-08-19,530042606,Dillon Hatfield,Carter Rompola,SUNNYVIEW HEIGHTS ADD. BLOCK 12 LOT 10,125000.0,94675,Kimball
107,2022-08-29,530033615,Linda Williams,"809 S Elm St, LLC",EAST MANOR FIRST ADD. BLOCK 1 LOT 9,83000.0,46040,Kimball
108,2022-09-09,530036843,"Kimball DJ, LLC",Eldon & Kylee Lewis,"LEAMINGS ADD, BLOCK 8 LOT 3 AND THE N 1/2 OF L...",120000.0,70375,Kimball
109,2022-09-26,530045109,Johnny D & Dawn Clifford,Mario Leiva Duran & Mirna Azucena Guerrero,BURG'S ADD. BLOCK 2 S 1/2 OF LOT 23 AND ALL LO...,39000.0,39900,Kimball

In [58]:
pd.set_option('display.max_rows', 100)
merged_df.loc[merged_df.duplicated(),:]

,Sale Date,Parcel ID,Seller,Buyer,LEGAL DESCRIPTION,Sale Price,Assessed Value,Assessor Location
190,2020-10-01,530033429,Ka'Lani O'Shea,Sharon June Pickering,DOWD'S SECOND ADD. BLOCK - LOT 14 (CARD #14),100000.0,113040,Kimball
191,2020-10-01,530036932,Chico R Fernandez,Crystal Kisicki,LEAMINGS ADD. BLOCK 9 S. 39' OF THE W. 80' OF ...,38000.0,27545,Kimball
192,2020-10-06,530033488,Justin W & Jacqueline N Prather,Anthony & Linda Madrid,DOWD'S SECOND ADD. BLOCK - LOT 19,145000.0,156090,Kimball
193,2020-10-06,530039036,James & Donna Cederburg,Caleb Reuter,SOUTH PARK ADD. BLOCK 16 W. 110' OF LOT 8 & W....,47900.0,36120,Kimball
194,2020-10-20,530042959,Carol L Meyer,Danny E Yung,SUNNYVIEW HEIGHTS ADD. BLOCK 14 N. 5' OF LOT 1...,71100.0,82945,Kimball
...,...,...,...,...,...,...,...,...
889,2020-02-15,530010518,Trevor L Chrystal,Michael T & Renee A Geha,1.907 ACRES IN SE CORNER OF SW 1/4 7-14-55,80000.0,74345,Rural Resi
890,2020-03-13,530021609,Scott E & Susan L Lockwood,Dalton & Ainsley Lockwood,23.147 ACRES IN 36-15-57,490000.0,300120,Rural Resi
891,2020-03-14,530029103,Douglas J & Marvel L Linthicum,Trevor L & Nicole M Anderson,LOT 3 PRAIRIE RIDGE ESTATE 17-15-55,255000.0,206040,Rural Resi
892,2020-04-01,530018365,Walter L Wann,Robert D Dunkin III,TRACT IN NE 1/4 NW 1/4 31-15-55,70000.0,87090,Rural Resi
893,2020-07-24,530050439,Dwayne A & Jonita M Groves,Bradley Ray & Nicole Lynn Hottell,12.415 ACRE TRACT IN NE 1/4 29-15-55,135000.0,197340,Rural Resi

In [59]:
sales_df = merged_df.loc[~merged_df.duplicated(),:]
print(len(sales_df))

641

In [60]:
sales_df.sort_values(by='Parcel ID')

,Sale Date,Parcel ID,Seller,Buyer,LEGAL DESCRIPTION,Sale Price,Assessed Value,Assessor Location
301,2021-05-03,530005069,Garland & Megan Hamilton,Sara Silvanage,6.502 ACRE TRACT IN NE1/4NE1/4 26-13-55,122000.0,103510,Rural Resi
289,2020-02-03,530005069,Kristine Carr,Garland & Megan Hamilton,A 6.502 ACRE TRACT IN 26-13-55,80000.0,101495,Rural Resi
509,2015-09-04,530007347,Dolores Harms Trustee,Carl Butler,TRACT IN E1/2 NE 1/4 14-13-58,40000.0,NaN,Rural Resi
881,2018-12-19,530009099,Maury D & Diane B Horst,Larry & Denise Loose,20.07 ACRE TRACT IN NE 1/4 5-14-54,105000.0,62185,Rural Resi
425,2018-12-19,530009099,Maury D & Diane B Horst,Larry & Denise Loose,20.07 ACRE TRACT IN NE 1/4 5-14-54,105000.0,NaN,Rural Resi
...,...,...,...,...,...,...,...,...
423,2018-10-26,530154424,Kelli Patterson,Ernest & Lea Hottell,29.810 A TRACT IN SE 1/4 31-14-55,190000.0,NaN,Rural Resi
426,2019-03-22,530157749,David & Joanna Hottell,Liam Dunn,TRACT IN SE 1/4 OF SE 1/4 OF SW 1/W 22-13-53,125000.0,NaN,Rural Resi
882,2019-03-22,530157749,David & Joanna Hottell,Liam Dunn,TRACT IN SE 1/4 OF SE 1/4 OF SW 1/W 22-13-53,125000.0,102330,Rural Resi
505,2014-11-06,530157938,William Spires,Andrew Knicely,3.99 A.TRACT IN SE1/4 28-15-56,80000.0,NaN,Rural Resi
510,2015-09-30,530160227,Kyle & Laura Johnson,Jay & Ashley Thurin,PART OF NE1/4SE1/4 2-15-55,220000.0,NaN,Rural Resi

In [61]:
sales_df.loc[sales_df['Buyer'].str.contains("Lincoln")]

,Sale Date,Parcel ID,Seller,Buyer,LEGAL DESCRIPTION,Sale Price,Assessed Value,Assessor Location
183,2020-08-28,530034360,William Russell,Lincoln Robert & Kelsey Leigh Brown,FORSLINGS ADDITION BLOCK 3 N 10' OF LOT 13 AND...,67500.0,72230,Kimball
474,2016-02-11,530040220,Steven Cleveland,Lincoln & Kelsey Brown,ORIGINAL KIMBALL ADD. BLOCK 10 LOTS 8 AND 9 ...,24000.0,NaN,Kimball

In [62]:
sales_pids = sales_df['Parcel ID']

test_price = sales_df.loc[sales_df['Parcel ID']== sales_pids[0], 'Sale Price']
print(test_price)

0      100000.0
357     80000.0
766     80000.0
Name: Sale Price, dtype: float64

In [63]:
def get_pid_info(pid):
        with open(f"PID_Details/{pid}_detail.json") as pid_file:
            [raw_text] = pid_file.readlines()
        data = json.loads(raw_text)
        return data

In [64]:
def get_json_len(pid):
    path = f"PID_Details/{pid}_detail.json"
    if os.path.exists(path):
        with open(path) as pid_file:
            [raw_text] = pid_file.readlines()
        data = json.loads(raw_text)
        parcel_data = data['items'][0]['items']
        print(len(parcel_data))

In [65]:
for pid in sales_pids:
    get_json_len(pid)

11
11
10
10
10
11
11
10
11
10
10
10
11
11
11
11
11
11
11
11
11
11
10
10
11
11
10
11
11
11
11
11
10
11
10
10
11
11
11
10
11
11
10
10
10
11
10
10
11
11
10
11
11
11
10
11
11
11
11
11
11
11
11
10
11
10
11
11
11
10
11
11
10
11
10
11
10
11
11
11
10
11
11
11
10
10
11
11
11
11
10
11
11
10
11
10
10
11
10
10
11
11
11
10
11
10
10
11
11
11
11
11
11
11
11
11
11
10
11
11
11
10
11
11
11
11
11
11
11
11
11
11
11
11
11
11
11
10
11
11
11
11
11
10
10
11
11
11
11
10
11
11
11
11
11
11
10
11
11
11
10
11
11
11
11
11
10
10
11
11
11
10
11
11
10
11
11
10
11
11
11
11
11
11
11
10
11
11
11
11
10
12
10
11
11
10
10
11
11
11
11
11
11
11
10
11
11
11
11
11
11
12
11
11
11
11
11
11
11
11
11
11
12
11
10
10
10
11
11
11
11
10
11
10
11
11
11
11
11
10
11
11
11
10
11
10
12
11
11
11
10
10
11
10
10
11
11
11
11
8
11
11
11
10
10
11
10
11
11
11
11
11
11
11
11
11
10
11
11
10
11
11
11
11
11
11
11
11
11
10
10
11
10
11
10
11
10
11
10
11
11
11
10
11
10
11
11
11
11
11
11
10
11
11
11
11
10
11
11
11
11
11
11
10
11
10
11
11
11
11
11
11
11
11
11
11
11
11
11
11
11
11
10
11
11
11
11
11
11
11
10
10
11
11
11
11
11
11
11
11
10
11
11
11
11
10
10
10
11
11
10
11
11
11
10
11
11
10
11
10
10
10
11
11
11
10
11
11
10
11
11
11
11
11
11
11
11
11
11
11
11
11
11
10
10
10
11
10
10
11
11
11
11
11
10
11
10
10
11
11
11
11
11
11
11
11
11
11
11
11
11
11
11
11
11
11
10
10
10
11
11
11
11
10
11
11
10
11
10
11
11
11
10
11
11
11
11
11
11
10
10
10
11
11
10
10
11
11
11
11
11
11
10
10
10
10
11
10
11
10
11
11
10
10
11
11
11
11
11
11
11
11
11
11
11
11
11
11
11
11
10
11
10
11
11
11
11
11
10
10
10
10
11
10
10
10
10
11
11
11
11
10
11
10
11
11
11
11
11
10
11
11
10
11
10
12
11
11
11
11
10
10
11
10
11
11
11
8
11
11
10
10
11
10
11
11
11
11
11
11
11
11
11
11
11
11
11
11
11
11
10
11
11
10
11
11
11
11
11
11
11
10
10
11
10
11
10
11
10
11
11
11
10
11
10
11
11
11
11
11
11
10
11
11
11
11
10
11
11
11
11
11
11
10
11
10
11
10
11
11
11
11
11
11
11
10
11
11
11

In [66]:
test = get_pid_info(sales_pids[0])

In [67]:
print(json.dumps(test, indent=4))

{
    "items": [
        {
            "type": "report",
            "title": "Buffalo County Assessor",
            "template": "DefaultStyleTemplate",
            "format": {},
            "items": [
                {
                    "type": "table",
                    "title": "Parcel Information",
                    "formtype": "normal",
                    "HeaderFormat": "background-color: Black !important;",
                    "items": [
                        {
                            "type": "field",
                            "title": "Parcel ID:",
                            "formtype": "",
                            "HeaderFormat": "",
                            "items": [
                                "530033429"
                            ]
                        },
                        {
                            "type": "field",
                            "title": "Map Number",
                            "formtype": "",
                            "HeaderFormat": "",
                            "items": [
                                ""
                            ]
                        },
                        {
                            "type": "field",
                            "title": "State Geo Code",
                            "formtype": "",
                            "HeaderFormat": "",
                            "items": [
                                "2809-00-0-30013-001-0014"
                            ]
                        },
                        {
                            "type": "field",
                            "title": "Cadastral #",
                            "formtype": "",
                            "HeaderFormat": "",
                            "items": [
                                ""
                            ]
                        },
                        {
                            "type": "field",
                            "title": "Images",
                            "formtype": "",
                            "HeaderFormat": "",
                            "items": [
                                "  <a target='_blank' href = 'https://kimball.gworks.com/photos/0530033429_1.jpg' >Photo #1</a>  <a target='_blank' href = 'https://kimball.gworks.com/photos/0530033429_8.jpg' >Photo #2</a>  <a target='_blank' href = 'https://kimball.gworks.com/photos/0530033429_2.jpg' >Photo #3</a>  <a target='_blank' href = 'https://kimball.gworks.com/photos/0530033429_3.jpg' >Photo #4</a>  <a target='_blank' href = 'https://kimball.gworks.com/photos/0530033429_4.jpg' >Photo #5</a>  <a target='_blank' href = 'https://kimball.gworks.com/photos/0530033429_5.jpg' >Photo #6</a>  <a target='_blank' href = 'https://kimball.gworks.com/photos/0530033429_6.jpg' >Photo #7</a>  <a target='_blank' href = 'https://kimball.gworks.com/photos/0530033429_9.jpg' >Photo #8</a>  <a target='_blank' href = 'https://kimball.gworks.com/photos/0530033429_10.jpg' >Photo #9</a>  <a target='_blank' href = 'https://kimball.gworks.com/photos/0530033429_11.jpg' >Photo #10</a>  <a target='_blank' href = 'https://kimball.gworks.com/photos/0530033429_12.jpg' >Photo #11</a>  <a target='_blank' href = 'https://kimball.gworks.com/photos/0530033429_7.jpg' >Sketch #1</a>",
                                "",
                                ""
                            ]
                        },
                        {
                            "type": "field",
                            "title": "Current Owner:",
                            "formtype": "",
                            "HeaderFormat": "",
                            "items": [
                                "PICKERING/SHARON JUNE \r14 DOWD CT\rKIMBALL, NE  69145"
                            ]
                        },
                        {
                            "type": "field",
                            "title": "Situs Address:",
                            "formtype": "",
                            "HeaderFormat": "",
                            "items": [
                                "14  DOWD COURT KIMBALL"
                            ]
                        },
                        {
                            "type": "field",
                            "title": "Tax District:",
                            "formtype": "",
                            "HeaderFormat": "",
                            "items": [
                                "40"
                            ]
                        },
                        {
                            "type": "field",
                            "title": "School District:",
                            "formtype": "",
                            "HeaderFormat": "",
                            "items": [
                                "KIMBALL #1, 53-0001"
                            ]
                        },
                        {
                            "type": "field",
                            "title": "Account Type:",
                            "formtype": "",
                            "HeaderFormat": "",
                            "items": [
                                "Residential"
                            ]
                        },
                        {
                            "type": "field",
                            "title": "Legal Description:",
                            "formtype": "",
                            "HeaderFormat": "",
                            "items": [
                                "DOWD'S SECOND ADD. BLOCK - LOT 14 (CARD #14)** 14 DOWD COURT"
                            ]
                        },
                        {
                            "type": "field",
                            "title": "Lot Width:",
                            "formtype": "",
                            "HeaderFormat": "",
                            "items": [
                                "N/A"
                            ]
                        },
                        {
                            "type": "field",
                            "title": "Lot Depth:",
                            "formtype": "",
                            "HeaderFormat": "",
                            "items": [
                                "N/A"
                            ]
                        },
                        {
                            "type": "field",
                            "title": "Total Lot Size:",
                            "formtype": "",
                            "HeaderFormat": "",
                            "items": [
                                "9344.40 sq ft"
                            ]
                        }
                    ]
                },
                {
                    "type": "table",
                    "title": "Assessed Values",
                    "formtype": "list",
                    "HeaderFormat": "background-color: Black !important;",
                    "items": [
                        {
                            "type": "field",
                            "title": "Year",
                            "formtype": "list",
                            "HeaderFormat": "",
                            "items": [
                                "2023",
                                "2022"
                            ]
                        },
                        {
                            "type": "field",
                            "title": "Total",
                            "formtype": "list",
                            "HeaderFormat": "",
                            "items": [
                                "$142,110",
                                "$127,055"
                            ]
                        },
                        {
                            "type": "field",
                            "title": "Land",
                            "formtype": "list",
                            "HeaderFormat": "",
                            "items": [
                                "$11,090",
                                "$9,065"
                            ]
                        },
                        {
                            "type": "field",
                            "title": "Outbuilding",
                            "formtype": "list",
                            "HeaderFormat": "",
                            "items": [
                                "$31,610",
                                "$26,480"
                            ]
                        },
                        {
                            "type": "field",
                            "title": "Dwelling",
                            "formtype": "list",
                            "HeaderFormat": "",
                            "items": [
                                "$99,410",
                                "$91,510"
                            ]
                        }
                    ]
                },
                {
                    "type": "table",
                    "title": "Yearly Tax Information",
                    "formtype": "list",
                    "HeaderFormat": "background-color: Black !important;",
                    "items": [
                        {
                            "type": "field",
                            "title": "Year",
                            "formtype": "list",
                            "HeaderFormat": "",
                            "items": [
                                "2023"
                            ]
                        },
                        {
                            "type": "field",
                            "title": "Amount",
                            "formtype": "list",
                            "HeaderFormat": "",
                            "items": [
                                "$2,626.24"
                            ]
                        },
                        {
                            "type": "field",
                            "title": "Levy",
                            "formtype": "list",
                            "HeaderFormat": "",
                            "items": [
                                "1.959336"
                            ]
                        }
                    ]
                },
                {
                    "type": "table",
                    "title": "2023 Tax Levy",
                    "formtype": "list",
                    "HeaderFormat": "background-color: Black !important;",
                    "items": [
                        {
                            "type": "field",
                            "title": "Description ",
                            "formtype": "list",
                            "HeaderFormat": "",
                            "items": [
                                "COUNTY GENERAL",
                                "KIMBALL #1",
                                "WNCC",
                                "ESU #13",
                                "HISTORICAL SOCIETY",
                                "AG SOCIETY",
                                "KIMBALL AIRPORT GENERAL",
                                "KIMBALL CITY BOND",
                                "S.P.N.R.D",
                                "KIMBALL CITY GENERAL",
                                "KIMBALL AIRPORT BOND"
                            ]
                        },
                        {
                            "type": "field",
                            "title": "Rate",
                            "formtype": "list",
                            "HeaderFormat": "",
                            "items": [
                                "0.47937200",
                                "0.90000000",
                                "0.09891400",
                                "0.01509400",
                                "0.00210400",
                                "0.01012800",
                                "0.01695600",
                                "0.00000000",
                                "0.04734200",
                                "0.36157200",
                                "0.02785400"
                            ]
                        }
                    ]
                },
                {
                    "type": "table",
                    "title": "Sales Information",
                    "formtype": "list",
                    "HeaderFormat": "background-color: Black !important;",
                    "items": [
                        {
                            "type": "field",
                            "title": "Sale Date",
                            "formtype": "list",
                            "HeaderFormat": "",
                            "items": [
                                "10/01/2020"
                            ]
                        },
                        {
                            "type": "field",
                            "title": "Sale Price",
                            "formtype": "list",
                            "HeaderFormat": "",
                            "items": [
                                "$100,000.00"
                            ]
                        },
                        {
                            "type": "field",
                            "title": "Book & Page",
                            "formtype": "list",
                            "HeaderFormat": "",
                            "items": [
                                "81 / 753"
                            ]
                        },
                        {
                            "type": "field",
                            "title": "Grantor",
                            "formtype": "list",
                            "HeaderFormat": "",
                            "items": [
                                "O'SHEA/KA'LANI "
                            ]
                        },
                        {
                            "type": "field",
                            "title": "Parcel Ids",
                            "formtype": "list",
                            "HeaderFormat": "",
                            "items": [
                                ""
                            ]
                        }
                    ]
                },
                {
                    "type": "table",
                    "title": "Property Classification",
                    "formtype": "doubleTable",
                    "HeaderFormat": "background-color: Black !important;",
                    "items": [
                        {
                            "type": "field",
                            "title": "Status:",
                            "formtype": "",
                            "HeaderFormat": "",
                            "items": [
                                "Improved"
                            ]
                        },
                        {
                            "type": "field",
                            "title": "Location:",
                            "formtype": "",
                            "HeaderFormat": "",
                            "items": [
                                "Urban"
                            ]
                        },
                        {
                            "type": "field",
                            "title": "Property Class:",
                            "formtype": "",
                            "HeaderFormat": "",
                            "items": [
                                "Residential"
                            ]
                        },
                        {
                            "type": "field",
                            "title": "City Size:",
                            "formtype": "",
                            "HeaderFormat": "",
                            "items": [
                                "2,501-5,000"
                            ]
                        },
                        {
                            "type": "field",
                            "title": "Zoning:",
                            "formtype": "",
                            "HeaderFormat": "",
                            "items": [
                                "Single Family"
                            ]
                        },
                        {
                            "type": "field",
                            "title": "Lot Size:",
                            "formtype": "",
                            "HeaderFormat": "",
                            "items": [
                                "<10,000 sq. ft."
                            ]
                        }
                    ]
                },
                {
                    "type": "table",
                    "title": "Land Information",
                    "formtype": "list",
                    "HeaderFormat": "background-color: Black !important;",
                    "items": [
                        {
                            "type": "field",
                            "title": "Lot Width (ft)",
                            "formtype": "list",
                            "HeaderFormat": "",
                            "items": [
                                "0.00"
                            ]
                        },
                        {
                            "type": "field",
                            "title": "Lot Depth (ft)",
                            "formtype": "list",
                            "HeaderFormat": "",
                            "items": [
                                "0.00"
                            ]
                        },
                        {
                            "type": "field",
                            "title": "Description",
                            "formtype": "list",
                            "HeaderFormat": "",
                            "items": [
                                "78 X 119.7 X 78 X 119.9 IRR"
                            ]
                        },
                        {
                            "type": "field",
                            "title": "Lot Size",
                            "formtype": "list",
                            "HeaderFormat": "",
                            "items": [
                                "9344.40 sq ft"
                            ]
                        }
                    ]
                },
                {
                    "type": "table",
                    "title": "Residential Datasheet",
                    "formtype": "doubleTable",
                    "HeaderFormat": "background-color: Black !important;",
                    "items": [
                        {
                            "type": "field",
                            "title": "Zoning:",
                            "formtype": "",
                            "HeaderFormat": "",
                            "items": [
                                "Single Family"
                            ]
                        },
                        {
                            "type": "field",
                            "title": "Condition:",
                            "formtype": "",
                            "HeaderFormat": "",
                            "items": [
                                "Average - Good"
                            ]
                        },
                        {
                            "type": "field",
                            "title": "Year Built:",
                            "formtype": "",
                            "HeaderFormat": "",
                            "items": [
                                "1960"
                            ]
                        },
                        {

In [68]:
print(len(test['items'][0]['items']))
for item in test['items'][0]['items']:
    #print(json.dumps(item,indent=4))
    print(item['title'])

11
Parcel Information
Assessed Values
Yearly Tax Information
2023 Tax Levy
Sales Information
Property Classification
Land Information
Residential Datasheet
Dwelling Data
Outbuilding Data
Photo/Sketch

In [69]:
sales_df = sales_df.drop_duplicates()
len(sales_df)

641

In [70]:
len(df)

129

In [71]:
test_df = pd.merge(sales_df, df, left_on="Parcel ID", right_on="pid", how='left')

KeyError: 'pid'

In [72]:
test_dupes = test_df[test_df.duplicated(['Sale Date', 'Parcel ID'])]
test_dupes

NameError: name 'test_df' is not defined

In [ ]:
test_df = test_df.drop_duplicates(subset=['Sale Date', 'Parcel ID'])
out_df = test_df.drop(columns=['Seller', 'Buyer', 'Assessed Value', 'pid'])
out_df.shape

In [ ]:
out_df.isna().sum()

In [ ]:
out_df = out_df.dropna()
out_df

In [ ]:
def clean_numbers(text):
    return re.sub(r'\D', '', text)

In [ ]:
size_cols = ["size", "basement_size", "garage_size"]
for col in size_cols:
    out_df[col] = out_df[col].apply(lambda x: clean_numbers(x))
    out_df[col] = out_df[col].astype(int)
out_df

In [6]:
# Unused function, developed for the sales_pids pids that were extracted from the excel spreadsheets
# The get_parcel_data function works with the json files that were scraped from the API
def get_parcel_info(pid):
    path = f"PID_Details/{pid}_detail.json"
    if os.path.exists(path):
        with open(path) as pid_file:
            [raw_text] = pid_file.readlines()
        data = json.loads(raw_text)
        parcel_data = data['items'][0]['items']
        
        # Extract 'Assessed Values' data, if present
        value_data = next((item['items'] for item in parcel_data if 'Assessed Values' in item['title']), None)
        
        assessed_value = next((v_item['items'] for v_item in value_data if 'Total' in v_item['title']), None)

        # Extract 'Sales Info' data, if present
        sales_data = next((item['items'] for item in parcel_data if 'Sales Info' in item['title']), None)
        if sales_data:
            sale_price = next((s_item['items'] for s_item in sales_data if 'Sale Price' in s_item['title']), None)
        
        # Get Residential Datasheet
        residential_data = next((item['items'] for item in parcel_data if 'Residential Datasheet' in item['title']), None)
        for x in residential_data:
            print(x)
        condition = next((r_item['items'] for r_item in residential_data if 'Condition:' in r_item['title']), None)
        year = next((r_item['items'] for r_item in residential_data if 'Year Built:' in r_item['title']), None)
        bathroom = next((r_item['items'] for r_item in residential_data if 'Bathrooms:' in r_item['title']), None)
        bedroom = next((r_item['items'] for r_item in residential_data if 'Bedrooms:' in r_item['title']), None)
        building_size = next((r_item['items'] for r_item in residential_data if 'Building Size:' in r_item['title']), None)
        basement_size = next((r_item['items'] for r_item in residential_data if 'Basement Size:' in r_item['title']), None)
        garage_size = next((r_item['items'] for r_item in residential_data if 'Garage 1 Size:' in r_item['title']), None)
        
        for x in sales_data:
            print(x)
        
        for x in residential_data:
            print(x)
        
        # Process 'Assessed Values' data
        #print(f"Assessed 2023 Value: {assessed_value[0]}")
        row = [pid, assessed_value[0], year[0], building_size[0], condition[0], bathroom[0], bedroom[0], basement_size[0], garage_size[0]]
        return row

In [7]:
# V1 of get_parcel_info
def get_parcel_info(pid):
    path = f"PID_Details/{pid}_detail.json"
    if os.path.exists(path):
        with open(path) as pid_file:
            [raw_text] = pid_file.readlines()
        data = json.loads(raw_text)
        parcel_data = data['items'][0]['items']
        for item in parcel_data:
            #print(item['title'])
            if item['title'].__contains__('Assessed Values'):
                value_data = item['items']
                for v_item in value_data:
                    print(v_item)
                    if v_item['title'].__contains__("Total"):
                        assessed_totals = v_item['items']
                        print(assessed_totals)

In [8]:
df = pd.DataFrame(columns = ['pid', 'assessed_value', 'year', 'size', 'condition', 'num_bathrooms', 'num_bedroom', 'basement_size', 'garage_size'])
for pid in sales_pids:
    try:
        row = get_parcel_info(pid)
        df.loc[len(df)] = row
    except Exception as e:
        print(e)

NameError: name 'sales_pids' is not defined

In [4]:
df = df[df.duplicated("pid", keep=False)]

NameError: name 'df' is not defined