## Housing Sale Price Predictions

### Term Project

## Lincoln Brown

## DSC550-T302

## Professor Werner

## Sales Data DataFrames

In [1]:
import pandas as pd
import os
import numpy as np
import re

In [2]:
files = os.listdir()
file_list = []
years = []
df_list = []

In [3]:
for f in files:
    if f.__contains__('Resi'):
        file_list.append(f)
        pattern = "(\d{4})-(\d{4})"
        pattern = re.compile(pattern)
        [f_years] = pattern.findall(f)
        print(f_years)
        years.append(f_years)

('2014', '2016')
('2017', '2019')
('2015', '2017')
('2018', '2020')
('2019', '2021')
('2016', '2018')
('2020', '2022')

In [4]:
df_list = []
df_14_16 = pd.read_excel(file_list[0], header=2, dtype={"Parcel ID": str})
df_list.append(df_14_16)
df_17_19 = pd.read_excel(file_list[1], header=2, dtype={"Parcel ID": str})
df_list.append(df_17_19)
df_15_17 = pd.read_excel(file_list[2], header=2, dtype={"Parcel ID": str})
df_list.append(df_15_17)
df_18_20 = pd.read_excel(file_list[3], header=2, dtype={"Parcel ID": str})
df_list.append(df_18_20)
df_19_21 = pd.read_excel(file_list[4], header=2, dtype={"Parcel ID": str})
df_list.append(df_19_21)
df_16_18 = pd.read_excel(file_list[5], header=2, dtype={"Parcel ID": str})
df_list.append(df_16_18)
df_20_22 = pd.read_excel(file_list[6], header=2, dtype={"Parcel ID": str})
df_list.append(df_20_22)

/home/x/anaconda3/lib/python3.11/site-packages/openpyxl/worksheet/header_footer.py:48: UserWarning: Cannot parse header or footer so it will be ignored
  warn("""Cannot parse header or footer so it will be ignored""")
/home/x/anaconda3/lib/python3.11/site-packages/openpyxl/worksheet/header_footer.py:48: UserWarning: Cannot parse header or footer so it will be ignored
  warn("""Cannot parse header or footer so it will be ignored""")
/home/x/anaconda3/lib/python3.11/site-packages/openpyxl/worksheet/header_footer.py:48: UserWarning: Cannot parse header or footer so it will be ignored
  warn("""Cannot parse header or footer so it will be ignored""")
/home/x/anaconda3/lib/python3.11/site-packages/openpyxl/worksheet/header_footer.py:48: UserWarning: Cannot parse header or footer so it will be ignored
  warn("""Cannot parse header or footer so it will be ignored""")

In [5]:
for df in df_list:
    display(df)

,Sale Date,Parcel ID,Seller,Buyer,LEGAL DESCRIPTION,Sale Price,Assessor Location
0,2014-10-17,530041421,Robert & Denise Waite,Preston Walls,SOUTH PARK ADD. BLOCK 3 N 1/2 OF LOT 13 AND AL...,54500.0,Kimball
1,2014-10-29,530035642,Elizabeth Shandera,Chauncey & Stephanie Pedersen,KIMBALL HEIGHTS ADD. LOT 13,140000.0,Kimball
2,2014-11-14,530032732,Wilma Vencill,Michael Mowry,CLARKSON ADD. BLOCK 10 LOT 6 AND N. 25' OF LOT 7,57000.0,Kimball
3,2014-11-14,530042800,Krissy Petersen,Roy Hammond,SUNNYVIEW HEIGHTS ADD. BLOCK 13 LOT 14,49600.0,Kimball
4,2014-11-24,530047381,Dennis & Robin McIntosh,Marc & Elizabeth Taylor,ANTELOPEVILLE ADD. BLOCK 8 W 1/2 OF LOTS8 AND 9,102000.0,Kimball
...,...,...,...,...,...,...,...
86,2015-11-05,530016818,Stanley & Beverly Pearson,Barbara Michael,TRACT 200 FEET BY 300 FEET IN THE N 1/2 OF THE...,175750.0,Rural Resi
87,2015-11-20,530151659,Lawrence & Nicole Snyder,Robert & Fawney Vincent,4.954A. TRACT IN SW1/4 30-15-56,123000.0,Rural Resi
88,2016-01-25,530028050,Whiting Oil & Gas Corp,Austin Garner,63.398 A. TRACT IN SE CORNER 10-16-58,95000.0,Rural Resi
89,2016-03-06,530029146,Daniel & Misty Curtis,Natalie & Owen Elder,LOTS 6 & 7 LESS TRACT PRAIRIE RIDGE ESTATE...,185000.0,Rural Resi
90,2016-07-25,530028522,David & Martha Cannon,Paul & Linda Piatz,19.854 ACRE TRACT IN 12-16-59,173000.0,Rural Resi

,Sale Date,Parcel ID,Seller,Buyer,LEGAL DESCRIPTION,Sale Price,Assessor Location
0,NaT,NaN,NaN,NaN,KIMBALL,NaN,NaN
1,2017-10-12,530038722,Carson R Sisk,Shelby L Widener,SOUTH PARK ADDITION BLOCK 13 LOT 9,88000.0,Kimball
2,2017-10-20,530034484,Donna L Luther,David J & Barbara A Nickel,HILLCREST FIRST ADDITION BLOCK 1 LOT 6,73500.0,Kimball
3,2017-10-26,530042738,Rhonda Green & Roger Seeman,Joshua & Bobbie J Ybarra,SUNNYVIEW HEIGHTS ADDITION BLOCK 13 S.6' OF LO...,75000.0,Kimball
4,2017-10-27,530035642,Chauncey & Stephanie Pedersen,Monica Cajero & Efrain Soto,KIMBALL HEIGHTS ADDITION - LOT 13,138000.0,Kimball
...,...,...,...,...,...,...,...
128,2018-12-07,530061201,Sam & Lovina Gingerich,Tracy & Sabine Kasten,1.82 ACRES IN N 1/2 NW 1/4 35-15-54,45000.0,Rural Resi
129,2018-12-19,530009099,Maury D & Diane B Horst,Larry & Denise Loose,20.07 ACRE TRACT IN NE 1/4 5-14-54,105000.0,Rural Resi
130,2019-03-22,530157749,David & Joanna Hottell,Liam Dunn,TRACT IN SE 1/4 OF SE 1/4 OF SW 1/W 22-13-53,125000.0,Rural Resi
131,2019-05-13,530029073,Robert Mueller,Richard R & Kelli L Patterson,LOT 1 PRAIRIE RIDGE ESTATE 17-15-55,249000.0,Rural Resi
132,2019-08-30,530017377,Darren L & Kelleigh Huff,Teresa Teppert,11.449 ACRES IN THE SE 1/4 OF THE SW 1/4 SOUTH...,157000.0,Rural Resi

,Sale Date,Parcel ID,Seller,Buyer,LEGAL DESCRIPTION,Sale Price,Assessor Location
0,2015-10-19,530035847,Donald Thompson,Carolyn & Jennette Wood,KINGSWOOD FIRST ADD. LOT 1,62000.0,Kimball
1,2015-10-26,530045036,William Loring,Aleta Lewis,BURG'S ADD. BLOCK 2 ALL OF SUBLOT 1 OF LOTS 1...,30000.0,Kimball
2,2015-10-27,530033003,William & Winifred Petersen,Matthew & Rachel Merryfield,DOWD'S FIRST ADD. BLOCK 2 LOT 1,87500.0,Kimball
3,2015-11-12,530017318,James & Charlotta Young,Jose & Fatima Lozoya,PART OF THE SW 1/4 SOUTH OF THE UPRR 28-15-55,95000.0,Kimball
4,2015-11-27,530033798,Marcelino Calderon,Daniel & Sherry Acheson,FAIRVIEW ADD. BLOCK 4 LOTS 21-22-23 AND 24,30000.0,Kimball
...,...,...,...,...,...,...,...
116,2017-08-25,530010445,Lyle & Shonna Yung,Daniel & Mercedes Arnold,PART OF S 1/2 S 1/2 6-14-55 30.012 ACRES,235000.0,Rural Resi
117,2017-09-14,530151659,Robert & Fawney Vincent,Christine & Eddie Sharkey,4.954 ACRE TRACT IN SW 1/4 30-15-56,135000.0,Rural Resi
118,NaT,NaN,NaN,NaN,NaN,NaN,NaN
119,NaT,NaN,NaN,NaN,NaN,NaN,NaN
120,NaT,NaN,,NaN,NaN,NaN,NaN

,Sale Date,Parcel ID,Seller,Buyer,LEGAL DESCRIPTION,Sale Price,Assessed Value,Assessor Location
0,NaT,NaN,NaN,NaN,KIMBALL,NaN,at time of sale,NaN
1,2018-10-16,530040824,Larry L & JoAnne M Fleagle,Christopher J Woods,ORIGINAL KIMBALL ADDITION BLOCK 21 LOTS 7 THRU 12,62000.0,40020,Kimball
2,2018-10-18,530033429,Melvin D & Sarah E Bouse,Ka'Lani O'Shea,DOWD'S SECOND ADDITION BLOCK - LOT 14,80000.0,102980,Kimball
3,2018-10-23,530036703,Patrick H Connelly,Mary Ann Felkins,LEAMINGS ADDITION BLOCK 7 LOT 1,40000.0,18875,Kimball
4,2018-10-26,530043416,Lisa A Rockhold,"Virginia K, Troy L & Julie E Davis",YANNAYON ADDITION BLOCK 2 LOT 20,75500.0,67475,Kimball
...,...,...,...,...,...,...,...,...
133,2020-02-15,530010518,Trevor L Chrystal,Michael T & Renee A Geha,1.907 ACRES IN SE CORNER OF SW 1/4 7-14-55,80000.0,74345,Rural Resi
134,2020-03-13,530021609,Scott E & Susan L Lockwood,Dalton & Ainsley Lockwood,23.147 ACRES IN 36-15-57,490000.0,300120,Rural Resi
135,2020-03-14,530029103,Douglas J & Marvel L Linthicum,Trevor L & Nicole M Anderson,LOT 3 PRAIRIE RIDGE ESTATE 17-15-55,255000.0,206040,Rural Resi
136,2020-04-01,530018365,Walter L Wann,Robert D Dunkin III,TRACT IN NE 1/4 NW 1/4 31-15-55,70000.0,87090,Rural Resi
137,2020-07-24,530050439,Dwayne A & Jonita M Groves,Bradley Ray & Nicole Lynn Hottell,12.415 ACRE TRACT IN NE 1/4 29-15-55,135000.0,197340,Rural Resi

,Sale Date,Parcel ID,Seller,Buyer,LEGAL DESCRIPTION,Sale Price,Assessed Value,Assessor Location
0,NaT,NaN,NaN,NaN,KIMBALL,NaN,at time of sale,NaN
1,2019-10-03,530042460,Kathleen P & Ricky L Chapman,Paul Richard & Rebecca Ellen Burris,SUNNYVIEW HEIGHTS ADDITION BLOCK 11 LOT 4,92500.0,71505,Kimball
2,2019-10-17,530033399,Tammy Adair,Doris F Burton,DOWD'S SECOND ADDITION BLOCK - LOT 10 AND SW 2...,147000.0,125245,Kimball
3,2019-11-06,530036754,Howard R & Shirley J Hoberg,David W & Debra A Gibson,LEAMINGS ADD BLOCK 7 LOT 6 AND THE N 1/2 OF LOT 7,89500.0,76555,Kimball
4,2019-11-07,530035448,Dan J & Cindy L Dean,Ryan M & Tiffany K Johnson,HUFF'S SECOND ADDITION BLOCK 1 S 5' OF LOT 1 A...,170000.0,175775,Kimball
...,...,...,...,...,...,...,...,...
170,2021-03-05,530010445,Daniel B Arnold,Timothy Wayne & Dixie Lee Smith,6-14-55 PART OF S1/2S1/2 6-14-55,330000.0,215195,Rural Resi
171,2021-03-25,530024640,Kathleen Atkins Trustee,Ryan Lukassen & Elyse Schlake,25-16-54 A TRACT IN THE N/2NE/4 25-16-54,265000.0,161020,Rural Resi
172,2021-05-03,530005069,Garland & Megan Hamilton,Sara Silvanage,6.502 ACRE TRACT IN NE1/4NE1/4 26-13-55,122000.0,103510,Rural Resi
173,2021-08-05,530010518,Michael T & Renee A Geha,Adam Geha,1.907 A. IN SE CORNER OF SW 1/4 7-14-55,80000.0,74345,Rural Resi
174,2021-09-28,530016818,Barbara K Michael,Carmen M Jackman,TRACT 200 FEET BY 300 FEET IN THE N 1/2 OF THE...,225000.0,156655,Rural Resi

,Sale Date,Parcel ID,Seller,Buyer,LEGAL DESCRIPTION,Sale Price,Assessor Location
0,2016-10-13,530045583,James Buckley,Scott Christensen,BURGS ADD. BLOCK 6 LOT 8,37000.0,Kimball
1,2016-10-17,530041286,Charles & Carolyn Carlson,Richard & Gloria Brookman,SOUTH PARK ADD. BLOCK 2 ALL LOT 8 AND S1/8 OF ...,150000.0,Kimball
2,2016-10-20,530035448,James Prince & Nancy Garrett,Patricia Biesecker & Deanna Bleyle,HUFFS SECOND ADD. BLOCK 1 S. 5' OF LOT 1 AND A...,120000.0,Kimball
3,2016-10-24,530032546,Claire Tritt,Ricky & Julia Gehrig,CLARKSON ADD. BLOCK 8 S. 20' OF LOT 7 AND ALL ...,83000.0,Kimball
4,2016-11-05,530045273,Jennifer Dillinger,Rachel Rowe,BURG'S ADD. BLOCK 4 ALL LOT 7 AND N 15' OF LOT 8,30000.0,Kimball
...,...,...,...,...,...,...,...
137,2018-06-15,530020696,Michael H & Karen M Isley,James N Columbia,A TRACT IN SE 1/4 28-15-56,165000.0,Rural Resi
138,2018-07-06,530031094,Karla J Jenkins,Marvin & Sandra Tabor,TRACT S OF UPRR IN SE 1/4 26-15-56,130000.0,Rural Resi
139,2018-07-18,530151470,Jared C & Melissa L Reich,Karla Jenkins,29.823 A TRACT IN NE 1/4 18-16-55,217500.0,Rural Resi
140,2018-08-01,530025779,Jeanne Anderson,Cheryl Delaplane,TRACT IN WEST PART OF NW 1/4 32-16-55,67000.0,Rural Resi
141,2018-09-14,530026937,Mary Ann Felkins,John M & Alicia I Buchart,7.015 ACRES IN THE NE 1/4 OF THE NE 1/4 OF TH ...,180000.0,Rural Resi

,Sale Date,Parcel ID,Seller,Buyer,LEGAL DESCRIPTION,Sale Price,Assessed Value,Assessor Location
0,NaT,NaN,NaN,NaN,KIMBALL,NaN,at time of sale,NaN
1,2020-10-01,530033429,Ka'Lani O'Shea,Sharon June Pickering,DOWD'S SECOND ADD. BLOCK - LOT 14 (CARD #14),100000.0,113040,Kimball
2,2020-10-01,530036932,Chico R Fernandez,Crystal Kisicki,LEAMINGS ADD. BLOCK 9 S. 39' OF THE W. 80' OF ...,38000.0,27545,Kimball
3,2020-10-06,530033488,Justin W & Jacqueline N Prather,Anthony & Linda Madrid,DOWD'S SECOND ADD. BLOCK - LOT 19,145000.0,156090,Kimball
4,2020-10-06,530039036,James & Donna Cederburg,Caleb Reuter,SOUTH PARK ADD. BLOCK 16 W. 110' OF LOT 8 & W....,47900.0,36120,Kimball
...,...,...,...,...,...,...,...,...
138,2021-09-28,530016818,Barbara K Michael,Carmen M Jackman,TRACT 200 FEET BY 300 FEET IN THE N 1/2 OF THE...,225000.0,156655,Rural Resi
139,2022-04-11,530015951,Sammie M & Lovina Gingerich,Sammie & Talia L Gingerich,23.540 ACRES IN SE 1/4 S. OF UPRR 29-15-54,167000.0,190030,Rural Resi
140,2022-04-28,530020041,Michael A & Clara Sue Salazar,Matthew & Crystal Brown,TAX LOT 14 MORGAN'S SUBDIVISION IN E 1/2 OF SW...,305000.0,150090,Rural Resi
141,2022-05-11,530151785,Jean A Mueller-Yanaga,Daniel Glasgow,TRACT IN SE 1/4 AND E 1/2 NE 1/4 SW 1/4 33-15-55,190000.0,96960,Rural Resi
142,2022-07-07,530023288,Central Properties,"Adair Holdings, LLC",9.883 ACRE TRACT IN N 1/2 N 1/2 6-16-53,126185.0,126185,Rural Resi

In [6]:
cleaned_dfs = []
for df in df_list:
    nas = df.loc[df.isna().any(axis=1), :]
    #display(nas)
    cleaned_dfs.append(df.loc[~df.isna().any(axis=1),:])
    display(df.loc[~df.isna().any(axis=1),:])

,Sale Date,Parcel ID,Seller,Buyer,LEGAL DESCRIPTION,Sale Price,Assessor Location
0,2014-10-17,530041421,Robert & Denise Waite,Preston Walls,SOUTH PARK ADD. BLOCK 3 N 1/2 OF LOT 13 AND AL...,54500.0,Kimball
1,2014-10-29,530035642,Elizabeth Shandera,Chauncey & Stephanie Pedersen,KIMBALL HEIGHTS ADD. LOT 13,140000.0,Kimball
2,2014-11-14,530032732,Wilma Vencill,Michael Mowry,CLARKSON ADD. BLOCK 10 LOT 6 AND N. 25' OF LOT 7,57000.0,Kimball
3,2014-11-14,530042800,Krissy Petersen,Roy Hammond,SUNNYVIEW HEIGHTS ADD. BLOCK 13 LOT 14,49600.0,Kimball
4,2014-11-24,530047381,Dennis & Robin McIntosh,Marc & Elizabeth Taylor,ANTELOPEVILLE ADD. BLOCK 8 W 1/2 OF LOTS8 AND 9,102000.0,Kimball
...,...,...,...,...,...,...,...
86,2015-11-05,530016818,Stanley & Beverly Pearson,Barbara Michael,TRACT 200 FEET BY 300 FEET IN THE N 1/2 OF THE...,175750.0,Rural Resi
87,2015-11-20,530151659,Lawrence & Nicole Snyder,Robert & Fawney Vincent,4.954A. TRACT IN SW1/4 30-15-56,123000.0,Rural Resi
88,2016-01-25,530028050,Whiting Oil & Gas Corp,Austin Garner,63.398 A. TRACT IN SE CORNER 10-16-58,95000.0,Rural Resi
89,2016-03-06,530029146,Daniel & Misty Curtis,Natalie & Owen Elder,LOTS 6 & 7 LESS TRACT PRAIRIE RIDGE ESTATE...,185000.0,Rural Resi
90,2016-07-25,530028522,David & Martha Cannon,Paul & Linda Piatz,19.854 ACRE TRACT IN 12-16-59,173000.0,Rural Resi

,Sale Date,Parcel ID,Seller,Buyer,LEGAL DESCRIPTION,Sale Price,Assessor Location
1,2017-10-12,530038722,Carson R Sisk,Shelby L Widener,SOUTH PARK ADDITION BLOCK 13 LOT 9,88000.0,Kimball
2,2017-10-20,530034484,Donna L Luther,David J & Barbara A Nickel,HILLCREST FIRST ADDITION BLOCK 1 LOT 6,73500.0,Kimball
3,2017-10-26,530042738,Rhonda Green & Roger Seeman,Joshua & Bobbie J Ybarra,SUNNYVIEW HEIGHTS ADDITION BLOCK 13 S.6' OF LO...,75000.0,Kimball
4,2017-10-27,530035642,Chauncey & Stephanie Pedersen,Monica Cajero & Efrain Soto,KIMBALL HEIGHTS ADDITION - LOT 13,138000.0,Kimball
5,2017-10-27,530034735,Irene J Wallin,Bernardo & Mercedes Quinones,HILLCREST SECOND ADDITION BLOCK 2 LOT 4,55000.0,Kimball
...,...,...,...,...,...,...,...
128,2018-12-07,530061201,Sam & Lovina Gingerich,Tracy & Sabine Kasten,1.82 ACRES IN N 1/2 NW 1/4 35-15-54,45000.0,Rural Resi
129,2018-12-19,530009099,Maury D & Diane B Horst,Larry & Denise Loose,20.07 ACRE TRACT IN NE 1/4 5-14-54,105000.0,Rural Resi
130,2019-03-22,530157749,David & Joanna Hottell,Liam Dunn,TRACT IN SE 1/4 OF SE 1/4 OF SW 1/W 22-13-53,125000.0,Rural Resi
131,2019-05-13,530029073,Robert Mueller,Richard R & Kelli L Patterson,LOT 1 PRAIRIE RIDGE ESTATE 17-15-55,249000.0,Rural Resi
132,2019-08-30,530017377,Darren L & Kelleigh Huff,Teresa Teppert,11.449 ACRES IN THE SE 1/4 OF THE SW 1/4 SOUTH...,157000.0,Rural Resi

,Sale Date,Parcel ID,Seller,Buyer,LEGAL DESCRIPTION,Sale Price,Assessor Location
0,2015-10-19,530035847,Donald Thompson,Carolyn & Jennette Wood,KINGSWOOD FIRST ADD. LOT 1,62000.0,Kimball
1,2015-10-26,530045036,William Loring,Aleta Lewis,BURG'S ADD. BLOCK 2 ALL OF SUBLOT 1 OF LOTS 1...,30000.0,Kimball
2,2015-10-27,530033003,William & Winifred Petersen,Matthew & Rachel Merryfield,DOWD'S FIRST ADD. BLOCK 2 LOT 1,87500.0,Kimball
3,2015-11-12,530017318,James & Charlotta Young,Jose & Fatima Lozoya,PART OF THE SW 1/4 SOUTH OF THE UPRR 28-15-55,95000.0,Kimball
4,2015-11-27,530033798,Marcelino Calderon,Daniel & Sherry Acheson,FAIRVIEW ADD. BLOCK 4 LOTS 21-22-23 AND 24,30000.0,Kimball
...,...,...,...,...,...,...,...
113,2017-04-24,530009285,Monica & Magdaleno Cajero,Donald Weeks,TRACT IN E 1/2 NE 1/4 OF 10-14-54 (26.849 ACRES),135000.0,Rural Resi
114,2017-06-16,530020173,Kristi & Ronald Cortney,Toni & Edward Barnes,TAX LOT 8 PART OF SE 1/4 OF THE NW 1/4 & NE 1/...,150499.0,Rural Resi
115,2017-07-12,530020041,Jason Hottell,Robin Whitehead,TAX LOT 14 MORGANS SUBDIVISION IN E 1/2 OF SW ...,187000.0,Rural Resi
116,2017-08-25,530010445,Lyle & Shonna Yung,Daniel & Mercedes Arnold,PART OF S 1/2 S 1/2 6-14-55 30.012 ACRES,235000.0,Rural Resi
117,2017-09-14,530151659,Robert & Fawney Vincent,Christine & Eddie Sharkey,4.954 ACRE TRACT IN SW 1/4 30-15-56,135000.0,Rural Resi

,Sale Date,Parcel ID,Seller,Buyer,LEGAL DESCRIPTION,Sale Price,Assessed Value,Assessor Location
1,2018-10-16,530040824,Larry L & JoAnne M Fleagle,Christopher J Woods,ORIGINAL KIMBALL ADDITION BLOCK 21 LOTS 7 THRU 12,62000.0,40020,Kimball
2,2018-10-18,530033429,Melvin D & Sarah E Bouse,Ka'Lani O'Shea,DOWD'S SECOND ADDITION BLOCK - LOT 14,80000.0,102980,Kimball
3,2018-10-23,530036703,Patrick H Connelly,Mary Ann Felkins,LEAMINGS ADDITION BLOCK 7 LOT 1,40000.0,18875,Kimball
4,2018-10-26,530043416,Lisa A Rockhold,"Virginia K, Troy L & Julie E Davis",YANNAYON ADDITION BLOCK 2 LOT 20,75500.0,67475,Kimball
5,2018-12-14,530035626,Kenneth H & Cynthia Stone Hunter,Ty M & Jessica S Gibson,KIMBALL HEIGHTS ADDITION N. 23' OF LOT 9 AND A...,189000.0,171090,Kimball
...,...,...,...,...,...,...,...,...
133,2020-02-15,530010518,Trevor L Chrystal,Michael T & Renee A Geha,1.907 ACRES IN SE CORNER OF SW 1/4 7-14-55,80000.0,74345,Rural Resi
134,2020-03-13,530021609,Scott E & Susan L Lockwood,Dalton & Ainsley Lockwood,23.147 ACRES IN 36-15-57,490000.0,300120,Rural Resi
135,2020-03-14,530029103,Douglas J & Marvel L Linthicum,Trevor L & Nicole M Anderson,LOT 3 PRAIRIE RIDGE ESTATE 17-15-55,255000.0,206040,Rural Resi
136,2020-04-01,530018365,Walter L Wann,Robert D Dunkin III,TRACT IN NE 1/4 NW 1/4 31-15-55,70000.0,87090,Rural Resi
137,2020-07-24,530050439,Dwayne A & Jonita M Groves,Bradley Ray & Nicole Lynn Hottell,12.415 ACRE TRACT IN NE 1/4 29-15-55,135000.0,197340,Rural Resi

,Sale Date,Parcel ID,Seller,Buyer,LEGAL DESCRIPTION,Sale Price,Assessed Value,Assessor Location
1,2019-10-03,530042460,Kathleen P & Ricky L Chapman,Paul Richard & Rebecca Ellen Burris,SUNNYVIEW HEIGHTS ADDITION BLOCK 11 LOT 4,92500.0,71505,Kimball
2,2019-10-17,530033399,Tammy Adair,Doris F Burton,DOWD'S SECOND ADDITION BLOCK - LOT 10 AND SW 2...,147000.0,125245,Kimball
3,2019-11-06,530036754,Howard R & Shirley J Hoberg,David W & Debra A Gibson,LEAMINGS ADD BLOCK 7 LOT 6 AND THE N 1/2 OF LOT 7,89500.0,76555,Kimball
4,2019-11-07,530035448,Dan J & Cindy L Dean,Ryan M & Tiffany K Johnson,HUFF'S SECOND ADDITION BLOCK 1 S 5' OF LOT 1 A...,170000.0,175775,Kimball
5,2019-11-11,530038803,Diana K Fiehtner,Frank & Norma Stauffer,SOUTH PARK ADDITION BLOCK 14 W 80' OF LOTS 1-3...,60000.0,53015,Kimball
...,...,...,...,...,...,...,...,...
170,2021-03-05,530010445,Daniel B Arnold,Timothy Wayne & Dixie Lee Smith,6-14-55 PART OF S1/2S1/2 6-14-55,330000.0,215195,Rural Resi
171,2021-03-25,530024640,Kathleen Atkins Trustee,Ryan Lukassen & Elyse Schlake,25-16-54 A TRACT IN THE N/2NE/4 25-16-54,265000.0,161020,Rural Resi
172,2021-05-03,530005069,Garland & Megan Hamilton,Sara Silvanage,6.502 ACRE TRACT IN NE1/4NE1/4 26-13-55,122000.0,103510,Rural Resi
173,2021-08-05,530010518,Michael T & Renee A Geha,Adam Geha,1.907 A. IN SE CORNER OF SW 1/4 7-14-55,80000.0,74345,Rural Resi
174,2021-09-28,530016818,Barbara K Michael,Carmen M Jackman,TRACT 200 FEET BY 300 FEET IN THE N 1/2 OF THE...,225000.0,156655,Rural Resi

,Sale Date,Parcel ID,Seller,Buyer,LEGAL DESCRIPTION,Sale Price,Assessor Location
0,2016-10-13,530045583,James Buckley,Scott Christensen,BURGS ADD. BLOCK 6 LOT 8,37000.0,Kimball
1,2016-10-17,530041286,Charles & Carolyn Carlson,Richard & Gloria Brookman,SOUTH PARK ADD. BLOCK 2 ALL LOT 8 AND S1/8 OF ...,150000.0,Kimball
2,2016-10-20,530035448,James Prince & Nancy Garrett,Patricia Biesecker & Deanna Bleyle,HUFFS SECOND ADD. BLOCK 1 S. 5' OF LOT 1 AND A...,120000.0,Kimball
3,2016-10-24,530032546,Claire Tritt,Ricky & Julia Gehrig,CLARKSON ADD. BLOCK 8 S. 20' OF LOT 7 AND ALL ...,83000.0,Kimball
4,2016-11-05,530045273,Jennifer Dillinger,Rachel Rowe,BURG'S ADD. BLOCK 4 ALL LOT 7 AND N 15' OF LOT 8,30000.0,Kimball
...,...,...,...,...,...,...,...
137,2018-06-15,530020696,Michael H & Karen M Isley,James N Columbia,A TRACT IN SE 1/4 28-15-56,165000.0,Rural Resi
138,2018-07-06,530031094,Karla J Jenkins,Marvin & Sandra Tabor,TRACT S OF UPRR IN SE 1/4 26-15-56,130000.0,Rural Resi
139,2018-07-18,530151470,Jared C & Melissa L Reich,Karla Jenkins,29.823 A TRACT IN NE 1/4 18-16-55,217500.0,Rural Resi
140,2018-08-01,530025779,Jeanne Anderson,Cheryl Delaplane,TRACT IN WEST PART OF NW 1/4 32-16-55,67000.0,Rural Resi
141,2018-09-14,530026937,Mary Ann Felkins,John M & Alicia I Buchart,7.015 ACRES IN THE NE 1/4 OF THE NE 1/4 OF TH ...,180000.0,Rural Resi

,Sale Date,Parcel ID,Seller,Buyer,LEGAL DESCRIPTION,Sale Price,Assessed Value,Assessor Location
1,2020-10-01,530033429,Ka'Lani O'Shea,Sharon June Pickering,DOWD'S SECOND ADD. BLOCK - LOT 14 (CARD #14),100000.0,113040,Kimball
2,2020-10-01,530036932,Chico R Fernandez,Crystal Kisicki,LEAMINGS ADD. BLOCK 9 S. 39' OF THE W. 80' OF ...,38000.0,27545,Kimball
3,2020-10-06,530033488,Justin W & Jacqueline N Prather,Anthony & Linda Madrid,DOWD'S SECOND ADD. BLOCK - LOT 19,145000.0,156090,Kimball
4,2020-10-06,530039036,James & Donna Cederburg,Caleb Reuter,SOUTH PARK ADD. BLOCK 16 W. 110' OF LOT 8 & W....,47900.0,36120,Kimball
5,2020-10-20,530042959,Carol L Meyer,Danny E Yung,SUNNYVIEW HEIGHTS ADD. BLOCK 14 N. 5' OF LOT 1...,71100.0,82945,Kimball
...,...,...,...,...,...,...,...,...
138,2021-09-28,530016818,Barbara K Michael,Carmen M Jackman,TRACT 200 FEET BY 300 FEET IN THE N 1/2 OF THE...,225000.0,156655,Rural Resi
139,2022-04-11,530015951,Sammie M & Lovina Gingerich,Sammie & Talia L Gingerich,23.540 ACRES IN SE 1/4 S. OF UPRR 29-15-54,167000.0,190030,Rural Resi
140,2022-04-28,530020041,Michael A & Clara Sue Salazar,Matthew & Crystal Brown,TAX LOT 14 MORGAN'S SUBDIVISION IN E 1/2 OF SW...,305000.0,150090,Rural Resi
141,2022-05-11,530151785,Jean A Mueller-Yanaga,Daniel Glasgow,TRACT IN SE 1/4 AND E 1/2 NE 1/4 SW 1/4 33-15-55,190000.0,96960,Rural Resi
142,2022-07-07,530023288,Central Properties,"Adair Holdings, LLC",9.883 ACRE TRACT IN N 1/2 N 1/2 6-16-53,126185.0,126185,Rural Resi

In [7]:
for df in cleaned_dfs:
    display(df)

,Sale Date,Parcel ID,Seller,Buyer,LEGAL DESCRIPTION,Sale Price,Assessor Location
0,2014-10-17,530041421,Robert & Denise Waite,Preston Walls,SOUTH PARK ADD. BLOCK 3 N 1/2 OF LOT 13 AND AL...,54500.0,Kimball
1,2014-10-29,530035642,Elizabeth Shandera,Chauncey & Stephanie Pedersen,KIMBALL HEIGHTS ADD. LOT 13,140000.0,Kimball
2,2014-11-14,530032732,Wilma Vencill,Michael Mowry,CLARKSON ADD. BLOCK 10 LOT 6 AND N. 25' OF LOT 7,57000.0,Kimball
3,2014-11-14,530042800,Krissy Petersen,Roy Hammond,SUNNYVIEW HEIGHTS ADD. BLOCK 13 LOT 14,49600.0,Kimball
4,2014-11-24,530047381,Dennis & Robin McIntosh,Marc & Elizabeth Taylor,ANTELOPEVILLE ADD. BLOCK 8 W 1/2 OF LOTS8 AND 9,102000.0,Kimball
...,...,...,...,...,...,...,...
86,2015-11-05,530016818,Stanley & Beverly Pearson,Barbara Michael,TRACT 200 FEET BY 300 FEET IN THE N 1/2 OF THE...,175750.0,Rural Resi
87,2015-11-20,530151659,Lawrence & Nicole Snyder,Robert & Fawney Vincent,4.954A. TRACT IN SW1/4 30-15-56,123000.0,Rural Resi
88,2016-01-25,530028050,Whiting Oil & Gas Corp,Austin Garner,63.398 A. TRACT IN SE CORNER 10-16-58,95000.0,Rural Resi
89,2016-03-06,530029146,Daniel & Misty Curtis,Natalie & Owen Elder,LOTS 6 & 7 LESS TRACT PRAIRIE RIDGE ESTATE...,185000.0,Rural Resi
90,2016-07-25,530028522,David & Martha Cannon,Paul & Linda Piatz,19.854 ACRE TRACT IN 12-16-59,173000.0,Rural Resi

,Sale Date,Parcel ID,Seller,Buyer,LEGAL DESCRIPTION,Sale Price,Assessor Location
1,2017-10-12,530038722,Carson R Sisk,Shelby L Widener,SOUTH PARK ADDITION BLOCK 13 LOT 9,88000.0,Kimball
2,2017-10-20,530034484,Donna L Luther,David J & Barbara A Nickel,HILLCREST FIRST ADDITION BLOCK 1 LOT 6,73500.0,Kimball
3,2017-10-26,530042738,Rhonda Green & Roger Seeman,Joshua & Bobbie J Ybarra,SUNNYVIEW HEIGHTS ADDITION BLOCK 13 S.6' OF LO...,75000.0,Kimball
4,2017-10-27,530035642,Chauncey & Stephanie Pedersen,Monica Cajero & Efrain Soto,KIMBALL HEIGHTS ADDITION - LOT 13,138000.0,Kimball
5,2017-10-27,530034735,Irene J Wallin,Bernardo & Mercedes Quinones,HILLCREST SECOND ADDITION BLOCK 2 LOT 4,55000.0,Kimball
...,...,...,...,...,...,...,...
128,2018-12-07,530061201,Sam & Lovina Gingerich,Tracy & Sabine Kasten,1.82 ACRES IN N 1/2 NW 1/4 35-15-54,45000.0,Rural Resi
129,2018-12-19,530009099,Maury D & Diane B Horst,Larry & Denise Loose,20.07 ACRE TRACT IN NE 1/4 5-14-54,105000.0,Rural Resi
130,2019-03-22,530157749,David & Joanna Hottell,Liam Dunn,TRACT IN SE 1/4 OF SE 1/4 OF SW 1/W 22-13-53,125000.0,Rural Resi
131,2019-05-13,530029073,Robert Mueller,Richard R & Kelli L Patterson,LOT 1 PRAIRIE RIDGE ESTATE 17-15-55,249000.0,Rural Resi
132,2019-08-30,530017377,Darren L & Kelleigh Huff,Teresa Teppert,11.449 ACRES IN THE SE 1/4 OF THE SW 1/4 SOUTH...,157000.0,Rural Resi

,Sale Date,Parcel ID,Seller,Buyer,LEGAL DESCRIPTION,Sale Price,Assessor Location
0,2015-10-19,530035847,Donald Thompson,Carolyn & Jennette Wood,KINGSWOOD FIRST ADD. LOT 1,62000.0,Kimball
1,2015-10-26,530045036,William Loring,Aleta Lewis,BURG'S ADD. BLOCK 2 ALL OF SUBLOT 1 OF LOTS 1...,30000.0,Kimball
2,2015-10-27,530033003,William & Winifred Petersen,Matthew & Rachel Merryfield,DOWD'S FIRST ADD. BLOCK 2 LOT 1,87500.0,Kimball
3,2015-11-12,530017318,James & Charlotta Young,Jose & Fatima Lozoya,PART OF THE SW 1/4 SOUTH OF THE UPRR 28-15-55,95000.0,Kimball
4,2015-11-27,530033798,Marcelino Calderon,Daniel & Sherry Acheson,FAIRVIEW ADD. BLOCK 4 LOTS 21-22-23 AND 24,30000.0,Kimball
...,...,...,...,...,...,...,...
113,2017-04-24,530009285,Monica & Magdaleno Cajero,Donald Weeks,TRACT IN E 1/2 NE 1/4 OF 10-14-54 (26.849 ACRES),135000.0,Rural Resi
114,2017-06-16,530020173,Kristi & Ronald Cortney,Toni & Edward Barnes,TAX LOT 8 PART OF SE 1/4 OF THE NW 1/4 & NE 1/...,150499.0,Rural Resi
115,2017-07-12,530020041,Jason Hottell,Robin Whitehead,TAX LOT 14 MORGANS SUBDIVISION IN E 1/2 OF SW ...,187000.0,Rural Resi
116,2017-08-25,530010445,Lyle & Shonna Yung,Daniel & Mercedes Arnold,PART OF S 1/2 S 1/2 6-14-55 30.012 ACRES,235000.0,Rural Resi
117,2017-09-14,530151659,Robert & Fawney Vincent,Christine & Eddie Sharkey,4.954 ACRE TRACT IN SW 1/4 30-15-56,135000.0,Rural Resi

,Sale Date,Parcel ID,Seller,Buyer,LEGAL DESCRIPTION,Sale Price,Assessed Value,Assessor Location
1,2018-10-16,530040824,Larry L & JoAnne M Fleagle,Christopher J Woods,ORIGINAL KIMBALL ADDITION BLOCK 21 LOTS 7 THRU 12,62000.0,40020,Kimball
2,2018-10-18,530033429,Melvin D & Sarah E Bouse,Ka'Lani O'Shea,DOWD'S SECOND ADDITION BLOCK - LOT 14,80000.0,102980,Kimball
3,2018-10-23,530036703,Patrick H Connelly,Mary Ann Felkins,LEAMINGS ADDITION BLOCK 7 LOT 1,40000.0,18875,Kimball
4,2018-10-26,530043416,Lisa A Rockhold,"Virginia K, Troy L & Julie E Davis",YANNAYON ADDITION BLOCK 2 LOT 20,75500.0,67475,Kimball
5,2018-12-14,530035626,Kenneth H & Cynthia Stone Hunter,Ty M & Jessica S Gibson,KIMBALL HEIGHTS ADDITION N. 23' OF LOT 9 AND A...,189000.0,171090,Kimball
...,...,...,...,...,...,...,...,...
133,2020-02-15,530010518,Trevor L Chrystal,Michael T & Renee A Geha,1.907 ACRES IN SE CORNER OF SW 1/4 7-14-55,80000.0,74345,Rural Resi
134,2020-03-13,530021609,Scott E & Susan L Lockwood,Dalton & Ainsley Lockwood,23.147 ACRES IN 36-15-57,490000.0,300120,Rural Resi
135,2020-03-14,530029103,Douglas J & Marvel L Linthicum,Trevor L & Nicole M Anderson,LOT 3 PRAIRIE RIDGE ESTATE 17-15-55,255000.0,206040,Rural Resi
136,2020-04-01,530018365,Walter L Wann,Robert D Dunkin III,TRACT IN NE 1/4 NW 1/4 31-15-55,70000.0,87090,Rural Resi
137,2020-07-24,530050439,Dwayne A & Jonita M Groves,Bradley Ray & Nicole Lynn Hottell,12.415 ACRE TRACT IN NE 1/4 29-15-55,135000.0,197340,Rural Resi

,Sale Date,Parcel ID,Seller,Buyer,LEGAL DESCRIPTION,Sale Price,Assessed Value,Assessor Location
1,2019-10-03,530042460,Kathleen P & Ricky L Chapman,Paul Richard & Rebecca Ellen Burris,SUNNYVIEW HEIGHTS ADDITION BLOCK 11 LOT 4,92500.0,71505,Kimball
2,2019-10-17,530033399,Tammy Adair,Doris F Burton,DOWD'S SECOND ADDITION BLOCK - LOT 10 AND SW 2...,147000.0,125245,Kimball
3,2019-11-06,530036754,Howard R & Shirley J Hoberg,David W & Debra A Gibson,LEAMINGS ADD BLOCK 7 LOT 6 AND THE N 1/2 OF LOT 7,89500.0,76555,Kimball
4,2019-11-07,530035448,Dan J & Cindy L Dean,Ryan M & Tiffany K Johnson,HUFF'S SECOND ADDITION BLOCK 1 S 5' OF LOT 1 A...,170000.0,175775,Kimball
5,2019-11-11,530038803,Diana K Fiehtner,Frank & Norma Stauffer,SOUTH PARK ADDITION BLOCK 14 W 80' OF LOTS 1-3...,60000.0,53015,Kimball
...,...,...,...,...,...,...,...,...
170,2021-03-05,530010445,Daniel B Arnold,Timothy Wayne & Dixie Lee Smith,6-14-55 PART OF S1/2S1/2 6-14-55,330000.0,215195,Rural Resi
171,2021-03-25,530024640,Kathleen Atkins Trustee,Ryan Lukassen & Elyse Schlake,25-16-54 A TRACT IN THE N/2NE/4 25-16-54,265000.0,161020,Rural Resi
172,2021-05-03,530005069,Garland & Megan Hamilton,Sara Silvanage,6.502 ACRE TRACT IN NE1/4NE1/4 26-13-55,122000.0,103510,Rural Resi
173,2021-08-05,530010518,Michael T & Renee A Geha,Adam Geha,1.907 A. IN SE CORNER OF SW 1/4 7-14-55,80000.0,74345,Rural Resi
174,2021-09-28,530016818,Barbara K Michael,Carmen M Jackman,TRACT 200 FEET BY 300 FEET IN THE N 1/2 OF THE...,225000.0,156655,Rural Resi

,Sale Date,Parcel ID,Seller,Buyer,LEGAL DESCRIPTION,Sale Price,Assessor Location
0,2016-10-13,530045583,James Buckley,Scott Christensen,BURGS ADD. BLOCK 6 LOT 8,37000.0,Kimball
1,2016-10-17,530041286,Charles & Carolyn Carlson,Richard & Gloria Brookman,SOUTH PARK ADD. BLOCK 2 ALL LOT 8 AND S1/8 OF ...,150000.0,Kimball
2,2016-10-20,530035448,James Prince & Nancy Garrett,Patricia Biesecker & Deanna Bleyle,HUFFS SECOND ADD. BLOCK 1 S. 5' OF LOT 1 AND A...,120000.0,Kimball
3,2016-10-24,530032546,Claire Tritt,Ricky & Julia Gehrig,CLARKSON ADD. BLOCK 8 S. 20' OF LOT 7 AND ALL ...,83000.0,Kimball
4,2016-11-05,530045273,Jennifer Dillinger,Rachel Rowe,BURG'S ADD. BLOCK 4 ALL LOT 7 AND N 15' OF LOT 8,30000.0,Kimball
...,...,...,...,...,...,...,...
137,2018-06-15,530020696,Michael H & Karen M Isley,James N Columbia,A TRACT IN SE 1/4 28-15-56,165000.0,Rural Resi
138,2018-07-06,530031094,Karla J Jenkins,Marvin & Sandra Tabor,TRACT S OF UPRR IN SE 1/4 26-15-56,130000.0,Rural Resi
139,2018-07-18,530151470,Jared C & Melissa L Reich,Karla Jenkins,29.823 A TRACT IN NE 1/4 18-16-55,217500.0,Rural Resi
140,2018-08-01,530025779,Jeanne Anderson,Cheryl Delaplane,TRACT IN WEST PART OF NW 1/4 32-16-55,67000.0,Rural Resi
141,2018-09-14,530026937,Mary Ann Felkins,John M & Alicia I Buchart,7.015 ACRES IN THE NE 1/4 OF THE NE 1/4 OF TH ...,180000.0,Rural Resi

,Sale Date,Parcel ID,Seller,Buyer,LEGAL DESCRIPTION,Sale Price,Assessed Value,Assessor Location
1,2020-10-01,530033429,Ka'Lani O'Shea,Sharon June Pickering,DOWD'S SECOND ADD. BLOCK - LOT 14 (CARD #14),100000.0,113040,Kimball
2,2020-10-01,530036932,Chico R Fernandez,Crystal Kisicki,LEAMINGS ADD. BLOCK 9 S. 39' OF THE W. 80' OF ...,38000.0,27545,Kimball
3,2020-10-06,530033488,Justin W & Jacqueline N Prather,Anthony & Linda Madrid,DOWD'S SECOND ADD. BLOCK - LOT 19,145000.0,156090,Kimball
4,2020-10-06,530039036,James & Donna Cederburg,Caleb Reuter,SOUTH PARK ADD. BLOCK 16 W. 110' OF LOT 8 & W....,47900.0,36120,Kimball
5,2020-10-20,530042959,Carol L Meyer,Danny E Yung,SUNNYVIEW HEIGHTS ADD. BLOCK 14 N. 5' OF LOT 1...,71100.0,82945,Kimball
...,...,...,...,...,...,...,...,...
138,2021-09-28,530016818,Barbara K Michael,Carmen M Jackman,TRACT 200 FEET BY 300 FEET IN THE N 1/2 OF THE...,225000.0,156655,Rural Resi
139,2022-04-11,530015951,Sammie M & Lovina Gingerich,Sammie & Talia L Gingerich,23.540 ACRES IN SE 1/4 S. OF UPRR 29-15-54,167000.0,190030,Rural Resi
140,2022-04-28,530020041,Michael A & Clara Sue Salazar,Matthew & Crystal Brown,TAX LOT 14 MORGAN'S SUBDIVISION IN E 1/2 OF SW...,305000.0,150090,Rural Resi
141,2022-05-11,530151785,Jean A Mueller-Yanaga,Daniel Glasgow,TRACT IN SE 1/4 AND E 1/2 NE 1/4 SW 1/4 33-15-55,190000.0,96960,Rural Resi
142,2022-07-07,530023288,Central Properties,"Adair Holdings, LLC",9.883 ACRE TRACT IN N 1/2 N 1/2 6-16-53,126185.0,126185,Rural Resi

In [8]:
merged_df = pd.DataFrame()

for df in cleaned_dfs:
    merged_df = pd.concat([merged_df, df], ignore_index=True)
    display(merged_df)

,Sale Date,Parcel ID,Seller,Buyer,LEGAL DESCRIPTION,Sale Price,Assessor Location
0,2014-10-17,530041421,Robert & Denise Waite,Preston Walls,SOUTH PARK ADD. BLOCK 3 N 1/2 OF LOT 13 AND AL...,54500.0,Kimball
1,2014-10-29,530035642,Elizabeth Shandera,Chauncey & Stephanie Pedersen,KIMBALL HEIGHTS ADD. LOT 13,140000.0,Kimball
2,2014-11-14,530032732,Wilma Vencill,Michael Mowry,CLARKSON ADD. BLOCK 10 LOT 6 AND N. 25' OF LOT 7,57000.0,Kimball
3,2014-11-14,530042800,Krissy Petersen,Roy Hammond,SUNNYVIEW HEIGHTS ADD. BLOCK 13 LOT 14,49600.0,Kimball
4,2014-11-24,530047381,Dennis & Robin McIntosh,Marc & Elizabeth Taylor,ANTELOPEVILLE ADD. BLOCK 8 W 1/2 OF LOTS8 AND 9,102000.0,Kimball
...,...,...,...,...,...,...,...
83,2015-11-05,530016818,Stanley & Beverly Pearson,Barbara Michael,TRACT 200 FEET BY 300 FEET IN THE N 1/2 OF THE...,175750.0,Rural Resi
84,2015-11-20,530151659,Lawrence & Nicole Snyder,Robert & Fawney Vincent,4.954A. TRACT IN SW1/4 30-15-56,123000.0,Rural Resi
85,2016-01-25,530028050,Whiting Oil & Gas Corp,Austin Garner,63.398 A. TRACT IN SE CORNER 10-16-58,95000.0,Rural Resi
86,2016-03-06,530029146,Daniel & Misty Curtis,Natalie & Owen Elder,LOTS 6 & 7 LESS TRACT PRAIRIE RIDGE ESTATE...,185000.0,Rural Resi
87,2016-07-25,530028522,David & Martha Cannon,Paul & Linda Piatz,19.854 ACRE TRACT IN 12-16-59,173000.0,Rural Resi

,Sale Date,Parcel ID,Seller,Buyer,LEGAL DESCRIPTION,Sale Price,Assessor Location
0,2014-10-17,530041421,Robert & Denise Waite,Preston Walls,SOUTH PARK ADD. BLOCK 3 N 1/2 OF LOT 13 AND AL...,54500.0,Kimball
1,2014-10-29,530035642,Elizabeth Shandera,Chauncey & Stephanie Pedersen,KIMBALL HEIGHTS ADD. LOT 13,140000.0,Kimball
2,2014-11-14,530032732,Wilma Vencill,Michael Mowry,CLARKSON ADD. BLOCK 10 LOT 6 AND N. 25' OF LOT 7,57000.0,Kimball
3,2014-11-14,530042800,Krissy Petersen,Roy Hammond,SUNNYVIEW HEIGHTS ADD. BLOCK 13 LOT 14,49600.0,Kimball
4,2014-11-24,530047381,Dennis & Robin McIntosh,Marc & Elizabeth Taylor,ANTELOPEVILLE ADD. BLOCK 8 W 1/2 OF LOTS8 AND 9,102000.0,Kimball
...,...,...,...,...,...,...,...
208,2018-12-07,530061201,Sam & Lovina Gingerich,Tracy & Sabine Kasten,1.82 ACRES IN N 1/2 NW 1/4 35-15-54,45000.0,Rural Resi
209,2018-12-19,530009099,Maury D & Diane B Horst,Larry & Denise Loose,20.07 ACRE TRACT IN NE 1/4 5-14-54,105000.0,Rural Resi
210,2019-03-22,530157749,David & Joanna Hottell,Liam Dunn,TRACT IN SE 1/4 OF SE 1/4 OF SW 1/W 22-13-53,125000.0,Rural Resi
211,2019-05-13,530029073,Robert Mueller,Richard R & Kelli L Patterson,LOT 1 PRAIRIE RIDGE ESTATE 17-15-55,249000.0,Rural Resi
212,2019-08-30,530017377,Darren L & Kelleigh Huff,Teresa Teppert,11.449 ACRES IN THE SE 1/4 OF THE SW 1/4 SOUTH...,157000.0,Rural Resi

,Sale Date,Parcel ID,Seller,Buyer,LEGAL DESCRIPTION,Sale Price,Assessor Location
0,2014-10-17,530041421,Robert & Denise Waite,Preston Walls,SOUTH PARK ADD. BLOCK 3 N 1/2 OF LOT 13 AND AL...,54500.0,Kimball
1,2014-10-29,530035642,Elizabeth Shandera,Chauncey & Stephanie Pedersen,KIMBALL HEIGHTS ADD. LOT 13,140000.0,Kimball
2,2014-11-14,530032732,Wilma Vencill,Michael Mowry,CLARKSON ADD. BLOCK 10 LOT 6 AND N. 25' OF LOT 7,57000.0,Kimball
3,2014-11-14,530042800,Krissy Petersen,Roy Hammond,SUNNYVIEW HEIGHTS ADD. BLOCK 13 LOT 14,49600.0,Kimball
4,2014-11-24,530047381,Dennis & Robin McIntosh,Marc & Elizabeth Taylor,ANTELOPEVILLE ADD. BLOCK 8 W 1/2 OF LOTS8 AND 9,102000.0,Kimball
...,...,...,...,...,...,...,...
320,2017-04-24,530009285,Monica & Magdaleno Cajero,Donald Weeks,TRACT IN E 1/2 NE 1/4 OF 10-14-54 (26.849 ACRES),135000.0,Rural Resi
321,2017-06-16,530020173,Kristi & Ronald Cortney,Toni & Edward Barnes,TAX LOT 8 PART OF SE 1/4 OF THE NW 1/4 & NE 1/...,150499.0,Rural Resi
322,2017-07-12,530020041,Jason Hottell,Robin Whitehead,TAX LOT 14 MORGANS SUBDIVISION IN E 1/2 OF SW ...,187000.0,Rural Resi
323,2017-08-25,530010445,Lyle & Shonna Yung,Daniel & Mercedes Arnold,PART OF S 1/2 S 1/2 6-14-55 30.012 ACRES,235000.0,Rural Resi
324,2017-09-14,530151659,Robert & Fawney Vincent,Christine & Eddie Sharkey,4.954 ACRE TRACT IN SW 1/4 30-15-56,135000.0,Rural Resi

,Sale Date,Parcel ID,Seller,Buyer,LEGAL DESCRIPTION,Sale Price,Assessor Location,Assessed Value
0,2014-10-17,530041421,Robert & Denise Waite,Preston Walls,SOUTH PARK ADD. BLOCK 3 N 1/2 OF LOT 13 AND AL...,54500.0,Kimball,NaN
1,2014-10-29,530035642,Elizabeth Shandera,Chauncey & Stephanie Pedersen,KIMBALL HEIGHTS ADD. LOT 13,140000.0,Kimball,NaN
2,2014-11-14,530032732,Wilma Vencill,Michael Mowry,CLARKSON ADD. BLOCK 10 LOT 6 AND N. 25' OF LOT 7,57000.0,Kimball,NaN
3,2014-11-14,530042800,Krissy Petersen,Roy Hammond,SUNNYVIEW HEIGHTS ADD. BLOCK 13 LOT 14,49600.0,Kimball,NaN
4,2014-11-24,530047381,Dennis & Robin McIntosh,Marc & Elizabeth Taylor,ANTELOPEVILLE ADD. BLOCK 8 W 1/2 OF LOTS8 AND 9,102000.0,Kimball,NaN
...,...,...,...,...,...,...,...,...
449,2020-02-15,530010518,Trevor L Chrystal,Michael T & Renee A Geha,1.907 ACRES IN SE CORNER OF SW 1/4 7-14-55,80000.0,Rural Resi,74345
450,2020-03-13,530021609,Scott E & Susan L Lockwood,Dalton & Ainsley Lockwood,23.147 ACRES IN 36-15-57,490000.0,Rural Resi,300120
451,2020-03-14,530029103,Douglas J & Marvel L Linthicum,Trevor L & Nicole M Anderson,LOT 3 PRAIRIE RIDGE ESTATE 17-15-55,255000.0,Rural Resi,206040
452,2020-04-01,530018365,Walter L Wann,Robert D Dunkin III,TRACT IN NE 1/4 NW 1/4 31-15-55,70000.0,Rural Resi,87090
453,2020-07-24,530050439,Dwayne A & Jonita M Groves,Bradley Ray & Nicole Lynn Hottell,12.415 ACRE TRACT IN NE 1/4 29-15-55,135000.0,Rural Resi,197340

,Sale Date,Parcel ID,Seller,Buyer,LEGAL DESCRIPTION,Sale Price,Assessor Location,Assessed Value
0,2014-10-17,530041421,Robert & Denise Waite,Preston Walls,SOUTH PARK ADD. BLOCK 3 N 1/2 OF LOT 13 AND AL...,54500.0,Kimball,NaN
1,2014-10-29,530035642,Elizabeth Shandera,Chauncey & Stephanie Pedersen,KIMBALL HEIGHTS ADD. LOT 13,140000.0,Kimball,NaN
2,2014-11-14,530032732,Wilma Vencill,Michael Mowry,CLARKSON ADD. BLOCK 10 LOT 6 AND N. 25' OF LOT 7,57000.0,Kimball,NaN
3,2014-11-14,530042800,Krissy Petersen,Roy Hammond,SUNNYVIEW HEIGHTS ADD. BLOCK 13 LOT 14,49600.0,Kimball,NaN
4,2014-11-24,530047381,Dennis & Robin McIntosh,Marc & Elizabeth Taylor,ANTELOPEVILLE ADD. BLOCK 8 W 1/2 OF LOTS8 AND 9,102000.0,Kimball,NaN
...,...,...,...,...,...,...,...,...
616,2021-03-05,530010445,Daniel B Arnold,Timothy Wayne & Dixie Lee Smith,6-14-55 PART OF S1/2S1/2 6-14-55,330000.0,Rural Resi,215195
617,2021-03-25,530024640,Kathleen Atkins Trustee,Ryan Lukassen & Elyse Schlake,25-16-54 A TRACT IN THE N/2NE/4 25-16-54,265000.0,Rural Resi,161020
618,2021-05-03,530005069,Garland & Megan Hamilton,Sara Silvanage,6.502 ACRE TRACT IN NE1/4NE1/4 26-13-55,122000.0,Rural Resi,103510
619,2021-08-05,530010518,Michael T & Renee A Geha,Adam Geha,1.907 A. IN SE CORNER OF SW 1/4 7-14-55,80000.0,Rural Resi,74345
620,2021-09-28,530016818,Barbara K Michael,Carmen M Jackman,TRACT 200 FEET BY 300 FEET IN THE N 1/2 OF THE...,225000.0,Rural Resi,156655

,Sale Date,Parcel ID,Seller,Buyer,LEGAL DESCRIPTION,Sale Price,Assessor Location,Assessed Value
0,2014-10-17,530041421,Robert & Denise Waite,Preston Walls,SOUTH PARK ADD. BLOCK 3 N 1/2 OF LOT 13 AND AL...,54500.0,Kimball,NaN
1,2014-10-29,530035642,Elizabeth Shandera,Chauncey & Stephanie Pedersen,KIMBALL HEIGHTS ADD. LOT 13,140000.0,Kimball,NaN
2,2014-11-14,530032732,Wilma Vencill,Michael Mowry,CLARKSON ADD. BLOCK 10 LOT 6 AND N. 25' OF LOT 7,57000.0,Kimball,NaN
3,2014-11-14,530042800,Krissy Petersen,Roy Hammond,SUNNYVIEW HEIGHTS ADD. BLOCK 13 LOT 14,49600.0,Kimball,NaN
4,2014-11-24,530047381,Dennis & Robin McIntosh,Marc & Elizabeth Taylor,ANTELOPEVILLE ADD. BLOCK 8 W 1/2 OF LOTS8 AND 9,102000.0,Kimball,NaN
...,...,...,...,...,...,...,...,...
752,2018-06-15,530020696,Michael H & Karen M Isley,James N Columbia,A TRACT IN SE 1/4 28-15-56,165000.0,Rural Resi,NaN
753,2018-07-06,530031094,Karla J Jenkins,Marvin & Sandra Tabor,TRACT S OF UPRR IN SE 1/4 26-15-56,130000.0,Rural Resi,NaN
754,2018-07-18,530151470,Jared C & Melissa L Reich,Karla Jenkins,29.823 A TRACT IN NE 1/4 18-16-55,217500.0,Rural Resi,NaN
755,2018-08-01,530025779,Jeanne Anderson,Cheryl Delaplane,TRACT IN WEST PART OF NW 1/4 32-16-55,67000.0,Rural Resi,NaN
756,2018-09-14,530026937,Mary Ann Felkins,John M & Alicia I Buchart,7.015 ACRES IN THE NE 1/4 OF THE NE 1/4 OF TH ...,180000.0,Rural Resi,NaN

,Sale Date,Parcel ID,Seller,Buyer,LEGAL DESCRIPTION,Sale Price,Assessor Location,Assessed Value
0,2014-10-17,530041421,Robert & Denise Waite,Preston Walls,SOUTH PARK ADD. BLOCK 3 N 1/2 OF LOT 13 AND AL...,54500.0,Kimball,NaN
1,2014-10-29,530035642,Elizabeth Shandera,Chauncey & Stephanie Pedersen,KIMBALL HEIGHTS ADD. LOT 13,140000.0,Kimball,NaN
2,2014-11-14,530032732,Wilma Vencill,Michael Mowry,CLARKSON ADD. BLOCK 10 LOT 6 AND N. 25' OF LOT 7,57000.0,Kimball,NaN
3,2014-11-14,530042800,Krissy Petersen,Roy Hammond,SUNNYVIEW HEIGHTS ADD. BLOCK 13 LOT 14,49600.0,Kimball,NaN
4,2014-11-24,530047381,Dennis & Robin McIntosh,Marc & Elizabeth Taylor,ANTELOPEVILLE ADD. BLOCK 8 W 1/2 OF LOTS8 AND 9,102000.0,Kimball,NaN
...,...,...,...,...,...,...,...,...
889,2021-09-28,530016818,Barbara K Michael,Carmen M Jackman,TRACT 200 FEET BY 300 FEET IN THE N 1/2 OF THE...,225000.0,Rural Resi,156655
890,2022-04-11,530015951,Sammie M & Lovina Gingerich,Sammie & Talia L Gingerich,23.540 ACRES IN SE 1/4 S. OF UPRR 29-15-54,167000.0,Rural Resi,190030
891,2022-04-28,530020041,Michael A & Clara Sue Salazar,Matthew & Crystal Brown,TAX LOT 14 MORGAN'S SUBDIVISION IN E 1/2 OF SW...,305000.0,Rural Resi,150090
892,2022-05-11,530151785,Jean A Mueller-Yanaga,Daniel Glasgow,TRACT IN SE 1/4 AND E 1/2 NE 1/4 SW 1/4 33-15-55,190000.0,Rural Resi,96960
893,2022-07-07,530023288,Central Properties,"Adair Holdings, LLC",9.883 ACRE TRACT IN N 1/2 N 1/2 6-16-53,126185.0,Rural Resi,126185

In [9]:
merged_df.sort_values(by='Sale Date')

,Sale Date,Parcel ID,Seller,Buyer,LEGAL DESCRIPTION,Sale Price,Assessor Location,Assessed Value
0,2014-10-17,530041421,Robert & Denise Waite,Preston Walls,SOUTH PARK ADD. BLOCK 3 N 1/2 OF LOT 13 AND AL...,54500.0,Kimball,NaN
1,2014-10-29,530035642,Elizabeth Shandera,Chauncey & Stephanie Pedersen,KIMBALL HEIGHTS ADD. LOT 13,140000.0,Kimball,NaN
76,2014-11-06,530157938,William Spires,Andrew Knicely,3.99 A.TRACT IN SE1/4 28-15-56,80000.0,Rural Resi,NaN
2,2014-11-14,530032732,Wilma Vencill,Michael Mowry,CLARKSON ADD. BLOCK 10 LOT 6 AND N. 25' OF LOT 7,57000.0,Kimball,NaN
3,2014-11-14,530042800,Krissy Petersen,Roy Hammond,SUNNYVIEW HEIGHTS ADD. BLOCK 13 LOT 14,49600.0,Kimball,NaN
...,...,...,...,...,...,...,...,...
862,2022-08-12,530034344,Abraham Parra,"Lynn Tornberg, James Cleveland & Shawna Cleveland",FORSLINGS ADD. BLOCK 3 LOT 12,185000.0,Kimball,37575
863,2022-08-19,530042606,Dillon Hatfield,Carter Rompola,SUNNYVIEW HEIGHTS ADD. BLOCK 12 LOT 10,125000.0,Kimball,94675
864,2022-08-29,530033615,Linda Williams,"809 S Elm St, LLC",EAST MANOR FIRST ADD. BLOCK 1 LOT 9,83000.0,Kimball,46040
865,2022-09-09,530036843,"Kimball DJ, LLC",Eldon & Kylee Lewis,"LEAMINGS ADD, BLOCK 8 LOT 3 AND THE N 1/2 OF L...",120000.0,Kimball,70375
866,2022-09-26,530045109,Johnny D & Dawn Clifford,Mario Leiva Duran & Mirna Azucena Guerrero,BURG'S ADD. BLOCK 2 S 1/2 OF LOT 23 AND ALL LO...,39000.0,Kimball,39900

In [10]:
pd.set_option('display.max_rows', 100)
merged_df.loc[merged_df.duplicated(),:]

,Sale Date,Parcel ID,Seller,Buyer,LEGAL DESCRIPTION,Sale Price,Assessor Location,Assessed Value
213,2015-10-19,530035847,Donald Thompson,Carolyn & Jennette Wood,KINGSWOOD FIRST ADD. LOT 1,62000.0,Kimball,NaN
214,2015-10-26,530045036,William Loring,Aleta Lewis,BURG'S ADD. BLOCK 2 ALL OF SUBLOT 1 OF LOTS 1...,30000.0,Kimball,NaN
215,2015-10-27,530033003,William & Winifred Petersen,Matthew & Rachel Merryfield,DOWD'S FIRST ADD. BLOCK 2 LOT 1,87500.0,Kimball,NaN
216,2015-11-12,530017318,James & Charlotta Young,Jose & Fatima Lozoya,PART OF THE SW 1/4 SOUTH OF THE UPRR 28-15-55,95000.0,Kimball,NaN
217,2015-11-27,530033798,Marcelino Calderon,Daniel & Sherry Acheson,FAIRVIEW ADD. BLOCK 4 LOTS 21-22-23 AND 24,30000.0,Kimball,NaN
...,...,...,...,...,...,...,...,...
875,2021-06-05,530047640,Phillip G Niles,Hermila Torres Zapata & Socorro Munoz Molina,BUSHNELL VILLAGE ADD. BLOCK 3 LOT 17,38000.0,Bushnell,17670
876,2021-06-14,530068389,Geraldine Leonard,Bert & Debby Ruth Summers,ORKNEY'S ADD BLOCK 10 LOTS 1 AND 2,76000.0,Bushnell,41830
877,2021-08-17,530048914,Marilyn A Morgart,Joan M Fluit,ORKNEY'S ADD. BLOCK 13 LOTS 5 AND 6,52000.0,Bushnell,51940
884,2020-10-27,530109719,Terry Jefferson,Michael A & Clara Sue Salazar,1.61 ACRE TRACT IN SE 1/4 NW 1/4 29-15-55,103000.0,Rural Resi,52275
889,2021-09-28,530016818,Barbara K Michael,Carmen M Jackman,TRACT 200 FEET BY 300 FEET IN THE N 1/2 OF THE...,225000.0,Rural Resi,156655

In [11]:
sales_df = merged_df.loc[~merged_df.duplicated(),:]

In [12]:
sales_df.sort_values(by='Sale Date')

,Sale Date,Parcel ID,Seller,Buyer,LEGAL DESCRIPTION,Sale Price,Assessor Location,Assessed Value
0,2014-10-17,530041421,Robert & Denise Waite,Preston Walls,SOUTH PARK ADD. BLOCK 3 N 1/2 OF LOT 13 AND AL...,54500.0,Kimball,NaN
1,2014-10-29,530035642,Elizabeth Shandera,Chauncey & Stephanie Pedersen,KIMBALL HEIGHTS ADD. LOT 13,140000.0,Kimball,NaN
76,2014-11-06,530157938,William Spires,Andrew Knicely,3.99 A.TRACT IN SE1/4 28-15-56,80000.0,Rural Resi,NaN
2,2014-11-14,530032732,Wilma Vencill,Michael Mowry,CLARKSON ADD. BLOCK 10 LOT 6 AND N. 25' OF LOT 7,57000.0,Kimball,NaN
3,2014-11-14,530042800,Krissy Petersen,Roy Hammond,SUNNYVIEW HEIGHTS ADD. BLOCK 13 LOT 14,49600.0,Kimball,NaN
...,...,...,...,...,...,...,...,...
862,2022-08-12,530034344,Abraham Parra,"Lynn Tornberg, James Cleveland & Shawna Cleveland",FORSLINGS ADD. BLOCK 3 LOT 12,185000.0,Kimball,37575
863,2022-08-19,530042606,Dillon Hatfield,Carter Rompola,SUNNYVIEW HEIGHTS ADD. BLOCK 12 LOT 10,125000.0,Kimball,94675
864,2022-08-29,530033615,Linda Williams,"809 S Elm St, LLC",EAST MANOR FIRST ADD. BLOCK 1 LOT 9,83000.0,Kimball,46040
865,2022-09-09,530036843,"Kimball DJ, LLC",Eldon & Kylee Lewis,"LEAMINGS ADD, BLOCK 8 LOT 3 AND THE N 1/2 OF L...",120000.0,Kimball,70375
866,2022-09-26,530045109,Johnny D & Dawn Clifford,Mario Leiva Duran & Mirna Azucena Guerrero,BURG'S ADD. BLOCK 2 S 1/2 OF LOT 23 AND ALL LO...,39000.0,Kimball,39900

In [13]:
sales_df.loc[sales_df['Buyer'].str.contains("Lincoln")]

,Sale Date,Parcel ID,Seller,Buyer,LEGAL DESCRIPTION,Sale Price,Assessor Location,Assessed Value
45,2016-02-11,530040220,Steven Cleveland,Lincoln & Kelsey Brown,ORIGINAL KIMBALL ADD. BLOCK 10 LOTS 8 AND 9 ...,24000.0,Kimball,NaN
419,2020-08-28,530034360,William Russell,Lincoln Robert & Kelsey Leigh Brown,FORSLINGS ADDITION BLOCK 3 N 10' OF LOT 13 AND...,67500.0,Kimball,72230

## PID Requests

In [14]:
import requests
import json
from bs4 import BeautifulSoup as bs
from time import sleep
from random import randrange

In [15]:
# Define load_json function to process files
def load_json(results_file):
    pids = []
    with open(results_file, 'r') as data_file:
        data = data_file.readlines()
    for line in data:
        data_test = json.loads(line)
    for result in data_test['results']:
        pid = result.get('attributes', {}).get('PID')
        pids.append(pid)
    return pids

In [16]:
# URLs
#bulk_pid_url = "https://gis2.gworks.com/arcgis/rest/services/Kimball_County_NE_Assessor/MapServer/find"
#bulk_pid_query = "f=json&searchText=53000&layers=1,2&searchFields=&returnGeometry=true&sr=3857&token="
#detail_url = "https://report.gworks.com/report.ashx?county=kimball&id=530025930&type=assessor&subs=true&format=json"
#bulk_url = f"{bulk_pid_url}?{bulk_pid_query}"

In [17]:
bulk_pid_searches = []
bulk_pid_prefix = "5300"
for i in range(0,8):
    bulk_pid_searches.append(f"{bulk_pid_prefix}{i}")

# Add to catch any missed PIDs
bulk_pid_searches.append("530")
bulk_pid_searches.append("kimball")
bulk_pid_searches

['53000',
 '53001',
 '53002',
 '53003',
 '53004',
 '53005',
 '53006',
 '53007',
 '530',
 'kimball']

In [18]:
# Only need to run once to get query results
"""for pid in bulk_pid_searches:
    bulk_pid_url = "https://gis2.gworks.com/arcgis/rest/services/Kimball_County_NE_Assessor/MapServer/find"
    bulk_pid_query = f"f=json&searchText={pid}&layers=1,2&searchFields=&returnGeometry=true&sr=3857&token="
    bulk_url = f"{bulk_pid_url}?{bulk_pid_query}"
    r = requests.get(bulk_url)
    if r.status_code == 200:
        with open(f"{pid}_query.txt", "w") as out_file:
            out_file.writelines(r.text)
    sleep(10) # Sleep 10 seconds"""

'for pid in bulk_pid_searches:\n    bulk_pid_url = "https://gis2.gworks.com/arcgis/rest/services/Kimball_County_NE_Assessor/MapServer/find"\n    bulk_pid_query = f"f=json&searchText={pid}&layers=1,2&searchFields=&returnGeometry=true&sr=3857&token="\n    bulk_url = f"{bulk_pid_url}?{bulk_pid_query}"\n    r = requests.get(bulk_url)\n    if r.status_code == 200:\n        with open(f"{pid}_query.txt", "w") as out_file:\n            out_file.writelines(r.text)\n    sleep(10) # Sleep 10 seconds'

In [19]:
query_files = []
for f in os.listdir():
    if f.__contains__("_query"):
        query_files.append(f)
query_files

['53000_query.txt',
 '53001_query.txt',
 '53007_query.txt',
 '53003_query.txt',
 '53002_query.txt',
 'kimball_query.txt',
 '53004_query.txt',
 '53005_query.txt',
 '530_query.txt',
 '53006_query.txt']

In [20]:
pid_set = set()
for f in query_files:
    pids = load_json(f)
    pid_set.update(pids)

print(f"There are {len(pid_set)} pids for Kimball County.")

There are 4352 pids for Kimball County.

In [21]:
from IPython.display import clear_output
requests.urllib3.disable_warnings()
def get_detail(pids):
    proxies = {"http": "http://206.233.177.254:80"}
    if not os.path.exists("./PID_Details"):
        os.mkdir("./PID_Details")
        print("Folder PID_Details Created")
    else:
        print("Folder PID_Details Exists")
    for idx,pid in enumerate(pids):
        wait_time = randrange(10,15)
        detail_url = f"https://report.gworks.com/report.ashx?county=kimball&id={pid}&type=assessor&subs=true&format=json"
        print(f"Processing {pid}...")
        r = requests.get(detail_url, proxies=proxies, verify=False)
        if r.status_code == 200:
            print(f"Request successful: {r.status_code}")
            with open(f"./PID_Details/{pid}_detail.json", 'w') as detail_file:
                detail_file.writelines(r.text)
                print(f"{pid}_detail.json written")
        else:
            print(f"Request Failed.\nStatus Code: {r.status_code}\n{r.text}")
        print(f"{len(pids) - (idx + 1)} PIDs left")
        print(f"Sleeping for {wait_time} seconds")
        sleep(wait_time)
        if(idx + 1) % 100 == 0:
            print(f"Processed {idx + 1} records. Pausing for 10 minutes")
            #sleep(600)
        clear_output(wait=True)

In [28]:
def existing_records(pid_set):
    existing_records = set()
    existing_files = os.listdir("PID_Details")
    for f in existing_files:
        pattern = r"(\d*)"
        pattern = re.compile(pattern)
        match = pattern.match(f)
        existing_records.add(match[0])
    print(len(pid_set))
    print(len(existing_records))
    need_details = set.difference(pid_set,existing_records)
    print(f"{len(need_details)} Records need to be processed.")
    print(need_details)
    return need_details

In [29]:
need_details = existing_records(pid_set)

4352
4349
3 Records need to be processed.
{'5300133312', '0', '9999'}

In [27]:
get_detail(need_details)

Folder PID_Details Exists
Processing 5300133312...
Request Failed.
Status Code: 500
<!DOCTYPE html>
<html>
    <head>
        <title>Runtime Error</title>
        <meta name="viewport" content="width=device-width" />
        <style>
         body {font-family:"Verdana";font-weight:normal;font-size: .7em;color:black;}
         p {font-family:"Verdana";font-weight:normal;color:black;margin-top: -5px}
         b {font-family:"Verdana";font-weight:bold;color:black;margin-top: -5px}
         H1 { font-family:"Verdana";font-weight:normal;font-size:18pt;color:red }
         H2 { font-family:"Verdana";font-weight:normal;font-size:14pt;color:maroon }
         pre {font-family:"Consolas","Lucida Console",Monospace;font-size:11pt;margin:0;padding:0.5em;line-height:14pt}
         .marker {font-weight: bold; color: black;text-decoration: none;}
         .version {color: gray;}
         .error {margin-bottom: 10px;}
         .expandable { text-decoration:underline; font-weight:bold; color:navy; cursor:pointer; }
         @media screen and (max-width: 639px) {
          pre { width: 440px; overflow: auto; white-space: pre-wrap; word-wrap: break-word; }
         }
         @media screen and (max-width: 479px) {
          pre { width: 280px; }
         }
        </style>
    </head>

    <body bgcolor="white">

            <span><H1>Server Error in '/' Application.<hr width=100% size=1 color=silver></H1>

            <h2> <i>Runtime Error</i> </h2></span>

            <font face="Arial, Helvetica, Geneva, SunSans-Regular, sans-serif ">

            <b> Description: </b>An application error occurred on the server. The current custom error settings for this application prevent the details of the application error from being viewed remotely (for security reasons). It could, however, be viewed by browsers running on the local server machine.
            <br><br>

            <b>Details:</b> To enable the details of this specific error message to be viewable on remote machines, please create a &lt;customErrors&gt; tag within a &quot;web.config&quot; configuration file located in the root directory of the current web application. This &lt;customErrors&gt; tag should then have its &quot;mode&quot; attribute set to &quot;Off&quot;.<br><br>

            <table width=100% bgcolor="#ffffcc">
               <tr>
                  <td>
                      <code><pre>

&lt;!-- Web.Config Configuration File --&gt;

&lt;configuration&gt;
    &lt;system.web&gt;
        &lt;customErrors mode=&quot;Off&quot;/&gt;
    &lt;/system.web&gt;
&lt;/configuration&gt;</pre>                      </code>

                  </td>
               </tr>
            </table>

            <br>

            <b>Notes:</b> The current error page you are seeing can be replaced by a custom error page by modifying the &quot;defaultRedirect&quot; attribute of the application&#39;s &lt;customErrors&gt; configuration tag to point to a custom error page URL.<br><br>

            <table width=100% bgcolor="#ffffcc">
               <tr>
                  <td>
                      <code><pre>

&lt;!-- Web.Config Configuration File --&gt;

&lt;configuration&gt;
    &lt;system.web&gt;
        &lt;customErrors mode=&quot;RemoteOnly&quot; defaultRedirect=&quot;mycustompage.htm&quot;/&gt;
    &lt;/system.web&gt;
&lt;/configuration&gt;</pre>                      </code>

                  </td>
               </tr>
            </table>

            <br>

            </font>

    </body>
</html>

2 PIDs left
Sleeping for 14 seconds

KeyboardInterrupt:

In [49]:
proxies = {"http": "http://65.20.235.40:8080"}
r = requests.get("https://report.gworks.com/report.ashx?county=kimball&id=530035669&type=assessor&subs=true&format=json", proxies=proxies, verify=False)
r.text

'{"items":[{"type":"report","title":"Buffalo County Assessor","template":"DefaultStyleTemplate","format":{},"items":[{"type":"table","title":"Parcel Information","formtype":"normal","HeaderFormat":"background-color: Black !important;","items":[{"type":"field","title":"Parcel ID:","formtype":"","HeaderFormat":"","items":["530035669"]},{"type":"field","title":"Map Number","formtype":"","HeaderFormat":"","items":[""]},{"type":"field","title":"State Geo Code","formtype":"","HeaderFormat":"","items":["2809-00-0-30041-000-0015"]},{"type":"field","title":"Cadastral #","formtype":"","HeaderFormat":"","items":[""]},{"type":"field","title":"Images","formtype":"","HeaderFormat":"","items":["  <a target=\'_blank\' href = \'https://kimball.gworks.com/photos/0530035669_2.jpg\' >Photo #1</a>  <a target=\'_blank\' href = \'https://kimball.gworks.com/photos/0530035669_3.jpg\' >Photo #2</a>  <a target=\'_blank\' href = \'https://kimball.gworks.com/photos/0530035669_4.jpg\' >Photo #3</a>  <a target=\'_blank\' href = \'https://kimball.gworks.com/photos/0530035669_1.jpg\' >Sketch #1</a>","",""]},{"type":"field","title":"Current Owner:","formtype":"","HeaderFormat":"","items":["DAVIS/VIRGINIA ROSE \\r704 S WEBSTER ST\\rKIMBALL, NE  69145"]},{"type":"field","title":"Situs Address:","formtype":"","HeaderFormat":"","items":["704 S WEBSTER STREET KIMBALL"]},{"type":"field","title":"Tax District:","formtype":"","HeaderFormat":"","items":["40"]},{"type":"field","title":"School District:","formtype":"","HeaderFormat":"","items":["KIMBALL #1, 53-0001"]},{"type":"field","title":"Account Type:","formtype":"","HeaderFormat":"","items":["Residential"]},{"type":"field","title":"Legal Description:","formtype":"","HeaderFormat":"","items":["KIMBALL HEIGHTS ADD. LOT 15 (CARD #12)**704 SOUTH WEBSTER STREET (1078382)"]},{"type":"field","title":"Lot Width:","formtype":"","HeaderFormat":"","items":["75.00"]},{"type":"field","title":"Lot Depth:","formtype":"","HeaderFormat":"","items":["140.00"]},{"type":"field","title":"Total Lot Size:","formtype":"","HeaderFormat":"","items":["10500.00 sq ft"]}]},{"type":"table","title":"Assessed Values","formtype":"list","HeaderFormat":"background-color: Black !important;","items":[{"type":"field","title":"Year","formtype":"list","HeaderFormat":"","items":["2023","2022"]},{"type":"field","title":"Total","formtype":"list","HeaderFormat":"","items":["$70,190","$74,065"]},{"type":"field","title":"Land","formtype":"list","HeaderFormat":"","items":["$11,900","$10,185"]},{"type":"field","title":"Outbuilding","formtype":"list","HeaderFormat":"","items":["$0","$0"]},{"type":"field","title":"Dwelling","formtype":"list","HeaderFormat":"","items":["$58,290","$63,880"]}]},{"type":"table","title":"Yearly Tax Information","formtype":"list","HeaderFormat":"background-color: Black !important;","items":[{"type":"field","title":"Year","formtype":"list","HeaderFormat":"","items":["2023"]},{"type":"field","title":"Amount","formtype":"list","HeaderFormat":"","items":["$1,297.14"]},{"type":"field","title":"Levy","formtype":"list","HeaderFormat":"","items":["1.959336"]}]},{"type":"table","title":"2023 Tax Levy","formtype":"list","HeaderFormat":"background-color: Black !important;","items":[{"type":"field","title":"Description ","formtype":"list","HeaderFormat":"","items":["COUNTY GENERAL","KIMBALL #1","WNCC","ESU #13","HISTORICAL SOCIETY","AG SOCIETY","KIMBALL AIRPORT GENERAL","KIMBALL CITY BOND","S.P.N.R.D","KIMBALL CITY GENERAL","KIMBALL AIRPORT BOND"]},{"type":"field","title":"Rate","formtype":"list","HeaderFormat":"","items":["0.47937200","0.90000000","0.09891400","0.01509400","0.00210400","0.01012800","0.01695600","0.00000000","0.04734200","0.36157200","0.02785400"]}]},{"type":"table","title":"Sales Information","formtype":"list","HeaderFormat":"background-color: Black !important;","items":[{"type":"field","title":"Sale Date","formtype":"list","HeaderFormat":"","items":["09/24/2019"]},{"type":"field","title":"Sale Price","formtype":"list","HeaderFormat":"","items":["$86,000.00"]},{"type":"field","title":"Book & Page","formtype":"list","HeaderFormat":"","items":["80 / 800"]},{"type":"field","title":"Grantor","formtype":"list","HeaderFormat":"","items":["SLADKY/JENNIFER R "]},{"type":"field","title":"Parcel Ids","formtype":"list","HeaderFormat":"","items":[""]}]},{"type":"table","title":"Property Classification","formtype":"doubleTable","HeaderFormat":"background-color: Black !important;","items":[{"type":"field","title":"Status:","formtype":"","HeaderFormat":"","items":["Improved"]},{"type":"field","title":"Location:","formtype":"","HeaderFormat":"","items":["Urban"]},{"type":"field","title":"Property Class:","formtype":"","HeaderFormat":"","items":["Residential"]},{"type":"field","title":"City Size:","formtype":"","HeaderFormat":"","items":["2,501-5,000"]},{"type":"field","title":"Zoning:","formtype":"","HeaderFormat":"","items":["Single Family"]},{"type":"field","title":"Lot Size:","formtype":"","HeaderFormat":"","items":["10,000-20,000 sq. ft."]}]},{"type":"table","title":"Land Information","formtype":"list","HeaderFormat":"background-color: Black !important;","items":[{"type":"field","title":"Lot Width (ft)","formtype":"list","HeaderFormat":"","items":["75.00"]},{"type":"field","title":"Lot Depth (ft)","formtype":"list","HeaderFormat":"","items":["140.00"]},{"type":"field","title":"Description","formtype":"list","HeaderFormat":"","items":["75.00 x 140.00 FEET"]},{"type":"field","title":"Lot Size","formtype":"list","HeaderFormat":"","items":["10500.00 sq ft"]}]},{"type":"table","title":"Residential Datasheet","formtype":"doubleTable","HeaderFormat":"background-color: Black !important;","items":[{"type":"field","title":"Zoning:","formtype":"","HeaderFormat":"","items":["Single Family"]},{"type":"field","title":"Condition:","formtype":"","HeaderFormat":"","items":["Average"]},{"type":"field","title":"Year Built:","formtype":"","HeaderFormat":"","items":["1950"]},{"type":"field","title":"Style:","formtype":"","HeaderFormat":"","items":["100%   One Story "]},{"type":"field","title":"Exterior:","formtype":"","HeaderFormat":"","items":["100%   Frame, Siding, Vinyl "]},{"type":"field","title":"Bathrooms:","formtype":"","HeaderFormat":"","items":["2.00"]},{"type":"field","title":"Bedrooms:","formtype":"","HeaderFormat":"","items":["3"]},{"type":"field","title":"Heating/Cooling:","formtype":"","HeaderFormat":"","items":[" 100%   Forced Air Furnace "]},{"type":"field","title":"Plumbing Fixtures:","formtype":"","HeaderFormat":"","items":["9"]},{"type":"field","title":"Min Finish:","formtype":"","HeaderFormat":"","items":["0 sq. ft"]},{"type":"field","title":"Basement Size:","formtype":"","HeaderFormat":"","items":["768 sq. ft"]},{"type":"field","title":"Part Finish:","formtype":"","HeaderFormat":"","items":["768 sq. ft"]},{"type":"field","title":"Building Size:","formtype":"","HeaderFormat":"","items":["864 sq. ft"]},{"type":"field","title":"Garage 1:","formtype":"","HeaderFormat":"","items":["Detached Garage"]},{"type":"field","title":"Quality:","formtype":"","HeaderFormat":"","items":["Fair"]},{"type":"field","title":"Garage 1 Size:","formtype":"","HeaderFormat":"","items":["740 sq. ft"]}]},{"type":"table","title":"Dwelling Data","formtype":"list","HeaderFormat":"background-color: Black !important;","items":[{"type":"field","title":"Description","formtype":"list","HeaderFormat":"","items":["Floor Allowance","Raised Slab Porch"]},{"type":"field","title":"Units","formtype":"list","HeaderFormat":"","items":["864","28"]},{"type":"field","title":"Value","formtype":"list","HeaderFormat":"","items":["N/A","N/A"]}]},{"type":"table","title":"Photo/Sketch","formtype":"normal","HeaderFormat":"background-color: Black !important;","items":[{"type":"field","title":"","formtype":"","HeaderFormat":"","items":["<img id=\'photo1\' src = \'https://kimball.gworks.com/photos/0530035669_2.jpg\'style=\'width: 100%\'   \'/>","<img id=\'sketch1\' src = \'https://kimball.gworks.com/photos/0530035669_1.jpg\'style=\'width: 100%\' \'/>"]}]}]}]}'

print(r.status_code)