## Housing Sale Price Predictions

### Term Project

## Lincoln Brown

## DSC550-T302

## Professor Werner

In [22]:
import pandas as pd
import os
import numpy as np
import re

In [27]:
files = os.listdir()
file_list = []
years = []
df_list = []

In [36]:
for f in files:
    if f.__contains__('Resi'):
        file_list.append(f)
        pattern = "(\d{4})-(\d{4})"
        pattern = re.compile(pattern)
        [f_years] = pattern.findall(f)
        print(f_years)
        years.append(f_years)

('2014', '2016')
('2017', '2019')
('2015', '2017')
('2018', '2020')
('2019', '2021')
('2016', '2018')
('2020', '2022')

In [178]:
df_14_16 = pd.read_excel(file_list[0], header=0, skiprows=[0,1])
df_17_19 = pd.read_excel(file_list[1], header=0, skiprows=[0,1,3])
df_15_17 = pd.read_excel(file_list[2], header=0, skiprows=[0,1])
df_18_20 = pd.read_excel(file_list[3], header=2, skiprows=[0,1,3])
df_19_21 = pd.read_excel(file_list[4], header=1, skiprows=[0,3])
df_16_18 = pd.read_excel(file_list[5], header=0, skiprows=[0,1])
df_20_22 = pd.read_excel(file_list[6], header=2, skiprows=[0,3])

/home/x/anaconda3/lib/python3.11/site-packages/openpyxl/worksheet/header_footer.py:48: UserWarning: Cannot parse header or footer so it will be ignored
  warn("""Cannot parse header or footer so it will be ignored""")
/home/x/anaconda3/lib/python3.11/site-packages/openpyxl/worksheet/header_footer.py:48: UserWarning: Cannot parse header or footer so it will be ignored
  warn("""Cannot parse header or footer so it will be ignored""")
/home/x/anaconda3/lib/python3.11/site-packages/openpyxl/worksheet/header_footer.py:48: UserWarning: Cannot parse header or footer so it will be ignored
  warn("""Cannot parse header or footer so it will be ignored""")
/home/x/anaconda3/lib/python3.11/site-packages/openpyxl/worksheet/header_footer.py:48: UserWarning: Cannot parse header or footer so it will be ignored
  warn("""Cannot parse header or footer so it will be ignored""")

,Sale Date,Parcel ID,Seller,Buyer,LEGAL DESCRIPTION,Sale Price,Assessor Location
0,2016-10-13,530045583.0,James Buckley,Scott Christensen,BURGS ADD. BLOCK 6 LOT 8,37000.0,Kimball
1,2016-10-17,530041286.0,Charles & Carolyn Carlson,Richard & Gloria Brookman,SOUTH PARK ADD. BLOCK 2 ALL LOT 8 AND S1/8 OF ...,150000.0,Kimball
2,2016-10-20,530035448.0,James Prince & Nancy Garrett,Patricia Biesecker & Deanna Bleyle,HUFFS SECOND ADD. BLOCK 1 S. 5' OF LOT 1 AND A...,120000.0,Kimball
3,2016-10-24,530032546.0,Claire Tritt,Ricky & Julia Gehrig,CLARKSON ADD. BLOCK 8 S. 20' OF LOT 7 AND ALL ...,83000.0,Kimball
4,2016-11-05,530045273.0,Jennifer Dillinger,Rachel Rowe,BURG'S ADD. BLOCK 4 ALL LOT 7 AND N 15' OF LOT 8,30000.0,Kimball
...,...,...,...,...,...,...,...
137,2018-06-15,530020696.0,Michael H & Karen M Isley,James N Columbia,A TRACT IN SE 1/4 28-15-56,165000.0,Rural Resi
138,2018-07-06,530031094.0,Karla J Jenkins,Marvin & Sandra Tabor,TRACT S OF UPRR IN SE 1/4 26-15-56,130000.0,Rural Resi
139,2018-07-18,530151470.0,Jared C & Melissa L Reich,Karla Jenkins,29.823 A TRACT IN NE 1/4 18-16-55,217500.0,Rural Resi
140,2018-08-01,530025779.0,Jeanne Anderson,Cheryl Delaplane,TRACT IN WEST PART OF NW 1/4 32-16-55,67000.0,Rural Resi
141,2018-09-14,530026937.0,Mary Ann Felkins,John M & Alicia I Buchart,7.015 ACRES IN THE NE 1/4 OF THE NE 1/4 OF TH ...,180000.0,Rural Resi

In [162]:
df_20_22

,Sale Date,Parcel ID,Seller,Buyer,LEGAL DESCRIPTION,Sale Price,Assessed Value,Assessor Location
0,2020-10-01,530033429.0,Ka'Lani O'Shea,Sharon June Pickering,DOWD'S SECOND ADD. BLOCK - LOT 14 (CARD #14),100000.0,113040,Kimball
1,2020-10-01,530036932.0,Chico R Fernandez,Crystal Kisicki,LEAMINGS ADD. BLOCK 9 S. 39' OF THE W. 80' OF ...,38000.0,27545,Kimball
2,2020-10-06,530033488.0,Justin W & Jacqueline N Prather,Anthony & Linda Madrid,DOWD'S SECOND ADD. BLOCK - LOT 19,145000.0,156090,Kimball
3,2020-10-06,530039036.0,James & Donna Cederburg,Caleb Reuter,SOUTH PARK ADD. BLOCK 16 W. 110' OF LOT 8 & W....,47900.0,36120,Kimball
4,2020-10-20,530042959.0,Carol L Meyer,Danny E Yung,SUNNYVIEW HEIGHTS ADD. BLOCK 14 N. 5' OF LOT 1...,71100.0,82945,Kimball
...,...,...,...,...,...,...,...,...
137,2021-09-28,530016818.0,Barbara K Michael,Carmen M Jackman,TRACT 200 FEET BY 300 FEET IN THE N 1/2 OF THE...,225000.0,156655,Rural Resi
138,2022-04-11,530015951.0,Sammie M & Lovina Gingerich,Sammie & Talia L Gingerich,23.540 ACRES IN SE 1/4 S. OF UPRR 29-15-54,167000.0,190030,Rural Resi
139,2022-04-28,530020041.0,Michael A & Clara Sue Salazar,Matthew & Crystal Brown,TAX LOT 14 MORGAN'S SUBDIVISION IN E 1/2 OF SW...,305000.0,150090,Rural Resi
140,2022-05-11,530151785.0,Jean A Mueller-Yanaga,Daniel Glasgow,TRACT IN SE 1/4 AND E 1/2 NE 1/4 SW 1/4 33-15-55,190000.0,96960,Rural Resi
141,2022-07-07,530023288.0,Central Properties,"Adair Holdings, LLC",9.883 ACRE TRACT IN N 1/2 N 1/2 6-16-53,126185.0,126185,Rural Resi